; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -global-isel=0 -mtriple=amdgpu10.10-amd-amdhsa -mcpu=gfx1010 -amdgpu-sqtt-combine-events=false < %s | FileCheck --check-prefix=GFX10 %s
; RUN: llc -global-isel=1 -mtriple=amdgpu10.10-amd-amdhsa -mcpu=gfx1010 -amdgpu-sqtt-combine-events=false < %s | FileCheck --check-prefix=GFX10 %s

; Event ids that don't fit in the 8 usable bits of s_ttracedata_imm fall back
; to an m0 write followed by s_ttracedata.

define void @sqtt_events() {
; GFX10-LABEL: sqtt_events:
; GFX10:       ; %bb.0:
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX10-NEXT:  .Lsqtt_event.0:
; GFX10-NEXT:    s_ttracedata_imm 0x0
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.1:
; GFX10-NEXT:    s_ttracedata_imm 0x1
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.2:
; GFX10-NEXT:    s_ttracedata_imm 0x2
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.3:
; GFX10-NEXT:    s_ttracedata_imm 0x3
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.4:
; GFX10-NEXT:    s_ttracedata_imm 0x4
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.5:
; GFX10-NEXT:    s_ttracedata_imm 0x5
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.6:
; GFX10-NEXT:    s_ttracedata_imm 0x6
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.7:
; GFX10-NEXT:    s_ttracedata_imm 0x7
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.8:
; GFX10-NEXT:    s_ttracedata_imm 0x8
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.9:
; GFX10-NEXT:    s_ttracedata_imm 0x9
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.10:
; GFX10-NEXT:    s_ttracedata_imm 0xa
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.11:
; GFX10-NEXT:    s_ttracedata_imm 0xb
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.12:
; GFX10-NEXT:    s_ttracedata_imm 0xc
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.13:
; GFX10-NEXT:    s_ttracedata_imm 0xd
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.14:
; GFX10-NEXT:    s_ttracedata_imm 0xe
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.15:
; GFX10-NEXT:    s_ttracedata_imm 0xf
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.16:
; GFX10-NEXT:    s_ttracedata_imm 0x10
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.17:
; GFX10-NEXT:    s_ttracedata_imm 0x11
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.18:
; GFX10-NEXT:    s_ttracedata_imm 0x12
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.19:
; GFX10-NEXT:    s_ttracedata_imm 0x13
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.20:
; GFX10-NEXT:    s_ttracedata_imm 0x14
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.21:
; GFX10-NEXT:    s_ttracedata_imm 0x15
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.22:
; GFX10-NEXT:    s_ttracedata_imm 0x16
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.23:
; GFX10-NEXT:    s_ttracedata_imm 0x17
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.24:
; GFX10-NEXT:    s_ttracedata_imm 0x18
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.25:
; GFX10-NEXT:    s_ttracedata_imm 0x19
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.26:
; GFX10-NEXT:    s_ttracedata_imm 0x1a
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.27:
; GFX10-NEXT:    s_ttracedata_imm 0x1b
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.28:
; GFX10-NEXT:    s_ttracedata_imm 0x1c
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.29:
; GFX10-NEXT:    s_ttracedata_imm 0x1d
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.30:
; GFX10-NEXT:    s_ttracedata_imm 0x1e
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.31:
; GFX10-NEXT:    s_ttracedata_imm 0x1f
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.32:
; GFX10-NEXT:    s_ttracedata_imm 0x20
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.33:
; GFX10-NEXT:    s_ttracedata_imm 0x21
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.34:
; GFX10-NEXT:    s_ttracedata_imm 0x22
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.35:
; GFX10-NEXT:    s_ttracedata_imm 0x23
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.36:
; GFX10-NEXT:    s_ttracedata_imm 0x24
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.37:
; GFX10-NEXT:    s_ttracedata_imm 0x25
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.38:
; GFX10-NEXT:    s_ttracedata_imm 0x26
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.39:
; GFX10-NEXT:    s_ttracedata_imm 0x27
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.40:
; GFX10-NEXT:    s_ttracedata_imm 0x28
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.41:
; GFX10-NEXT:    s_ttracedata_imm 0x29
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.42:
; GFX10-NEXT:    s_ttracedata_imm 0x2a
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.43:
; GFX10-NEXT:    s_ttracedata_imm 0x2b
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.44:
; GFX10-NEXT:    s_ttracedata_imm 0x2c
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.45:
; GFX10-NEXT:    s_ttracedata_imm 0x2d
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.46:
; GFX10-NEXT:    s_ttracedata_imm 0x2e
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.47:
; GFX10-NEXT:    s_ttracedata_imm 0x2f
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.48:
; GFX10-NEXT:    s_ttracedata_imm 0x30
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.49:
; GFX10-NEXT:    s_ttracedata_imm 0x31
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.50:
; GFX10-NEXT:    s_ttracedata_imm 0x32
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.51:
; GFX10-NEXT:    s_ttracedata_imm 0x33
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.52:
; GFX10-NEXT:    s_ttracedata_imm 0x34
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.53:
; GFX10-NEXT:    s_ttracedata_imm 0x35
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.54:
; GFX10-NEXT:    s_ttracedata_imm 0x36
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.55:
; GFX10-NEXT:    s_ttracedata_imm 0x37
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.56:
; GFX10-NEXT:    s_ttracedata_imm 0x38
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.57:
; GFX10-NEXT:    s_ttracedata_imm 0x39
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.58:
; GFX10-NEXT:    s_ttracedata_imm 0x3a
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.59:
; GFX10-NEXT:    s_ttracedata_imm 0x3b
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.60:
; GFX10-NEXT:    s_ttracedata_imm 0x3c
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.61:
; GFX10-NEXT:    s_ttracedata_imm 0x3d
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.62:
; GFX10-NEXT:    s_ttracedata_imm 0x3e
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.63:
; GFX10-NEXT:    s_ttracedata_imm 0x3f
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.64:
; GFX10-NEXT:    s_ttracedata_imm 0x40
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.65:
; GFX10-NEXT:    s_ttracedata_imm 0x41
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.66:
; GFX10-NEXT:    s_ttracedata_imm 0x42
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.67:
; GFX10-NEXT:    s_ttracedata_imm 0x43
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.68:
; GFX10-NEXT:    s_ttracedata_imm 0x44
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.69:
; GFX10-NEXT:    s_ttracedata_imm 0x45
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.70:
; GFX10-NEXT:    s_ttracedata_imm 0x46
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.71:
; GFX10-NEXT:    s_ttracedata_imm 0x47
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.72:
; GFX10-NEXT:    s_ttracedata_imm 0x48
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.73:
; GFX10-NEXT:    s_ttracedata_imm 0x49
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.74:
; GFX10-NEXT:    s_ttracedata_imm 0x4a
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.75:
; GFX10-NEXT:    s_ttracedata_imm 0x4b
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.76:
; GFX10-NEXT:    s_ttracedata_imm 0x4c
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.77:
; GFX10-NEXT:    s_ttracedata_imm 0x4d
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.78:
; GFX10-NEXT:    s_ttracedata_imm 0x4e
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.79:
; GFX10-NEXT:    s_ttracedata_imm 0x4f
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.80:
; GFX10-NEXT:    s_ttracedata_imm 0x50
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.81:
; GFX10-NEXT:    s_ttracedata_imm 0x51
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.82:
; GFX10-NEXT:    s_ttracedata_imm 0x52
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.83:
; GFX10-NEXT:    s_ttracedata_imm 0x53
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.84:
; GFX10-NEXT:    s_ttracedata_imm 0x54
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.85:
; GFX10-NEXT:    s_ttracedata_imm 0x55
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.86:
; GFX10-NEXT:    s_ttracedata_imm 0x56
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.87:
; GFX10-NEXT:    s_ttracedata_imm 0x57
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.88:
; GFX10-NEXT:    s_ttracedata_imm 0x58
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.89:
; GFX10-NEXT:    s_ttracedata_imm 0x59
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.90:
; GFX10-NEXT:    s_ttracedata_imm 0x5a
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.91:
; GFX10-NEXT:    s_ttracedata_imm 0x5b
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.92:
; GFX10-NEXT:    s_ttracedata_imm 0x5c
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.93:
; GFX10-NEXT:    s_ttracedata_imm 0x5d
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.94:
; GFX10-NEXT:    s_ttracedata_imm 0x5e
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.95:
; GFX10-NEXT:    s_ttracedata_imm 0x5f
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.96:
; GFX10-NEXT:    s_ttracedata_imm 0x60
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.97:
; GFX10-NEXT:    s_ttracedata_imm 0x61
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.98:
; GFX10-NEXT:    s_ttracedata_imm 0x62
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.99:
; GFX10-NEXT:    s_ttracedata_imm 0x63
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.100:
; GFX10-NEXT:    s_ttracedata_imm 0x64
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.101:
; GFX10-NEXT:    s_ttracedata_imm 0x65
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.102:
; GFX10-NEXT:    s_ttracedata_imm 0x66
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.103:
; GFX10-NEXT:    s_ttracedata_imm 0x67
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.104:
; GFX10-NEXT:    s_ttracedata_imm 0x68
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.105:
; GFX10-NEXT:    s_ttracedata_imm 0x69
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.106:
; GFX10-NEXT:    s_ttracedata_imm 0x6a
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.107:
; GFX10-NEXT:    s_ttracedata_imm 0x6b
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.108:
; GFX10-NEXT:    s_ttracedata_imm 0x6c
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.109:
; GFX10-NEXT:    s_ttracedata_imm 0x6d
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.110:
; GFX10-NEXT:    s_ttracedata_imm 0x6e
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.111:
; GFX10-NEXT:    s_ttracedata_imm 0x6f
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.112:
; GFX10-NEXT:    s_ttracedata_imm 0x70
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.113:
; GFX10-NEXT:    s_ttracedata_imm 0x71
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.114:
; GFX10-NEXT:    s_ttracedata_imm 0x72
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.115:
; GFX10-NEXT:    s_ttracedata_imm 0x73
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.116:
; GFX10-NEXT:    s_ttracedata_imm 0x74
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.117:
; GFX10-NEXT:    s_ttracedata_imm 0x75
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.118:
; GFX10-NEXT:    s_ttracedata_imm 0x76
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.119:
; GFX10-NEXT:    s_ttracedata_imm 0x77
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.120:
; GFX10-NEXT:    s_ttracedata_imm 0x78
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.121:
; GFX10-NEXT:    s_ttracedata_imm 0x79
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.122:
; GFX10-NEXT:    s_ttracedata_imm 0x7a
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.123:
; GFX10-NEXT:    s_ttracedata_imm 0x7b
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.124:
; GFX10-NEXT:    s_ttracedata_imm 0x7c
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.125:
; GFX10-NEXT:    s_ttracedata_imm 0x7d
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.126:
; GFX10-NEXT:    s_ttracedata_imm 0x7e
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.127:
; GFX10-NEXT:    s_ttracedata_imm 0x7f
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.128:
; GFX10-NEXT:    s_ttracedata_imm 0x80
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.129:
; GFX10-NEXT:    s_ttracedata_imm 0x81
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.130:
; GFX10-NEXT:    s_ttracedata_imm 0x82
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.131:
; GFX10-NEXT:    s_ttracedata_imm 0x83
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.132:
; GFX10-NEXT:    s_ttracedata_imm 0x84
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.133:
; GFX10-NEXT:    s_ttracedata_imm 0x85
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.134:
; GFX10-NEXT:    s_ttracedata_imm 0x86
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.135:
; GFX10-NEXT:    s_ttracedata_imm 0x87
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.136:
; GFX10-NEXT:    s_ttracedata_imm 0x88
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.137:
; GFX10-NEXT:    s_ttracedata_imm 0x89
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.138:
; GFX10-NEXT:    s_ttracedata_imm 0x8a
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.139:
; GFX10-NEXT:    s_ttracedata_imm 0x8b
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.140:
; GFX10-NEXT:    s_ttracedata_imm 0x8c
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.141:
; GFX10-NEXT:    s_ttracedata_imm 0x8d
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.142:
; GFX10-NEXT:    s_ttracedata_imm 0x8e
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.143:
; GFX10-NEXT:    s_ttracedata_imm 0x8f
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.144:
; GFX10-NEXT:    s_ttracedata_imm 0x90
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.145:
; GFX10-NEXT:    s_ttracedata_imm 0x91
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.146:
; GFX10-NEXT:    s_ttracedata_imm 0x92
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.147:
; GFX10-NEXT:    s_ttracedata_imm 0x93
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.148:
; GFX10-NEXT:    s_ttracedata_imm 0x94
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.149:
; GFX10-NEXT:    s_ttracedata_imm 0x95
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.150:
; GFX10-NEXT:    s_ttracedata_imm 0x96
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.151:
; GFX10-NEXT:    s_ttracedata_imm 0x97
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.152:
; GFX10-NEXT:    s_ttracedata_imm 0x98
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.153:
; GFX10-NEXT:    s_ttracedata_imm 0x99
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.154:
; GFX10-NEXT:    s_ttracedata_imm 0x9a
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.155:
; GFX10-NEXT:    s_ttracedata_imm 0x9b
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.156:
; GFX10-NEXT:    s_ttracedata_imm 0x9c
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.157:
; GFX10-NEXT:    s_ttracedata_imm 0x9d
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.158:
; GFX10-NEXT:    s_ttracedata_imm 0x9e
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.159:
; GFX10-NEXT:    s_ttracedata_imm 0x9f
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.160:
; GFX10-NEXT:    s_ttracedata_imm 0xa0
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.161:
; GFX10-NEXT:    s_ttracedata_imm 0xa1
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.162:
; GFX10-NEXT:    s_ttracedata_imm 0xa2
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.163:
; GFX10-NEXT:    s_ttracedata_imm 0xa3
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.164:
; GFX10-NEXT:    s_ttracedata_imm 0xa4
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.165:
; GFX10-NEXT:    s_ttracedata_imm 0xa5
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.166:
; GFX10-NEXT:    s_ttracedata_imm 0xa6
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.167:
; GFX10-NEXT:    s_ttracedata_imm 0xa7
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.168:
; GFX10-NEXT:    s_ttracedata_imm 0xa8
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.169:
; GFX10-NEXT:    s_ttracedata_imm 0xa9
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.170:
; GFX10-NEXT:    s_ttracedata_imm 0xaa
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.171:
; GFX10-NEXT:    s_ttracedata_imm 0xab
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.172:
; GFX10-NEXT:    s_ttracedata_imm 0xac
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.173:
; GFX10-NEXT:    s_ttracedata_imm 0xad
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.174:
; GFX10-NEXT:    s_ttracedata_imm 0xae
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.175:
; GFX10-NEXT:    s_ttracedata_imm 0xaf
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.176:
; GFX10-NEXT:    s_ttracedata_imm 0xb0
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.177:
; GFX10-NEXT:    s_ttracedata_imm 0xb1
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.178:
; GFX10-NEXT:    s_ttracedata_imm 0xb2
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.179:
; GFX10-NEXT:    s_ttracedata_imm 0xb3
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.180:
; GFX10-NEXT:    s_ttracedata_imm 0xb4
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.181:
; GFX10-NEXT:    s_ttracedata_imm 0xb5
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.182:
; GFX10-NEXT:    s_ttracedata_imm 0xb6
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.183:
; GFX10-NEXT:    s_ttracedata_imm 0xb7
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.184:
; GFX10-NEXT:    s_ttracedata_imm 0xb8
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.185:
; GFX10-NEXT:    s_ttracedata_imm 0xb9
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.186:
; GFX10-NEXT:    s_ttracedata_imm 0xba
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.187:
; GFX10-NEXT:    s_ttracedata_imm 0xbb
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.188:
; GFX10-NEXT:    s_ttracedata_imm 0xbc
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.189:
; GFX10-NEXT:    s_ttracedata_imm 0xbd
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.190:
; GFX10-NEXT:    s_ttracedata_imm 0xbe
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.191:
; GFX10-NEXT:    s_ttracedata_imm 0xbf
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.192:
; GFX10-NEXT:    s_ttracedata_imm 0xc0
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.193:
; GFX10-NEXT:    s_ttracedata_imm 0xc1
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.194:
; GFX10-NEXT:    s_ttracedata_imm 0xc2
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.195:
; GFX10-NEXT:    s_ttracedata_imm 0xc3
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.196:
; GFX10-NEXT:    s_ttracedata_imm 0xc4
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.197:
; GFX10-NEXT:    s_ttracedata_imm 0xc5
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.198:
; GFX10-NEXT:    s_ttracedata_imm 0xc6
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.199:
; GFX10-NEXT:    s_ttracedata_imm 0xc7
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.200:
; GFX10-NEXT:    s_ttracedata_imm 0xc8
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.201:
; GFX10-NEXT:    s_ttracedata_imm 0xc9
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.202:
; GFX10-NEXT:    s_ttracedata_imm 0xca
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.203:
; GFX10-NEXT:    s_ttracedata_imm 0xcb
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.204:
; GFX10-NEXT:    s_ttracedata_imm 0xcc
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.205:
; GFX10-NEXT:    s_ttracedata_imm 0xcd
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.206:
; GFX10-NEXT:    s_ttracedata_imm 0xce
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.207:
; GFX10-NEXT:    s_ttracedata_imm 0xcf
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.208:
; GFX10-NEXT:    s_ttracedata_imm 0xd0
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.209:
; GFX10-NEXT:    s_ttracedata_imm 0xd1
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.210:
; GFX10-NEXT:    s_ttracedata_imm 0xd2
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.211:
; GFX10-NEXT:    s_ttracedata_imm 0xd3
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.212:
; GFX10-NEXT:    s_ttracedata_imm 0xd4
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.213:
; GFX10-NEXT:    s_ttracedata_imm 0xd5
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.214:
; GFX10-NEXT:    s_ttracedata_imm 0xd6
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.215:
; GFX10-NEXT:    s_ttracedata_imm 0xd7
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.216:
; GFX10-NEXT:    s_ttracedata_imm 0xd8
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.217:
; GFX10-NEXT:    s_ttracedata_imm 0xd9
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.218:
; GFX10-NEXT:    s_ttracedata_imm 0xda
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.219:
; GFX10-NEXT:    s_ttracedata_imm 0xdb
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.220:
; GFX10-NEXT:    s_ttracedata_imm 0xdc
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.221:
; GFX10-NEXT:    s_ttracedata_imm 0xdd
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.222:
; GFX10-NEXT:    s_ttracedata_imm 0xde
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.223:
; GFX10-NEXT:    s_ttracedata_imm 0xdf
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.224:
; GFX10-NEXT:    s_ttracedata_imm 0xe0
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.225:
; GFX10-NEXT:    s_ttracedata_imm 0xe1
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.226:
; GFX10-NEXT:    s_ttracedata_imm 0xe2
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.227:
; GFX10-NEXT:    s_ttracedata_imm 0xe3
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.228:
; GFX10-NEXT:    s_ttracedata_imm 0xe4
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.229:
; GFX10-NEXT:    s_ttracedata_imm 0xe5
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.230:
; GFX10-NEXT:    s_ttracedata_imm 0xe6
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.231:
; GFX10-NEXT:    s_ttracedata_imm 0xe7
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.232:
; GFX10-NEXT:    s_ttracedata_imm 0xe8
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.233:
; GFX10-NEXT:    s_ttracedata_imm 0xe9
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.234:
; GFX10-NEXT:    s_ttracedata_imm 0xea
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.235:
; GFX10-NEXT:    s_ttracedata_imm 0xeb
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.236:
; GFX10-NEXT:    s_ttracedata_imm 0xec
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.237:
; GFX10-NEXT:    s_ttracedata_imm 0xed
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.238:
; GFX10-NEXT:    s_ttracedata_imm 0xee
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.239:
; GFX10-NEXT:    s_ttracedata_imm 0xef
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.240:
; GFX10-NEXT:    s_ttracedata_imm 0xf0
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.241:
; GFX10-NEXT:    s_ttracedata_imm 0xf1
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.242:
; GFX10-NEXT:    s_ttracedata_imm 0xf2
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.243:
; GFX10-NEXT:    s_ttracedata_imm 0xf3
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.244:
; GFX10-NEXT:    s_ttracedata_imm 0xf4
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.245:
; GFX10-NEXT:    s_ttracedata_imm 0xf5
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.246:
; GFX10-NEXT:    s_ttracedata_imm 0xf6
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.247:
; GFX10-NEXT:    s_ttracedata_imm 0xf7
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.248:
; GFX10-NEXT:    s_ttracedata_imm 0xf8
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.249:
; GFX10-NEXT:    s_ttracedata_imm 0xf9
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.250:
; GFX10-NEXT:    s_ttracedata_imm 0xfa
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.251:
; GFX10-NEXT:    s_ttracedata_imm 0xfb
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.252:
; GFX10-NEXT:    s_ttracedata_imm 0xfc
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.253:
; GFX10-NEXT:    s_ttracedata_imm 0xfd
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.254:
; GFX10-NEXT:    s_ttracedata_imm 0xfe
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.255:
; GFX10-NEXT:    s_ttracedata_imm 0xff
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    s_movk_i32 m0, 0x100
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.256:
; GFX10-NEXT:    s_ttracedata
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    s_setpc_b64 s[30:31]
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !0, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !1, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !2, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !3, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !4, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !5, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !6, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !7, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !8, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !9, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !10, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !11, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !12, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !13, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !14, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !15, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !16, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !17, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !18, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !19, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !20, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !21, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !22, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !23, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !24, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !25, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !26, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !27, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !28, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !29, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !30, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !31, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !32, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !33, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !34, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !35, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !36, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !37, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !38, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !39, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !40, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !41, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !42, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !43, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !44, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !45, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !46, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !47, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !48, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !49, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !50, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !51, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !52, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !53, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !54, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !55, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !56, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !57, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !58, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !59, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !60, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !61, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !62, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !63, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !64, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !65, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !66, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !67, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !68, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !69, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !70, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !71, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !72, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !73, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !74, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !75, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !76, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !77, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !78, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !79, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !80, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !81, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !82, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !83, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !84, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !85, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !86, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !87, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !88, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !89, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !90, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !91, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !92, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !93, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !94, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !95, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !96, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !97, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !98, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !99, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !100, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !101, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !102, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !103, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !104, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !105, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !106, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !107, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !108, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !109, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !110, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !111, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !112, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !113, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !114, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !115, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !116, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !117, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !118, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !119, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !120, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !121, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !122, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !123, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !124, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !125, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !126, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !127, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !128, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !129, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !130, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !131, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !132, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !133, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !134, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !135, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !136, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !137, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !138, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !139, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !140, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !141, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !142, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !143, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !144, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !145, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !146, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !147, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !148, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !149, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !150, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !151, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !152, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !153, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !154, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !155, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !156, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !157, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !158, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !159, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !160, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !161, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !162, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !163, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !164, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !165, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !166, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !167, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !168, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !169, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !170, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !171, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !172, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !173, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !174, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !175, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !176, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !177, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !178, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !179, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !180, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !181, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !182, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !183, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !184, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !185, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !186, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !187, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !188, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !189, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !190, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !191, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !192, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !193, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !194, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !195, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !196, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !197, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !198, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !199, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !200, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !201, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !202, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !203, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !204, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !205, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !206, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !207, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !208, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !209, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !210, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !211, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !212, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !213, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !214, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !215, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !216, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !217, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !218, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !219, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !220, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !221, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !222, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !223, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !224, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !225, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !226, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !227, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !228, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !229, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !230, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !231, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !232, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !233, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !234, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !235, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !236, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !237, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !238, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !239, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !240, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !241, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !242, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !243, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !244, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !245, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !246, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !247, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !248, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !249, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !250, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !251, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !252, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !253, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !254, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !255, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !256, i32 poison)
  ret void
}

declare void @llvm.amdgcn.sqtt.event(metadata, i32, ...)

!0 = !{i32 0, !"event_0"}
!1 = !{i32 0, !"event_1"}
!2 = !{i32 0, !"event_2"}
!3 = !{i32 0, !"event_3"}
!4 = !{i32 0, !"event_4"}
!5 = !{i32 0, !"event_5"}
!6 = !{i32 0, !"event_6"}
!7 = !{i32 0, !"event_7"}
!8 = !{i32 0, !"event_8"}
!9 = !{i32 0, !"event_9"}
!10 = !{i32 0, !"event_10"}
!11 = !{i32 0, !"event_11"}
!12 = !{i32 0, !"event_12"}
!13 = !{i32 0, !"event_13"}
!14 = !{i32 0, !"event_14"}
!15 = !{i32 0, !"event_15"}
!16 = !{i32 0, !"event_16"}
!17 = !{i32 0, !"event_17"}
!18 = !{i32 0, !"event_18"}
!19 = !{i32 0, !"event_19"}
!20 = !{i32 0, !"event_20"}
!21 = !{i32 0, !"event_21"}
!22 = !{i32 0, !"event_22"}
!23 = !{i32 0, !"event_23"}
!24 = !{i32 0, !"event_24"}
!25 = !{i32 0, !"event_25"}
!26 = !{i32 0, !"event_26"}
!27 = !{i32 0, !"event_27"}
!28 = !{i32 0, !"event_28"}
!29 = !{i32 0, !"event_29"}
!30 = !{i32 0, !"event_30"}
!31 = !{i32 0, !"event_31"}
!32 = !{i32 0, !"event_32"}
!33 = !{i32 0, !"event_33"}
!34 = !{i32 0, !"event_34"}
!35 = !{i32 0, !"event_35"}
!36 = !{i32 0, !"event_36"}
!37 = !{i32 0, !"event_37"}
!38 = !{i32 0, !"event_38"}
!39 = !{i32 0, !"event_39"}
!40 = !{i32 0, !"event_40"}
!41 = !{i32 0, !"event_41"}
!42 = !{i32 0, !"event_42"}
!43 = !{i32 0, !"event_43"}
!44 = !{i32 0, !"event_44"}
!45 = !{i32 0, !"event_45"}
!46 = !{i32 0, !"event_46"}
!47 = !{i32 0, !"event_47"}
!48 = !{i32 0, !"event_48"}
!49 = !{i32 0, !"event_49"}
!50 = !{i32 0, !"event_50"}
!51 = !{i32 0, !"event_51"}
!52 = !{i32 0, !"event_52"}
!53 = !{i32 0, !"event_53"}
!54 = !{i32 0, !"event_54"}
!55 = !{i32 0, !"event_55"}
!56 = !{i32 0, !"event_56"}
!57 = !{i32 0, !"event_57"}
!58 = !{i32 0, !"event_58"}
!59 = !{i32 0, !"event_59"}
!60 = !{i32 0, !"event_60"}
!61 = !{i32 0, !"event_61"}
!62 = !{i32 0, !"event_62"}
!63 = !{i32 0, !"event_63"}
!64 = !{i32 0, !"event_64"}
!65 = !{i32 0, !"event_65"}
!66 = !{i32 0, !"event_66"}
!67 = !{i32 0, !"event_67"}
!68 = !{i32 0, !"event_68"}
!69 = !{i32 0, !"event_69"}
!70 = !{i32 0, !"event_70"}
!71 = !{i32 0, !"event_71"}
!72 = !{i32 0, !"event_72"}
!73 = !{i32 0, !"event_73"}
!74 = !{i32 0, !"event_74"}
!75 = !{i32 0, !"event_75"}
!76 = !{i32 0, !"event_76"}
!77 = !{i32 0, !"event_77"}
!78 = !{i32 0, !"event_78"}
!79 = !{i32 0, !"event_79"}
!80 = !{i32 0, !"event_80"}
!81 = !{i32 0, !"event_81"}
!82 = !{i32 0, !"event_82"}
!83 = !{i32 0, !"event_83"}
!84 = !{i32 0, !"event_84"}
!85 = !{i32 0, !"event_85"}
!86 = !{i32 0, !"event_86"}
!87 = !{i32 0, !"event_87"}
!88 = !{i32 0, !"event_88"}
!89 = !{i32 0, !"event_89"}
!90 = !{i32 0, !"event_90"}
!91 = !{i32 0, !"event_91"}
!92 = !{i32 0, !"event_92"}
!93 = !{i32 0, !"event_93"}
!94 = !{i32 0, !"event_94"}
!95 = !{i32 0, !"event_95"}
!96 = !{i32 0, !"event_96"}
!97 = !{i32 0, !"event_97"}
!98 = !{i32 0, !"event_98"}
!99 = !{i32 0, !"event_99"}
!100 = !{i32 0, !"event_100"}
!101 = !{i32 0, !"event_101"}
!102 = !{i32 0, !"event_102"}
!103 = !{i32 0, !"event_103"}
!104 = !{i32 0, !"event_104"}
!105 = !{i32 0, !"event_105"}
!106 = !{i32 0, !"event_106"}
!107 = !{i32 0, !"event_107"}
!108 = !{i32 0, !"event_108"}
!109 = !{i32 0, !"event_109"}
!110 = !{i32 0, !"event_110"}
!111 = !{i32 0, !"event_111"}
!112 = !{i32 0, !"event_112"}
!113 = !{i32 0, !"event_113"}
!114 = !{i32 0, !"event_114"}
!115 = !{i32 0, !"event_115"}
!116 = !{i32 0, !"event_116"}
!117 = !{i32 0, !"event_117"}
!118 = !{i32 0, !"event_118"}
!119 = !{i32 0, !"event_119"}
!120 = !{i32 0, !"event_120"}
!121 = !{i32 0, !"event_121"}
!122 = !{i32 0, !"event_122"}
!123 = !{i32 0, !"event_123"}
!124 = !{i32 0, !"event_124"}
!125 = !{i32 0, !"event_125"}
!126 = !{i32 0, !"event_126"}
!127 = !{i32 0, !"event_127"}
!128 = !{i32 0, !"event_128"}
!129 = !{i32 0, !"event_129"}
!130 = !{i32 0, !"event_130"}
!131 = !{i32 0, !"event_131"}
!132 = !{i32 0, !"event_132"}
!133 = !{i32 0, !"event_133"}
!134 = !{i32 0, !"event_134"}
!135 = !{i32 0, !"event_135"}
!136 = !{i32 0, !"event_136"}
!137 = !{i32 0, !"event_137"}
!138 = !{i32 0, !"event_138"}
!139 = !{i32 0, !"event_139"}
!140 = !{i32 0, !"event_140"}
!141 = !{i32 0, !"event_141"}
!142 = !{i32 0, !"event_142"}
!143 = !{i32 0, !"event_143"}
!144 = !{i32 0, !"event_144"}
!145 = !{i32 0, !"event_145"}
!146 = !{i32 0, !"event_146"}
!147 = !{i32 0, !"event_147"}
!148 = !{i32 0, !"event_148"}
!149 = !{i32 0, !"event_149"}
!150 = !{i32 0, !"event_150"}
!151 = !{i32 0, !"event_151"}
!152 = !{i32 0, !"event_152"}
!153 = !{i32 0, !"event_153"}
!154 = !{i32 0, !"event_154"}
!155 = !{i32 0, !"event_155"}
!156 = !{i32 0, !"event_156"}
!157 = !{i32 0, !"event_157"}
!158 = !{i32 0, !"event_158"}
!159 = !{i32 0, !"event_159"}
!160 = !{i32 0, !"event_160"}
!161 = !{i32 0, !"event_161"}
!162 = !{i32 0, !"event_162"}
!163 = !{i32 0, !"event_163"}
!164 = !{i32 0, !"event_164"}
!165 = !{i32 0, !"event_165"}
!166 = !{i32 0, !"event_166"}
!167 = !{i32 0, !"event_167"}
!168 = !{i32 0, !"event_168"}
!169 = !{i32 0, !"event_169"}
!170 = !{i32 0, !"event_170"}
!171 = !{i32 0, !"event_171"}
!172 = !{i32 0, !"event_172"}
!173 = !{i32 0, !"event_173"}
!174 = !{i32 0, !"event_174"}
!175 = !{i32 0, !"event_175"}
!176 = !{i32 0, !"event_176"}
!177 = !{i32 0, !"event_177"}
!178 = !{i32 0, !"event_178"}
!179 = !{i32 0, !"event_179"}
!180 = !{i32 0, !"event_180"}
!181 = !{i32 0, !"event_181"}
!182 = !{i32 0, !"event_182"}
!183 = !{i32 0, !"event_183"}
!184 = !{i32 0, !"event_184"}
!185 = !{i32 0, !"event_185"}
!186 = !{i32 0, !"event_186"}
!187 = !{i32 0, !"event_187"}
!188 = !{i32 0, !"event_188"}
!189 = !{i32 0, !"event_189"}
!190 = !{i32 0, !"event_190"}
!191 = !{i32 0, !"event_191"}
!192 = !{i32 0, !"event_192"}
!193 = !{i32 0, !"event_193"}
!194 = !{i32 0, !"event_194"}
!195 = !{i32 0, !"event_195"}
!196 = !{i32 0, !"event_196"}
!197 = !{i32 0, !"event_197"}
!198 = !{i32 0, !"event_198"}
!199 = !{i32 0, !"event_199"}
!200 = !{i32 0, !"event_200"}
!201 = !{i32 0, !"event_201"}
!202 = !{i32 0, !"event_202"}
!203 = !{i32 0, !"event_203"}
!204 = !{i32 0, !"event_204"}
!205 = !{i32 0, !"event_205"}
!206 = !{i32 0, !"event_206"}
!207 = !{i32 0, !"event_207"}
!208 = !{i32 0, !"event_208"}
!209 = !{i32 0, !"event_209"}
!210 = !{i32 0, !"event_210"}
!211 = !{i32 0, !"event_211"}
!212 = !{i32 0, !"event_212"}
!213 = !{i32 0, !"event_213"}
!214 = !{i32 0, !"event_214"}
!215 = !{i32 0, !"event_215"}
!216 = !{i32 0, !"event_216"}
!217 = !{i32 0, !"event_217"}
!218 = !{i32 0, !"event_218"}
!219 = !{i32 0, !"event_219"}
!220 = !{i32 0, !"event_220"}
!221 = !{i32 0, !"event_221"}
!222 = !{i32 0, !"event_222"}
!223 = !{i32 0, !"event_223"}
!224 = !{i32 0, !"event_224"}
!225 = !{i32 0, !"event_225"}
!226 = !{i32 0, !"event_226"}
!227 = !{i32 0, !"event_227"}
!228 = !{i32 0, !"event_228"}
!229 = !{i32 0, !"event_229"}
!230 = !{i32 0, !"event_230"}
!231 = !{i32 0, !"event_231"}
!232 = !{i32 0, !"event_232"}
!233 = !{i32 0, !"event_233"}
!234 = !{i32 0, !"event_234"}
!235 = !{i32 0, !"event_235"}
!236 = !{i32 0, !"event_236"}
!237 = !{i32 0, !"event_237"}
!238 = !{i32 0, !"event_238"}
!239 = !{i32 0, !"event_239"}
!240 = !{i32 0, !"event_240"}
!241 = !{i32 0, !"event_241"}
!242 = !{i32 0, !"event_242"}
!243 = !{i32 0, !"event_243"}
!244 = !{i32 0, !"event_244"}
!245 = !{i32 0, !"event_245"}
!246 = !{i32 0, !"event_246"}
!247 = !{i32 0, !"event_247"}
!248 = !{i32 0, !"event_248"}
!249 = !{i32 0, !"event_249"}
!250 = !{i32 0, !"event_250"}
!251 = !{i32 0, !"event_251"}
!252 = !{i32 0, !"event_252"}
!253 = !{i32 0, !"event_253"}
!254 = !{i32 0, !"event_254"}
!255 = !{i32 0, !"event_255"}
!256 = !{i32 0, !"event_256"}
