; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: not --crash llc -global-isel=0 -mtriple=amdgpu9.00-amd-amdhsa -mcpu=gfx900 < %s 2>&1 | FileCheck --check-prefix=SDAG %s
; RUN: not llc -global-isel=1 -mtriple=amdgpu9.00-amd-amdhsa -mcpu=gfx900 < %s 2>&1 | FileCheck --check-prefix=GISEL %s

; SDAG: LLVM ERROR: Cannot select: intrinsic %llvm.amdgcn.sqtt.event
; GISEL: LLVM ERROR: No AMDGPU RegBankLegalize rules defined for opcode: G_INTRINSIC_W_SIDE_EFFECTS intrinsic(@llvm.amdgcn.sqtt.event)

define void @sqtt_events() {
  call void @llvm.amdgcn.sqtt.event(metadata !0)
  call void @llvm.amdgcn.sqtt.event(metadata !1)
  ret void
}

declare void @llvm.amdgcn.sqtt.event(metadata)

!0 = !{i32 0, ptr @sqtt_events}
!1 = !{i32 1, ptr @sqtt_events}
