; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -global-isel=0 -mtriple=amdgpu9.00-amd-amdhsa -mcpu=gfx900 < %s | FileCheck --check-prefix=GFX9 %s
; RUN: llc -global-isel=1 -mtriple=amdgpu9.00-amd-amdhsa -mcpu=gfx900 < %s | FileCheck --check-prefix=GFX9 %s
; RUN: llc -global-isel=0 -mtriple=amdgpu10.10-amd-amdhsa -mcpu=gfx1010 < %s | FileCheck --check-prefix=GFX10 %s
; RUN: llc -global-isel=1 -mtriple=amdgpu10.10-amd-amdhsa -mcpu=gfx1010 < %s | FileCheck --check-prefix=GFX10 %s

define void @sqtt_events() {
; GFX9-LABEL: sqtt_events:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_mov_b32 m0, 0
; GFX9-NEXT:    ; sched_barrier mask(0x00000000)
; GFX9-NEXT:    s_nop 0
; GFX9-NEXT:  .Lsqtt_event.0:
; GFX9-NEXT:    s_ttracedata
; GFX9-NEXT:    ; sched_barrier mask(0x00000000)
; GFX9-NEXT:    s_mov_b32 m0, 1
; GFX9-NEXT:    ; sched_barrier mask(0x00000000)
; GFX9-NEXT:    s_nop 0
; GFX9-NEXT:  .Lsqtt_event.1:
; GFX9-NEXT:    s_ttracedata
; GFX9-NEXT:    ; sched_barrier mask(0x00000000)
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX10-LABEL: sqtt_events:
; GFX10:       ; %bb.0:
; GFX10-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX10-NEXT:    s_mov_b32 m0, 0
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.0:
; GFX10-NEXT:    s_ttracedata
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    s_mov_b32 m0, 1
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:  .Lsqtt_event.1:
; GFX10-NEXT:    s_ttracedata
; GFX10-NEXT:    ; sched_barrier mask(0x00000000)
; GFX10-NEXT:    s_setpc_b64 s[30:31]
  call void @llvm.amdgcn.sqtt.event(metadata !0, i32 poison)
  call void @llvm.amdgcn.sqtt.event(metadata !1, i32 poison)
  ret void
}

declare void @llvm.amdgcn.sqtt.event(metadata, i32)

!0 = !{i32 0, !"sqtt_events"}
!1 = !{i32 1, !"sqtt_events"}
