; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --version 6
; RUN: opt -S -mtriple=amdgpu-amd-amdhsa -passes=amdgpu-sqtt-lower -amdgpu-sqtt-combine-events=false %s | FileCheck %s

define void @foo() {
; CHECK-LABEL: define void @foo() {
; CHECK-NEXT:    call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata [[META0:![0-9]+]], i32 0)
; CHECK-NEXT:    call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata [[META1:![0-9]+]], i32 1)
; CHECK-NEXT:    ret void
;
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !0, i32 poison)
  call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata !1, i32 poison)
  ret void
}

declare void @llvm.amdgcn.sqtt.event(metadata, i32, ...)

!0 = !{i32 0, !"foo"}
!1 = !{i32 1, !"foo"}
;.
; CHECK: attributes #[[ATTR0:[0-9]+]] = { nocallback nofree nosync nounwind willreturn }
;.
; CHECK: [[META0]] = !{i32 0, !"foo"}
; CHECK: [[META1]] = !{i32 1, !"foo"}
;.
