; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --version 5
; RUN: opt -mtriple=amdgpu-amd-amdhsa -passes=ee-instrument -S < %s | FileCheck --check-prefix=PRE %s
; RUN: opt -mtriple=amdgpu-amd-amdhsa -passes='ee-instrument<post-inline>' -S < %s | FileCheck --check-prefix=POST %s

define void @instrumented() #0 {
; PRE-LABEL: define void @instrumented() {
; PRE-NEXT:  [[ENTRY:.*:]]
; PRE-NEXT:    call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata [[META0:![0-9]+]], i32 poison)
; PRE-NEXT:    call void @body()
; PRE-NEXT:    call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata [[META1:![0-9]+]], i32 poison)
; PRE-NEXT:    ret void
;
; POST-LABEL: define void @instrumented(
; POST-SAME: ) #[[ATTR0:[0-9]+]] {
; POST-NEXT:  [[ENTRY:.*:]]
; POST-NEXT:    call void @body()
; POST-NEXT:    ret void
;
entry:
  call void @body()
  ret void
}

define void @instrumented_inlined() #1 {
; PRE-LABEL: define void @instrumented_inlined(
; PRE-SAME: ) #[[ATTR0:[0-9]+]] {
; PRE-NEXT:  [[ENTRY:.*:]]
; PRE-NEXT:    call void @body()
; PRE-NEXT:    ret void
;
; POST-LABEL: define void @instrumented_inlined() {
; POST-NEXT:  [[ENTRY:.*:]]
; POST-NEXT:    call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata [[META0:![0-9]+]], i32 poison)
; POST-NEXT:    call void @body()
; POST-NEXT:    call void (metadata, i32, ...) @llvm.amdgcn.sqtt.event(metadata [[META1:![0-9]+]], i32 poison)
; POST-NEXT:    ret void
;
entry:
  call void @body()
  ret void
}

declare void @body()

attributes #0 = { "instrument-function-entry"="sqtt_func_enter" "instrument-function-exit"="sqtt_func_exit" }
attributes #1 = { "instrument-function-entry-inlined"="sqtt_func_enter" "instrument-function-exit-inlined"="sqtt_func_exit" }
;.
; PRE: attributes #[[ATTR0]] = { "instrument-function-entry-inlined"="sqtt_func_enter" "instrument-function-exit-inlined"="sqtt_func_exit" }
; PRE: attributes #[[ATTR1:[0-9]+]] = { nocallback nofree nosync nounwind willreturn }
;.
; POST: attributes #[[ATTR0]] = { "instrument-function-entry"="sqtt_func_enter" "instrument-function-exit"="sqtt_func_exit" }
; POST: attributes #[[ATTR1:[0-9]+]] = { nocallback nofree nosync nounwind willreturn }
;.
; PRE: [[META0]] = !{i32 0, !"instrumented"}
; PRE: [[META1]] = !{i32 1, !"instrumented"}
;.
; POST: [[META0]] = !{i32 0, !"instrumented_inlined"}
; POST: [[META1]] = !{i32 1, !"instrumented_inlined"}
;.
