; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -mtriple=amdgcn-- -passes='loop-unroll,simplifycfg,sroa' -S < %s | FileCheck --check-prefixes=CHECK,AMDGCN %s
; RUN: opt -mtriple=r600-- -passes='loop-unroll,simplifycfg,sroa' -S < %s | FileCheck --check-prefixes=CHECK,R600 %s

; This test contains a simple loop that initializes an array declared in
; private memory.  We want to make sure these kinds of loops are always
; unrolled, because private memory is slow.

define amdgpu_kernel void @private_memory(ptr addrspace(1) %out) {
; CHECK-LABEL: @private_memory(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    store i32 5, ptr addrspace(1) [[OUT:%.*]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %0 = alloca [32 x i32], addrspace(5)
  br label %loop.header

loop.header:
  %counter = phi i32 [0, %entry], [%inc, %loop.inc]
  br label %loop.body

loop.body:
  %ptr = getelementptr [32 x i32], ptr addrspace(5) %0, i32 0, i32 %counter
  store i32 %counter, ptr addrspace(5) %ptr
  br label %loop.inc

loop.inc:
  %inc = add i32 %counter, 1
  %1 = icmp sge i32 %counter, 32
  br i1 %1, label  %exit, label %loop.header

exit:
  %2 = getelementptr [32 x i32], ptr addrspace(5) %0, i32 0, i32 5
  %3 = load i32, ptr addrspace(5) %2
  store i32 %3, ptr addrspace(1) %out
  ret void
}

; Check that loop is unrolled for local memory references

define amdgpu_kernel void @local_memory(ptr addrspace(1) %out, ptr addrspace(3) %lds) {
; CHECK-LABEL: @local_memory(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[VAL:%.*]] = load i32, ptr addrspace(3) [[LDS:%.*]], align 4
; CHECK-NEXT:    store i32 [[VAL]], ptr addrspace(1) [[OUT:%.*]], align 4
; CHECK-NEXT:    [[PTR_LDS_1:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 1
; CHECK-NEXT:    [[VAL_1:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_1]], align 4
; CHECK-NEXT:    [[PTR_OUT_1:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 1
; CHECK-NEXT:    store i32 [[VAL_1]], ptr addrspace(1) [[PTR_OUT_1]], align 4
; CHECK-NEXT:    [[PTR_LDS_2:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 2
; CHECK-NEXT:    [[VAL_2:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_2]], align 4
; CHECK-NEXT:    [[PTR_OUT_2:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 2
; CHECK-NEXT:    store i32 [[VAL_2]], ptr addrspace(1) [[PTR_OUT_2]], align 4
; CHECK-NEXT:    [[PTR_LDS_3:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 3
; CHECK-NEXT:    [[VAL_3:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_3]], align 4
; CHECK-NEXT:    [[PTR_OUT_3:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 3
; CHECK-NEXT:    store i32 [[VAL_3]], ptr addrspace(1) [[PTR_OUT_3]], align 4
; CHECK-NEXT:    [[PTR_LDS_4:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 4
; CHECK-NEXT:    [[VAL_4:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_4]], align 4
; CHECK-NEXT:    [[PTR_OUT_4:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 4
; CHECK-NEXT:    store i32 [[VAL_4]], ptr addrspace(1) [[PTR_OUT_4]], align 4
; CHECK-NEXT:    [[PTR_LDS_5:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 5
; CHECK-NEXT:    [[VAL_5:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_5]], align 4
; CHECK-NEXT:    [[PTR_OUT_5:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 5
; CHECK-NEXT:    store i32 [[VAL_5]], ptr addrspace(1) [[PTR_OUT_5]], align 4
; CHECK-NEXT:    [[PTR_LDS_6:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 6
; CHECK-NEXT:    [[VAL_6:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_6]], align 4
; CHECK-NEXT:    [[PTR_OUT_6:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 6
; CHECK-NEXT:    store i32 [[VAL_6]], ptr addrspace(1) [[PTR_OUT_6]], align 4
; CHECK-NEXT:    [[PTR_LDS_7:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 7
; CHECK-NEXT:    [[VAL_7:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_7]], align 4
; CHECK-NEXT:    [[PTR_OUT_7:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 7
; CHECK-NEXT:    store i32 [[VAL_7]], ptr addrspace(1) [[PTR_OUT_7]], align 4
; CHECK-NEXT:    [[PTR_LDS_8:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 8
; CHECK-NEXT:    [[VAL_8:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_8]], align 4
; CHECK-NEXT:    [[PTR_OUT_8:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 8
; CHECK-NEXT:    store i32 [[VAL_8]], ptr addrspace(1) [[PTR_OUT_8]], align 4
; CHECK-NEXT:    [[PTR_LDS_9:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 9
; CHECK-NEXT:    [[VAL_9:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_9]], align 4
; CHECK-NEXT:    [[PTR_OUT_9:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 9
; CHECK-NEXT:    store i32 [[VAL_9]], ptr addrspace(1) [[PTR_OUT_9]], align 4
; CHECK-NEXT:    [[PTR_LDS_10:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 10
; CHECK-NEXT:    [[VAL_10:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_10]], align 4
; CHECK-NEXT:    [[PTR_OUT_10:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 10
; CHECK-NEXT:    store i32 [[VAL_10]], ptr addrspace(1) [[PTR_OUT_10]], align 4
; CHECK-NEXT:    [[PTR_LDS_11:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 11
; CHECK-NEXT:    [[VAL_11:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_11]], align 4
; CHECK-NEXT:    [[PTR_OUT_11:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 11
; CHECK-NEXT:    store i32 [[VAL_11]], ptr addrspace(1) [[PTR_OUT_11]], align 4
; CHECK-NEXT:    [[PTR_LDS_12:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 12
; CHECK-NEXT:    [[VAL_12:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_12]], align 4
; CHECK-NEXT:    [[PTR_OUT_12:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 12
; CHECK-NEXT:    store i32 [[VAL_12]], ptr addrspace(1) [[PTR_OUT_12]], align 4
; CHECK-NEXT:    [[PTR_LDS_13:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 13
; CHECK-NEXT:    [[VAL_13:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_13]], align 4
; CHECK-NEXT:    [[PTR_OUT_13:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 13
; CHECK-NEXT:    store i32 [[VAL_13]], ptr addrspace(1) [[PTR_OUT_13]], align 4
; CHECK-NEXT:    [[PTR_LDS_14:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 14
; CHECK-NEXT:    [[VAL_14:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_14]], align 4
; CHECK-NEXT:    [[PTR_OUT_14:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 14
; CHECK-NEXT:    store i32 [[VAL_14]], ptr addrspace(1) [[PTR_OUT_14]], align 4
; CHECK-NEXT:    [[PTR_LDS_15:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 15
; CHECK-NEXT:    [[VAL_15:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_15]], align 4
; CHECK-NEXT:    [[PTR_OUT_15:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 15
; CHECK-NEXT:    store i32 [[VAL_15]], ptr addrspace(1) [[PTR_OUT_15]], align 4
; CHECK-NEXT:    [[PTR_LDS_16:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 16
; CHECK-NEXT:    [[VAL_16:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_16]], align 4
; CHECK-NEXT:    [[PTR_OUT_16:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 16
; CHECK-NEXT:    store i32 [[VAL_16]], ptr addrspace(1) [[PTR_OUT_16]], align 4
; CHECK-NEXT:    [[PTR_LDS_17:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 17
; CHECK-NEXT:    [[VAL_17:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_17]], align 4
; CHECK-NEXT:    [[PTR_OUT_17:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 17
; CHECK-NEXT:    store i32 [[VAL_17]], ptr addrspace(1) [[PTR_OUT_17]], align 4
; CHECK-NEXT:    [[PTR_LDS_18:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 18
; CHECK-NEXT:    [[VAL_18:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_18]], align 4
; CHECK-NEXT:    [[PTR_OUT_18:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 18
; CHECK-NEXT:    store i32 [[VAL_18]], ptr addrspace(1) [[PTR_OUT_18]], align 4
; CHECK-NEXT:    [[PTR_LDS_19:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 19
; CHECK-NEXT:    [[VAL_19:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_19]], align 4
; CHECK-NEXT:    [[PTR_OUT_19:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 19
; CHECK-NEXT:    store i32 [[VAL_19]], ptr addrspace(1) [[PTR_OUT_19]], align 4
; CHECK-NEXT:    [[PTR_LDS_20:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 20
; CHECK-NEXT:    [[VAL_20:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_20]], align 4
; CHECK-NEXT:    [[PTR_OUT_20:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 20
; CHECK-NEXT:    store i32 [[VAL_20]], ptr addrspace(1) [[PTR_OUT_20]], align 4
; CHECK-NEXT:    [[PTR_LDS_21:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 21
; CHECK-NEXT:    [[VAL_21:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_21]], align 4
; CHECK-NEXT:    [[PTR_OUT_21:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 21
; CHECK-NEXT:    store i32 [[VAL_21]], ptr addrspace(1) [[PTR_OUT_21]], align 4
; CHECK-NEXT:    [[PTR_LDS_22:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 22
; CHECK-NEXT:    [[VAL_22:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_22]], align 4
; CHECK-NEXT:    [[PTR_OUT_22:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 22
; CHECK-NEXT:    store i32 [[VAL_22]], ptr addrspace(1) [[PTR_OUT_22]], align 4
; CHECK-NEXT:    [[PTR_LDS_23:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 23
; CHECK-NEXT:    [[VAL_23:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_23]], align 4
; CHECK-NEXT:    [[PTR_OUT_23:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 23
; CHECK-NEXT:    store i32 [[VAL_23]], ptr addrspace(1) [[PTR_OUT_23]], align 4
; CHECK-NEXT:    [[PTR_LDS_24:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 24
; CHECK-NEXT:    [[VAL_24:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_24]], align 4
; CHECK-NEXT:    [[PTR_OUT_24:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 24
; CHECK-NEXT:    store i32 [[VAL_24]], ptr addrspace(1) [[PTR_OUT_24]], align 4
; CHECK-NEXT:    [[PTR_LDS_25:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 25
; CHECK-NEXT:    [[VAL_25:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_25]], align 4
; CHECK-NEXT:    [[PTR_OUT_25:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 25
; CHECK-NEXT:    store i32 [[VAL_25]], ptr addrspace(1) [[PTR_OUT_25]], align 4
; CHECK-NEXT:    [[PTR_LDS_26:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 26
; CHECK-NEXT:    [[VAL_26:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_26]], align 4
; CHECK-NEXT:    [[PTR_OUT_26:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 26
; CHECK-NEXT:    store i32 [[VAL_26]], ptr addrspace(1) [[PTR_OUT_26]], align 4
; CHECK-NEXT:    [[PTR_LDS_27:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 27
; CHECK-NEXT:    [[VAL_27:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_27]], align 4
; CHECK-NEXT:    [[PTR_OUT_27:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 27
; CHECK-NEXT:    store i32 [[VAL_27]], ptr addrspace(1) [[PTR_OUT_27]], align 4
; CHECK-NEXT:    [[PTR_LDS_28:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 28
; CHECK-NEXT:    [[VAL_28:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_28]], align 4
; CHECK-NEXT:    [[PTR_OUT_28:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 28
; CHECK-NEXT:    store i32 [[VAL_28]], ptr addrspace(1) [[PTR_OUT_28]], align 4
; CHECK-NEXT:    [[PTR_LDS_29:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 29
; CHECK-NEXT:    [[VAL_29:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_29]], align 4
; CHECK-NEXT:    [[PTR_OUT_29:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 29
; CHECK-NEXT:    store i32 [[VAL_29]], ptr addrspace(1) [[PTR_OUT_29]], align 4
; CHECK-NEXT:    [[PTR_LDS_30:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 30
; CHECK-NEXT:    [[VAL_30:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_30]], align 4
; CHECK-NEXT:    [[PTR_OUT_30:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 30
; CHECK-NEXT:    store i32 [[VAL_30]], ptr addrspace(1) [[PTR_OUT_30]], align 4
; CHECK-NEXT:    [[PTR_LDS_31:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 31
; CHECK-NEXT:    [[VAL_31:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_31]], align 4
; CHECK-NEXT:    [[PTR_OUT_31:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 31
; CHECK-NEXT:    store i32 [[VAL_31]], ptr addrspace(1) [[PTR_OUT_31]], align 4
; CHECK-NEXT:    [[PTR_LDS_32:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 32
; CHECK-NEXT:    [[VAL_32:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_32]], align 4
; CHECK-NEXT:    [[PTR_OUT_32:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 32
; CHECK-NEXT:    store i32 [[VAL_32]], ptr addrspace(1) [[PTR_OUT_32]], align 4
; CHECK-NEXT:    [[PTR_LDS_33:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 33
; CHECK-NEXT:    [[VAL_33:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_33]], align 4
; CHECK-NEXT:    [[PTR_OUT_33:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 33
; CHECK-NEXT:    store i32 [[VAL_33]], ptr addrspace(1) [[PTR_OUT_33]], align 4
; CHECK-NEXT:    [[PTR_LDS_34:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 34
; CHECK-NEXT:    [[VAL_34:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_34]], align 4
; CHECK-NEXT:    [[PTR_OUT_34:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 34
; CHECK-NEXT:    store i32 [[VAL_34]], ptr addrspace(1) [[PTR_OUT_34]], align 4
; CHECK-NEXT:    [[PTR_LDS_35:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 35
; CHECK-NEXT:    [[VAL_35:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_35]], align 4
; CHECK-NEXT:    [[PTR_OUT_35:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 35
; CHECK-NEXT:    store i32 [[VAL_35]], ptr addrspace(1) [[PTR_OUT_35]], align 4
; CHECK-NEXT:    [[PTR_LDS_36:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 36
; CHECK-NEXT:    [[VAL_36:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_36]], align 4
; CHECK-NEXT:    [[PTR_OUT_36:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 36
; CHECK-NEXT:    store i32 [[VAL_36]], ptr addrspace(1) [[PTR_OUT_36]], align 4
; CHECK-NEXT:    [[PTR_LDS_37:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 37
; CHECK-NEXT:    [[VAL_37:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_37]], align 4
; CHECK-NEXT:    [[PTR_OUT_37:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 37
; CHECK-NEXT:    store i32 [[VAL_37]], ptr addrspace(1) [[PTR_OUT_37]], align 4
; CHECK-NEXT:    [[PTR_LDS_38:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 38
; CHECK-NEXT:    [[VAL_38:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_38]], align 4
; CHECK-NEXT:    [[PTR_OUT_38:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 38
; CHECK-NEXT:    store i32 [[VAL_38]], ptr addrspace(1) [[PTR_OUT_38]], align 4
; CHECK-NEXT:    [[PTR_LDS_39:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 39
; CHECK-NEXT:    [[VAL_39:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_39]], align 4
; CHECK-NEXT:    [[PTR_OUT_39:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 39
; CHECK-NEXT:    store i32 [[VAL_39]], ptr addrspace(1) [[PTR_OUT_39]], align 4
; CHECK-NEXT:    [[PTR_LDS_40:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 40
; CHECK-NEXT:    [[VAL_40:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_40]], align 4
; CHECK-NEXT:    [[PTR_OUT_40:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 40
; CHECK-NEXT:    store i32 [[VAL_40]], ptr addrspace(1) [[PTR_OUT_40]], align 4
; CHECK-NEXT:    [[PTR_LDS_41:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 41
; CHECK-NEXT:    [[VAL_41:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_41]], align 4
; CHECK-NEXT:    [[PTR_OUT_41:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 41
; CHECK-NEXT:    store i32 [[VAL_41]], ptr addrspace(1) [[PTR_OUT_41]], align 4
; CHECK-NEXT:    [[PTR_LDS_42:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 42
; CHECK-NEXT:    [[VAL_42:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_42]], align 4
; CHECK-NEXT:    [[PTR_OUT_42:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 42
; CHECK-NEXT:    store i32 [[VAL_42]], ptr addrspace(1) [[PTR_OUT_42]], align 4
; CHECK-NEXT:    [[PTR_LDS_43:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 43
; CHECK-NEXT:    [[VAL_43:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_43]], align 4
; CHECK-NEXT:    [[PTR_OUT_43:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 43
; CHECK-NEXT:    store i32 [[VAL_43]], ptr addrspace(1) [[PTR_OUT_43]], align 4
; CHECK-NEXT:    [[PTR_LDS_44:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 44
; CHECK-NEXT:    [[VAL_44:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_44]], align 4
; CHECK-NEXT:    [[PTR_OUT_44:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 44
; CHECK-NEXT:    store i32 [[VAL_44]], ptr addrspace(1) [[PTR_OUT_44]], align 4
; CHECK-NEXT:    [[PTR_LDS_45:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 45
; CHECK-NEXT:    [[VAL_45:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_45]], align 4
; CHECK-NEXT:    [[PTR_OUT_45:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 45
; CHECK-NEXT:    store i32 [[VAL_45]], ptr addrspace(1) [[PTR_OUT_45]], align 4
; CHECK-NEXT:    [[PTR_LDS_46:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 46
; CHECK-NEXT:    [[VAL_46:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_46]], align 4
; CHECK-NEXT:    [[PTR_OUT_46:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 46
; CHECK-NEXT:    store i32 [[VAL_46]], ptr addrspace(1) [[PTR_OUT_46]], align 4
; CHECK-NEXT:    [[PTR_LDS_47:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 47
; CHECK-NEXT:    [[VAL_47:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_47]], align 4
; CHECK-NEXT:    [[PTR_OUT_47:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 47
; CHECK-NEXT:    store i32 [[VAL_47]], ptr addrspace(1) [[PTR_OUT_47]], align 4
; CHECK-NEXT:    [[PTR_LDS_48:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 48
; CHECK-NEXT:    [[VAL_48:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_48]], align 4
; CHECK-NEXT:    [[PTR_OUT_48:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 48
; CHECK-NEXT:    store i32 [[VAL_48]], ptr addrspace(1) [[PTR_OUT_48]], align 4
; CHECK-NEXT:    [[PTR_LDS_49:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 49
; CHECK-NEXT:    [[VAL_49:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_49]], align 4
; CHECK-NEXT:    [[PTR_OUT_49:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 49
; CHECK-NEXT:    store i32 [[VAL_49]], ptr addrspace(1) [[PTR_OUT_49]], align 4
; CHECK-NEXT:    [[PTR_LDS_50:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 50
; CHECK-NEXT:    [[VAL_50:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_50]], align 4
; CHECK-NEXT:    [[PTR_OUT_50:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 50
; CHECK-NEXT:    store i32 [[VAL_50]], ptr addrspace(1) [[PTR_OUT_50]], align 4
; CHECK-NEXT:    [[PTR_LDS_51:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 51
; CHECK-NEXT:    [[VAL_51:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_51]], align 4
; CHECK-NEXT:    [[PTR_OUT_51:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 51
; CHECK-NEXT:    store i32 [[VAL_51]], ptr addrspace(1) [[PTR_OUT_51]], align 4
; CHECK-NEXT:    [[PTR_LDS_52:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 52
; CHECK-NEXT:    [[VAL_52:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_52]], align 4
; CHECK-NEXT:    [[PTR_OUT_52:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 52
; CHECK-NEXT:    store i32 [[VAL_52]], ptr addrspace(1) [[PTR_OUT_52]], align 4
; CHECK-NEXT:    [[PTR_LDS_53:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 53
; CHECK-NEXT:    [[VAL_53:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_53]], align 4
; CHECK-NEXT:    [[PTR_OUT_53:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 53
; CHECK-NEXT:    store i32 [[VAL_53]], ptr addrspace(1) [[PTR_OUT_53]], align 4
; CHECK-NEXT:    [[PTR_LDS_54:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 54
; CHECK-NEXT:    [[VAL_54:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_54]], align 4
; CHECK-NEXT:    [[PTR_OUT_54:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 54
; CHECK-NEXT:    store i32 [[VAL_54]], ptr addrspace(1) [[PTR_OUT_54]], align 4
; CHECK-NEXT:    [[PTR_LDS_55:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 55
; CHECK-NEXT:    [[VAL_55:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_55]], align 4
; CHECK-NEXT:    [[PTR_OUT_55:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 55
; CHECK-NEXT:    store i32 [[VAL_55]], ptr addrspace(1) [[PTR_OUT_55]], align 4
; CHECK-NEXT:    [[PTR_LDS_56:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 56
; CHECK-NEXT:    [[VAL_56:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_56]], align 4
; CHECK-NEXT:    [[PTR_OUT_56:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 56
; CHECK-NEXT:    store i32 [[VAL_56]], ptr addrspace(1) [[PTR_OUT_56]], align 4
; CHECK-NEXT:    [[PTR_LDS_57:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 57
; CHECK-NEXT:    [[VAL_57:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_57]], align 4
; CHECK-NEXT:    [[PTR_OUT_57:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 57
; CHECK-NEXT:    store i32 [[VAL_57]], ptr addrspace(1) [[PTR_OUT_57]], align 4
; CHECK-NEXT:    [[PTR_LDS_58:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 58
; CHECK-NEXT:    [[VAL_58:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_58]], align 4
; CHECK-NEXT:    [[PTR_OUT_58:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 58
; CHECK-NEXT:    store i32 [[VAL_58]], ptr addrspace(1) [[PTR_OUT_58]], align 4
; CHECK-NEXT:    [[PTR_LDS_59:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 59
; CHECK-NEXT:    [[VAL_59:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_59]], align 4
; CHECK-NEXT:    [[PTR_OUT_59:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 59
; CHECK-NEXT:    store i32 [[VAL_59]], ptr addrspace(1) [[PTR_OUT_59]], align 4
; CHECK-NEXT:    [[PTR_LDS_60:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 60
; CHECK-NEXT:    [[VAL_60:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_60]], align 4
; CHECK-NEXT:    [[PTR_OUT_60:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 60
; CHECK-NEXT:    store i32 [[VAL_60]], ptr addrspace(1) [[PTR_OUT_60]], align 4
; CHECK-NEXT:    [[PTR_LDS_61:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 61
; CHECK-NEXT:    [[VAL_61:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_61]], align 4
; CHECK-NEXT:    [[PTR_OUT_61:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 61
; CHECK-NEXT:    store i32 [[VAL_61]], ptr addrspace(1) [[PTR_OUT_61]], align 4
; CHECK-NEXT:    [[PTR_LDS_62:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 62
; CHECK-NEXT:    [[VAL_62:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_62]], align 4
; CHECK-NEXT:    [[PTR_OUT_62:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 62
; CHECK-NEXT:    store i32 [[VAL_62]], ptr addrspace(1) [[PTR_OUT_62]], align 4
; CHECK-NEXT:    [[PTR_LDS_63:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 63
; CHECK-NEXT:    [[VAL_63:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_63]], align 4
; CHECK-NEXT:    [[PTR_OUT_63:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 63
; CHECK-NEXT:    store i32 [[VAL_63]], ptr addrspace(1) [[PTR_OUT_63]], align 4
; CHECK-NEXT:    [[PTR_LDS_64:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 64
; CHECK-NEXT:    [[VAL_64:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_64]], align 4
; CHECK-NEXT:    [[PTR_OUT_64:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 64
; CHECK-NEXT:    store i32 [[VAL_64]], ptr addrspace(1) [[PTR_OUT_64]], align 4
; CHECK-NEXT:    [[PTR_LDS_65:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 65
; CHECK-NEXT:    [[VAL_65:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_65]], align 4
; CHECK-NEXT:    [[PTR_OUT_65:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 65
; CHECK-NEXT:    store i32 [[VAL_65]], ptr addrspace(1) [[PTR_OUT_65]], align 4
; CHECK-NEXT:    [[PTR_LDS_66:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 66
; CHECK-NEXT:    [[VAL_66:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_66]], align 4
; CHECK-NEXT:    [[PTR_OUT_66:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 66
; CHECK-NEXT:    store i32 [[VAL_66]], ptr addrspace(1) [[PTR_OUT_66]], align 4
; CHECK-NEXT:    [[PTR_LDS_67:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 67
; CHECK-NEXT:    [[VAL_67:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_67]], align 4
; CHECK-NEXT:    [[PTR_OUT_67:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 67
; CHECK-NEXT:    store i32 [[VAL_67]], ptr addrspace(1) [[PTR_OUT_67]], align 4
; CHECK-NEXT:    [[PTR_LDS_68:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 68
; CHECK-NEXT:    [[VAL_68:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_68]], align 4
; CHECK-NEXT:    [[PTR_OUT_68:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 68
; CHECK-NEXT:    store i32 [[VAL_68]], ptr addrspace(1) [[PTR_OUT_68]], align 4
; CHECK-NEXT:    [[PTR_LDS_69:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 69
; CHECK-NEXT:    [[VAL_69:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_69]], align 4
; CHECK-NEXT:    [[PTR_OUT_69:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 69
; CHECK-NEXT:    store i32 [[VAL_69]], ptr addrspace(1) [[PTR_OUT_69]], align 4
; CHECK-NEXT:    [[PTR_LDS_70:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 70
; CHECK-NEXT:    [[VAL_70:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_70]], align 4
; CHECK-NEXT:    [[PTR_OUT_70:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 70
; CHECK-NEXT:    store i32 [[VAL_70]], ptr addrspace(1) [[PTR_OUT_70]], align 4
; CHECK-NEXT:    [[PTR_LDS_71:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 71
; CHECK-NEXT:    [[VAL_71:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_71]], align 4
; CHECK-NEXT:    [[PTR_OUT_71:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 71
; CHECK-NEXT:    store i32 [[VAL_71]], ptr addrspace(1) [[PTR_OUT_71]], align 4
; CHECK-NEXT:    [[PTR_LDS_72:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 72
; CHECK-NEXT:    [[VAL_72:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_72]], align 4
; CHECK-NEXT:    [[PTR_OUT_72:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 72
; CHECK-NEXT:    store i32 [[VAL_72]], ptr addrspace(1) [[PTR_OUT_72]], align 4
; CHECK-NEXT:    [[PTR_LDS_73:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 73
; CHECK-NEXT:    [[VAL_73:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_73]], align 4
; CHECK-NEXT:    [[PTR_OUT_73:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 73
; CHECK-NEXT:    store i32 [[VAL_73]], ptr addrspace(1) [[PTR_OUT_73]], align 4
; CHECK-NEXT:    [[PTR_LDS_74:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 74
; CHECK-NEXT:    [[VAL_74:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_74]], align 4
; CHECK-NEXT:    [[PTR_OUT_74:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 74
; CHECK-NEXT:    store i32 [[VAL_74]], ptr addrspace(1) [[PTR_OUT_74]], align 4
; CHECK-NEXT:    [[PTR_LDS_75:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 75
; CHECK-NEXT:    [[VAL_75:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_75]], align 4
; CHECK-NEXT:    [[PTR_OUT_75:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 75
; CHECK-NEXT:    store i32 [[VAL_75]], ptr addrspace(1) [[PTR_OUT_75]], align 4
; CHECK-NEXT:    [[PTR_LDS_76:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 76
; CHECK-NEXT:    [[VAL_76:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_76]], align 4
; CHECK-NEXT:    [[PTR_OUT_76:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 76
; CHECK-NEXT:    store i32 [[VAL_76]], ptr addrspace(1) [[PTR_OUT_76]], align 4
; CHECK-NEXT:    [[PTR_LDS_77:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 77
; CHECK-NEXT:    [[VAL_77:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_77]], align 4
; CHECK-NEXT:    [[PTR_OUT_77:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 77
; CHECK-NEXT:    store i32 [[VAL_77]], ptr addrspace(1) [[PTR_OUT_77]], align 4
; CHECK-NEXT:    [[PTR_LDS_78:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 78
; CHECK-NEXT:    [[VAL_78:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_78]], align 4
; CHECK-NEXT:    [[PTR_OUT_78:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 78
; CHECK-NEXT:    store i32 [[VAL_78]], ptr addrspace(1) [[PTR_OUT_78]], align 4
; CHECK-NEXT:    [[PTR_LDS_79:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 79
; CHECK-NEXT:    [[VAL_79:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_79]], align 4
; CHECK-NEXT:    [[PTR_OUT_79:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 79
; CHECK-NEXT:    store i32 [[VAL_79]], ptr addrspace(1) [[PTR_OUT_79]], align 4
; CHECK-NEXT:    [[PTR_LDS_80:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 80
; CHECK-NEXT:    [[VAL_80:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_80]], align 4
; CHECK-NEXT:    [[PTR_OUT_80:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 80
; CHECK-NEXT:    store i32 [[VAL_80]], ptr addrspace(1) [[PTR_OUT_80]], align 4
; CHECK-NEXT:    [[PTR_LDS_81:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 81
; CHECK-NEXT:    [[VAL_81:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_81]], align 4
; CHECK-NEXT:    [[PTR_OUT_81:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 81
; CHECK-NEXT:    store i32 [[VAL_81]], ptr addrspace(1) [[PTR_OUT_81]], align 4
; CHECK-NEXT:    [[PTR_LDS_82:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 82
; CHECK-NEXT:    [[VAL_82:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_82]], align 4
; CHECK-NEXT:    [[PTR_OUT_82:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 82
; CHECK-NEXT:    store i32 [[VAL_82]], ptr addrspace(1) [[PTR_OUT_82]], align 4
; CHECK-NEXT:    [[PTR_LDS_83:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 83
; CHECK-NEXT:    [[VAL_83:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_83]], align 4
; CHECK-NEXT:    [[PTR_OUT_83:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 83
; CHECK-NEXT:    store i32 [[VAL_83]], ptr addrspace(1) [[PTR_OUT_83]], align 4
; CHECK-NEXT:    [[PTR_LDS_84:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 84
; CHECK-NEXT:    [[VAL_84:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_84]], align 4
; CHECK-NEXT:    [[PTR_OUT_84:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 84
; CHECK-NEXT:    store i32 [[VAL_84]], ptr addrspace(1) [[PTR_OUT_84]], align 4
; CHECK-NEXT:    [[PTR_LDS_85:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 85
; CHECK-NEXT:    [[VAL_85:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_85]], align 4
; CHECK-NEXT:    [[PTR_OUT_85:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 85
; CHECK-NEXT:    store i32 [[VAL_85]], ptr addrspace(1) [[PTR_OUT_85]], align 4
; CHECK-NEXT:    [[PTR_LDS_86:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 86
; CHECK-NEXT:    [[VAL_86:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_86]], align 4
; CHECK-NEXT:    [[PTR_OUT_86:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 86
; CHECK-NEXT:    store i32 [[VAL_86]], ptr addrspace(1) [[PTR_OUT_86]], align 4
; CHECK-NEXT:    [[PTR_LDS_87:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 87
; CHECK-NEXT:    [[VAL_87:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_87]], align 4
; CHECK-NEXT:    [[PTR_OUT_87:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 87
; CHECK-NEXT:    store i32 [[VAL_87]], ptr addrspace(1) [[PTR_OUT_87]], align 4
; CHECK-NEXT:    [[PTR_LDS_88:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 88
; CHECK-NEXT:    [[VAL_88:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_88]], align 4
; CHECK-NEXT:    [[PTR_OUT_88:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 88
; CHECK-NEXT:    store i32 [[VAL_88]], ptr addrspace(1) [[PTR_OUT_88]], align 4
; CHECK-NEXT:    [[PTR_LDS_89:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 89
; CHECK-NEXT:    [[VAL_89:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_89]], align 4
; CHECK-NEXT:    [[PTR_OUT_89:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 89
; CHECK-NEXT:    store i32 [[VAL_89]], ptr addrspace(1) [[PTR_OUT_89]], align 4
; CHECK-NEXT:    [[PTR_LDS_90:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 90
; CHECK-NEXT:    [[VAL_90:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_90]], align 4
; CHECK-NEXT:    [[PTR_OUT_90:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 90
; CHECK-NEXT:    store i32 [[VAL_90]], ptr addrspace(1) [[PTR_OUT_90]], align 4
; CHECK-NEXT:    [[PTR_LDS_91:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 91
; CHECK-NEXT:    [[VAL_91:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_91]], align 4
; CHECK-NEXT:    [[PTR_OUT_91:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 91
; CHECK-NEXT:    store i32 [[VAL_91]], ptr addrspace(1) [[PTR_OUT_91]], align 4
; CHECK-NEXT:    [[PTR_LDS_92:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 92
; CHECK-NEXT:    [[VAL_92:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_92]], align 4
; CHECK-NEXT:    [[PTR_OUT_92:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 92
; CHECK-NEXT:    store i32 [[VAL_92]], ptr addrspace(1) [[PTR_OUT_92]], align 4
; CHECK-NEXT:    [[PTR_LDS_93:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 93
; CHECK-NEXT:    [[VAL_93:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_93]], align 4
; CHECK-NEXT:    [[PTR_OUT_93:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 93
; CHECK-NEXT:    store i32 [[VAL_93]], ptr addrspace(1) [[PTR_OUT_93]], align 4
; CHECK-NEXT:    [[PTR_LDS_94:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 94
; CHECK-NEXT:    [[VAL_94:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_94]], align 4
; CHECK-NEXT:    [[PTR_OUT_94:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 94
; CHECK-NEXT:    store i32 [[VAL_94]], ptr addrspace(1) [[PTR_OUT_94]], align 4
; CHECK-NEXT:    [[PTR_LDS_95:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 95
; CHECK-NEXT:    [[VAL_95:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_95]], align 4
; CHECK-NEXT:    [[PTR_OUT_95:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 95
; CHECK-NEXT:    store i32 [[VAL_95]], ptr addrspace(1) [[PTR_OUT_95]], align 4
; CHECK-NEXT:    [[PTR_LDS_96:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 96
; CHECK-NEXT:    [[VAL_96:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_96]], align 4
; CHECK-NEXT:    [[PTR_OUT_96:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 96
; CHECK-NEXT:    store i32 [[VAL_96]], ptr addrspace(1) [[PTR_OUT_96]], align 4
; CHECK-NEXT:    [[PTR_LDS_97:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 97
; CHECK-NEXT:    [[VAL_97:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_97]], align 4
; CHECK-NEXT:    [[PTR_OUT_97:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 97
; CHECK-NEXT:    store i32 [[VAL_97]], ptr addrspace(1) [[PTR_OUT_97]], align 4
; CHECK-NEXT:    [[PTR_LDS_98:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 98
; CHECK-NEXT:    [[VAL_98:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_98]], align 4
; CHECK-NEXT:    [[PTR_OUT_98:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 98
; CHECK-NEXT:    store i32 [[VAL_98]], ptr addrspace(1) [[PTR_OUT_98]], align 4
; CHECK-NEXT:    [[PTR_LDS_99:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 99
; CHECK-NEXT:    [[VAL_99:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_99]], align 4
; CHECK-NEXT:    [[PTR_OUT_99:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 99
; CHECK-NEXT:    store i32 [[VAL_99]], ptr addrspace(1) [[PTR_OUT_99]], align 4
; CHECK-NEXT:    [[PTR_LDS_100:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 100
; CHECK-NEXT:    [[VAL_100:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_100]], align 4
; CHECK-NEXT:    [[PTR_OUT_100:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 100
; CHECK-NEXT:    store i32 [[VAL_100]], ptr addrspace(1) [[PTR_OUT_100]], align 4
; CHECK-NEXT:    [[PTR_LDS_101:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 101
; CHECK-NEXT:    [[VAL_101:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_101]], align 4
; CHECK-NEXT:    [[PTR_OUT_101:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 101
; CHECK-NEXT:    store i32 [[VAL_101]], ptr addrspace(1) [[PTR_OUT_101]], align 4
; CHECK-NEXT:    [[PTR_LDS_102:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 102
; CHECK-NEXT:    [[VAL_102:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_102]], align 4
; CHECK-NEXT:    [[PTR_OUT_102:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 102
; CHECK-NEXT:    store i32 [[VAL_102]], ptr addrspace(1) [[PTR_OUT_102]], align 4
; CHECK-NEXT:    [[PTR_LDS_103:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 103
; CHECK-NEXT:    [[VAL_103:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_103]], align 4
; CHECK-NEXT:    [[PTR_OUT_103:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 103
; CHECK-NEXT:    store i32 [[VAL_103]], ptr addrspace(1) [[PTR_OUT_103]], align 4
; CHECK-NEXT:    [[PTR_LDS_104:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 104
; CHECK-NEXT:    [[VAL_104:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_104]], align 4
; CHECK-NEXT:    [[PTR_OUT_104:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 104
; CHECK-NEXT:    store i32 [[VAL_104]], ptr addrspace(1) [[PTR_OUT_104]], align 4
; CHECK-NEXT:    [[PTR_LDS_105:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 105
; CHECK-NEXT:    [[VAL_105:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_105]], align 4
; CHECK-NEXT:    [[PTR_OUT_105:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 105
; CHECK-NEXT:    store i32 [[VAL_105]], ptr addrspace(1) [[PTR_OUT_105]], align 4
; CHECK-NEXT:    [[PTR_LDS_106:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 106
; CHECK-NEXT:    [[VAL_106:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_106]], align 4
; CHECK-NEXT:    [[PTR_OUT_106:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 106
; CHECK-NEXT:    store i32 [[VAL_106]], ptr addrspace(1) [[PTR_OUT_106]], align 4
; CHECK-NEXT:    [[PTR_LDS_107:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 107
; CHECK-NEXT:    [[VAL_107:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_107]], align 4
; CHECK-NEXT:    [[PTR_OUT_107:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 107
; CHECK-NEXT:    store i32 [[VAL_107]], ptr addrspace(1) [[PTR_OUT_107]], align 4
; CHECK-NEXT:    [[PTR_LDS_108:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 108
; CHECK-NEXT:    [[VAL_108:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_108]], align 4
; CHECK-NEXT:    [[PTR_OUT_108:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 108
; CHECK-NEXT:    store i32 [[VAL_108]], ptr addrspace(1) [[PTR_OUT_108]], align 4
; CHECK-NEXT:    [[PTR_LDS_109:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 109
; CHECK-NEXT:    [[VAL_109:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_109]], align 4
; CHECK-NEXT:    [[PTR_OUT_109:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 109
; CHECK-NEXT:    store i32 [[VAL_109]], ptr addrspace(1) [[PTR_OUT_109]], align 4
; CHECK-NEXT:    [[PTR_LDS_110:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 110
; CHECK-NEXT:    [[VAL_110:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_110]], align 4
; CHECK-NEXT:    [[PTR_OUT_110:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 110
; CHECK-NEXT:    store i32 [[VAL_110]], ptr addrspace(1) [[PTR_OUT_110]], align 4
; CHECK-NEXT:    [[PTR_LDS_111:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 111
; CHECK-NEXT:    [[VAL_111:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_111]], align 4
; CHECK-NEXT:    [[PTR_OUT_111:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 111
; CHECK-NEXT:    store i32 [[VAL_111]], ptr addrspace(1) [[PTR_OUT_111]], align 4
; CHECK-NEXT:    [[PTR_LDS_112:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 112
; CHECK-NEXT:    [[VAL_112:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_112]], align 4
; CHECK-NEXT:    [[PTR_OUT_112:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 112
; CHECK-NEXT:    store i32 [[VAL_112]], ptr addrspace(1) [[PTR_OUT_112]], align 4
; CHECK-NEXT:    [[PTR_LDS_113:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 113
; CHECK-NEXT:    [[VAL_113:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_113]], align 4
; CHECK-NEXT:    [[PTR_OUT_113:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 113
; CHECK-NEXT:    store i32 [[VAL_113]], ptr addrspace(1) [[PTR_OUT_113]], align 4
; CHECK-NEXT:    [[PTR_LDS_114:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 114
; CHECK-NEXT:    [[VAL_114:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_114]], align 4
; CHECK-NEXT:    [[PTR_OUT_114:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 114
; CHECK-NEXT:    store i32 [[VAL_114]], ptr addrspace(1) [[PTR_OUT_114]], align 4
; CHECK-NEXT:    [[PTR_LDS_115:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 115
; CHECK-NEXT:    [[VAL_115:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_115]], align 4
; CHECK-NEXT:    [[PTR_OUT_115:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 115
; CHECK-NEXT:    store i32 [[VAL_115]], ptr addrspace(1) [[PTR_OUT_115]], align 4
; CHECK-NEXT:    [[PTR_LDS_116:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 116
; CHECK-NEXT:    [[VAL_116:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_116]], align 4
; CHECK-NEXT:    [[PTR_OUT_116:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 116
; CHECK-NEXT:    store i32 [[VAL_116]], ptr addrspace(1) [[PTR_OUT_116]], align 4
; CHECK-NEXT:    [[PTR_LDS_117:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 117
; CHECK-NEXT:    [[VAL_117:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_117]], align 4
; CHECK-NEXT:    [[PTR_OUT_117:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 117
; CHECK-NEXT:    store i32 [[VAL_117]], ptr addrspace(1) [[PTR_OUT_117]], align 4
; CHECK-NEXT:    [[PTR_LDS_118:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 118
; CHECK-NEXT:    [[VAL_118:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_118]], align 4
; CHECK-NEXT:    [[PTR_OUT_118:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 118
; CHECK-NEXT:    store i32 [[VAL_118]], ptr addrspace(1) [[PTR_OUT_118]], align 4
; CHECK-NEXT:    [[PTR_LDS_119:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 119
; CHECK-NEXT:    [[VAL_119:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_119]], align 4
; CHECK-NEXT:    [[PTR_OUT_119:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 119
; CHECK-NEXT:    store i32 [[VAL_119]], ptr addrspace(1) [[PTR_OUT_119]], align 4
; CHECK-NEXT:    [[PTR_LDS_120:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 120
; CHECK-NEXT:    [[VAL_120:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_120]], align 4
; CHECK-NEXT:    [[PTR_OUT_120:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 120
; CHECK-NEXT:    store i32 [[VAL_120]], ptr addrspace(1) [[PTR_OUT_120]], align 4
; CHECK-NEXT:    [[PTR_LDS_121:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 121
; CHECK-NEXT:    [[VAL_121:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_121]], align 4
; CHECK-NEXT:    [[PTR_OUT_121:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 121
; CHECK-NEXT:    store i32 [[VAL_121]], ptr addrspace(1) [[PTR_OUT_121]], align 4
; CHECK-NEXT:    [[PTR_LDS_122:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 122
; CHECK-NEXT:    [[VAL_122:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_122]], align 4
; CHECK-NEXT:    [[PTR_OUT_122:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 122
; CHECK-NEXT:    store i32 [[VAL_122]], ptr addrspace(1) [[PTR_OUT_122]], align 4
; CHECK-NEXT:    [[PTR_LDS_123:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 123
; CHECK-NEXT:    [[VAL_123:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_123]], align 4
; CHECK-NEXT:    [[PTR_OUT_123:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 123
; CHECK-NEXT:    store i32 [[VAL_123]], ptr addrspace(1) [[PTR_OUT_123]], align 4
; CHECK-NEXT:    [[PTR_LDS_124:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 124
; CHECK-NEXT:    [[VAL_124:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_124]], align 4
; CHECK-NEXT:    [[PTR_OUT_124:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 124
; CHECK-NEXT:    store i32 [[VAL_124]], ptr addrspace(1) [[PTR_OUT_124]], align 4
; CHECK-NEXT:    [[PTR_LDS_125:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 125
; CHECK-NEXT:    [[VAL_125:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_125]], align 4
; CHECK-NEXT:    [[PTR_OUT_125:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 125
; CHECK-NEXT:    store i32 [[VAL_125]], ptr addrspace(1) [[PTR_OUT_125]], align 4
; CHECK-NEXT:    [[PTR_LDS_126:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 126
; CHECK-NEXT:    [[VAL_126:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_126]], align 4
; CHECK-NEXT:    [[PTR_OUT_126:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 126
; CHECK-NEXT:    store i32 [[VAL_126]], ptr addrspace(1) [[PTR_OUT_126]], align 4
; CHECK-NEXT:    [[PTR_LDS_127:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 127
; CHECK-NEXT:    [[VAL_127:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_127]], align 4
; CHECK-NEXT:    [[PTR_OUT_127:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 127
; CHECK-NEXT:    store i32 [[VAL_127]], ptr addrspace(1) [[PTR_OUT_127]], align 4
; CHECK-NEXT:    [[PTR_LDS_128:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 128
; CHECK-NEXT:    [[VAL_128:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_128]], align 4
; CHECK-NEXT:    [[PTR_OUT_128:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 128
; CHECK-NEXT:    store i32 [[VAL_128]], ptr addrspace(1) [[PTR_OUT_128]], align 4
; CHECK-NEXT:    ret void
;
entry:
  br label %loop.header

loop.header:
  %counter = phi i32 [0, %entry], [%inc, %loop.inc]
  br label %loop.body

loop.body:
  %ptr_lds = getelementptr i32, ptr addrspace(3) %lds, i32 %counter
  %val = load i32, ptr addrspace(3) %ptr_lds
  %ptr_out = getelementptr i32, ptr addrspace(1) %out, i32 %counter
  store i32 %val, ptr addrspace(1) %ptr_out
  br label %loop.inc

loop.inc:
  %inc = add i32 %counter, 1
  %cond = icmp sge i32 %counter, 128
  br i1 %cond, label  %exit, label %loop.header

exit:
  ret void
}

; Check that a loop with if inside completely unrolled to eliminate phi and if

define amdgpu_kernel void @unroll_for_if(ptr addrspace(5) %a) {
; CHECK-LABEL: @unroll_for_if(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ARRAYIDX_1:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A:%.*]], i64 1
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_1]], align 4
; CHECK-NEXT:    [[ARRAYIDX_2:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A]], i64 2
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_2]], align 4
; CHECK-NEXT:    [[ARRAYIDX_3:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A]], i64 3
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_3]], align 4
; CHECK-NEXT:    [[ARRAYIDX_4:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A]], i64 4
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_4]], align 4
; CHECK-NEXT:    [[ARRAYIDX_5:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A]], i64 5
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_5]], align 4
; CHECK-NEXT:    [[ARRAYIDX_6:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A]], i64 6
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_6]], align 4
; CHECK-NEXT:    [[ARRAYIDX_7:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A]], i64 7
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_7]], align 4
; CHECK-NEXT:    [[ARRAYIDX_8:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A]], i64 8
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_8]], align 4
; CHECK-NEXT:    [[ARRAYIDX_9:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A]], i64 9
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_9]], align 4
; CHECK-NEXT:    [[ARRAYIDX_10:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A]], i64 10
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_10]], align 4
; CHECK-NEXT:    [[ARRAYIDX_11:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A]], i64 11
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_11]], align 4
; CHECK-NEXT:    [[ARRAYIDX_12:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A]], i64 12
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_12]], align 4
; CHECK-NEXT:    [[ARRAYIDX_13:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A]], i64 13
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_13]], align 4
; CHECK-NEXT:    [[ARRAYIDX_14:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A]], i64 14
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_14]], align 4
; CHECK-NEXT:    [[ARRAYIDX_15:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A]], i64 15
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_15]], align 4
; CHECK-NEXT:    [[ARRAYIDX_16:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A]], i64 16
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_16]], align 4
; CHECK-NEXT:    [[ARRAYIDX_17:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A]], i64 17
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_17]], align 4
; CHECK-NEXT:    [[ARRAYIDX_18:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A]], i64 18
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_18]], align 4
; CHECK-NEXT:    [[ARRAYIDX_19:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A]], i64 19
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_19]], align 4
; CHECK-NEXT:    [[ARRAYIDX_20:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A]], i64 20
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_20]], align 4
; CHECK-NEXT:    [[ARRAYIDX_21:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A]], i64 21
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_21]], align 4
; CHECK-NEXT:    [[ARRAYIDX_22:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A]], i64 22
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_22]], align 4
; CHECK-NEXT:    [[ARRAYIDX_23:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A]], i64 23
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_23]], align 4
; CHECK-NEXT:    [[ARRAYIDX_24:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A]], i64 24
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_24]], align 4
; CHECK-NEXT:    [[ARRAYIDX_25:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A]], i64 25
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_25]], align 4
; CHECK-NEXT:    [[ARRAYIDX_26:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A]], i64 26
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_26]], align 4
; CHECK-NEXT:    [[ARRAYIDX_27:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A]], i64 27
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_27]], align 4
; CHECK-NEXT:    [[ARRAYIDX_28:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A]], i64 28
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_28]], align 4
; CHECK-NEXT:    [[ARRAYIDX_29:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A]], i64 29
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_29]], align 4
; CHECK-NEXT:    [[ARRAYIDX_30:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A]], i64 30
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_30]], align 4
; CHECK-NEXT:    [[ARRAYIDX_31:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A]], i64 31
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_31]], align 4
; CHECK-NEXT:    [[ARRAYIDX_32:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A]], i64 32
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_32]], align 4
; CHECK-NEXT:    [[ARRAYIDX_33:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A]], i64 33
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_33]], align 4
; CHECK-NEXT:    [[ARRAYIDX_34:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A]], i64 34
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_34]], align 4
; CHECK-NEXT:    [[ARRAYIDX_35:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A]], i64 35
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_35]], align 4
; CHECK-NEXT:    [[ARRAYIDX_36:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A]], i64 36
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_36]], align 4
; CHECK-NEXT:    [[ARRAYIDX_37:%.*]] = getelementptr inbounds i32, ptr addrspace(5) [[A]], i64 37
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[ARRAYIDX_37]], align 4
; CHECK-NEXT:    ret void
;
entry:
  br label %for.body

for.body:                                         ; preds = %entry, %for.inc
  %i1 = phi i32 [ 0, %entry ], [ %inc, %for.inc ]
  %tobool = icmp eq i32 %i1, 0
  br i1 %tobool, label %for.inc, label %if.then

if.then:                                          ; preds = %for.body
  %0 = sext i32 %i1 to i64
  %arrayidx = getelementptr inbounds i32, ptr addrspace(5) %a, i64 %0
  store i32 0, ptr addrspace(5) %arrayidx, align 4
  br label %for.inc

for.inc:                                          ; preds = %for.body, %if.then
  %inc = add nuw nsw i32 %i1, 1
  %cmp = icmp ult i32 %inc, 38
  br i1 %cmp, label %for.body, label %for.end

for.end:                                          ; preds = %for.cond
  ret void
}

; Check that runtime unroll is enabled for local memory references

define amdgpu_kernel void @local_memory_runtime(ptr addrspace(1) %out, ptr addrspace(3) %lds, i32 %n) {
; CHECK-LABEL: @local_memory_runtime(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SMAX:%.*]] = call i32 @llvm.smax.i32(i32 [[N:%.*]], i32 0)
; CHECK-NEXT:    [[TMP0:%.*]] = add nuw i32 [[SMAX]], 1
; CHECK-NEXT:    [[XTRAITER:%.*]] = and i32 [[TMP0]], 7
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ult i32 [[SMAX]], 7
; CHECK-NEXT:    br i1 [[TMP1]], label [[LOOP_HEADER_EPIL_PREHEADER:%.*]], label [[ENTRY_NEW:%.*]]
; CHECK:       entry.new:
; CHECK-NEXT:    [[UNROLL_ITER:%.*]] = sub i32 [[TMP0]], [[XTRAITER]]
; CHECK-NEXT:    br label [[LOOP_HEADER:%.*]]
; CHECK:       loop.header:
; CHECK-NEXT:    [[COUNTER:%.*]] = phi i32 [ 0, [[ENTRY_NEW]] ], [ [[INC_7:%.*]], [[LOOP_HEADER]] ]
; CHECK-NEXT:    [[NITER:%.*]] = phi i32 [ 0, [[ENTRY_NEW]] ], [ [[NITER_NEXT_7:%.*]], [[LOOP_HEADER]] ]
; CHECK-NEXT:    [[PTR_LDS:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS:%.*]], i32 [[COUNTER]]
; CHECK-NEXT:    [[VAL:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS]], align 4
; CHECK-NEXT:    [[PTR_OUT:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT:%.*]], i32 [[COUNTER]]
; CHECK-NEXT:    store i32 [[VAL]], ptr addrspace(1) [[PTR_OUT]], align 4
; CHECK-NEXT:    [[INC:%.*]] = add nuw nsw i32 [[COUNTER]], 1
; CHECK-NEXT:    [[PTR_LDS_1:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 [[INC]]
; CHECK-NEXT:    [[VAL_1:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_1]], align 4
; CHECK-NEXT:    [[PTR_OUT_1:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 [[INC]]
; CHECK-NEXT:    store i32 [[VAL_1]], ptr addrspace(1) [[PTR_OUT_1]], align 4
; CHECK-NEXT:    [[INC_1:%.*]] = add nuw nsw i32 [[COUNTER]], 2
; CHECK-NEXT:    [[PTR_LDS_2:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 [[INC_1]]
; CHECK-NEXT:    [[VAL_2:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_2]], align 4
; CHECK-NEXT:    [[PTR_OUT_2:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 [[INC_1]]
; CHECK-NEXT:    store i32 [[VAL_2]], ptr addrspace(1) [[PTR_OUT_2]], align 4
; CHECK-NEXT:    [[INC_2:%.*]] = add nuw nsw i32 [[COUNTER]], 3
; CHECK-NEXT:    [[PTR_LDS_3:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 [[INC_2]]
; CHECK-NEXT:    [[VAL_3:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_3]], align 4
; CHECK-NEXT:    [[PTR_OUT_3:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 [[INC_2]]
; CHECK-NEXT:    store i32 [[VAL_3]], ptr addrspace(1) [[PTR_OUT_3]], align 4
; CHECK-NEXT:    [[INC_3:%.*]] = add nuw nsw i32 [[COUNTER]], 4
; CHECK-NEXT:    [[PTR_LDS_4:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 [[INC_3]]
; CHECK-NEXT:    [[VAL_4:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_4]], align 4
; CHECK-NEXT:    [[PTR_OUT_4:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 [[INC_3]]
; CHECK-NEXT:    store i32 [[VAL_4]], ptr addrspace(1) [[PTR_OUT_4]], align 4
; CHECK-NEXT:    [[INC_4:%.*]] = add nuw nsw i32 [[COUNTER]], 5
; CHECK-NEXT:    [[PTR_LDS_5:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 [[INC_4]]
; CHECK-NEXT:    [[VAL_5:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_5]], align 4
; CHECK-NEXT:    [[PTR_OUT_5:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 [[INC_4]]
; CHECK-NEXT:    store i32 [[VAL_5]], ptr addrspace(1) [[PTR_OUT_5]], align 4
; CHECK-NEXT:    [[INC_5:%.*]] = add nuw nsw i32 [[COUNTER]], 6
; CHECK-NEXT:    [[PTR_LDS_6:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 [[INC_5]]
; CHECK-NEXT:    [[VAL_6:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_6]], align 4
; CHECK-NEXT:    [[PTR_OUT_6:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 [[INC_5]]
; CHECK-NEXT:    store i32 [[VAL_6]], ptr addrspace(1) [[PTR_OUT_6]], align 4
; CHECK-NEXT:    [[INC_6:%.*]] = add nuw nsw i32 [[COUNTER]], 7
; CHECK-NEXT:    [[PTR_LDS_7:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 [[INC_6]]
; CHECK-NEXT:    [[VAL_7:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_7]], align 4
; CHECK-NEXT:    [[PTR_OUT_7:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 [[INC_6]]
; CHECK-NEXT:    store i32 [[VAL_7]], ptr addrspace(1) [[PTR_OUT_7]], align 4
; CHECK-NEXT:    [[INC_7]] = add i32 [[COUNTER]], 8
; CHECK-NEXT:    [[NITER_NEXT_7]] = add i32 [[NITER]], 8
; CHECK-NEXT:    [[NITER_NCMP_7:%.*]] = icmp eq i32 [[NITER_NEXT_7]], [[UNROLL_ITER]]
; CHECK-NEXT:    br i1 [[NITER_NCMP_7]], label [[EXIT_UNR_LCSSA:%.*]], label [[LOOP_HEADER]]
; CHECK:       exit.unr-lcssa:
; CHECK-NEXT:    [[COUNTER_UNR:%.*]] = phi i32 [ [[INC_7]], [[LOOP_HEADER]] ]
; CHECK-NEXT:    [[LCMP_MOD:%.*]] = icmp ne i32 [[XTRAITER]], 0
; CHECK-NEXT:    br i1 [[LCMP_MOD]], label [[LOOP_HEADER_EPIL_PREHEADER]], label [[EXIT:%.*]]
; CHECK:       loop.header.epil.preheader:
; CHECK-NEXT:    [[COUNTER_EPIL_INIT:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[COUNTER_UNR]], [[EXIT_UNR_LCSSA]] ]
; CHECK-NEXT:    [[LCMP_MOD1:%.*]] = icmp ne i32 [[XTRAITER]], 0
; CHECK-NEXT:    call void @llvm.assume(i1 [[LCMP_MOD1]])
; CHECK-NEXT:    br label [[LOOP_HEADER_EPIL:%.*]]
; CHECK:       loop.header.epil:
; CHECK-NEXT:    [[COUNTER_EPIL:%.*]] = phi i32 [ [[COUNTER_EPIL_INIT]], [[LOOP_HEADER_EPIL_PREHEADER]] ], [ [[INC_EPIL:%.*]], [[LOOP_HEADER_EPIL]] ]
; CHECK-NEXT:    [[EPIL_ITER:%.*]] = phi i32 [ 0, [[LOOP_HEADER_EPIL_PREHEADER]] ], [ [[EPIL_ITER_NEXT:%.*]], [[LOOP_HEADER_EPIL]] ]
; CHECK-NEXT:    [[PTR_LDS_EPIL:%.*]] = getelementptr i32, ptr addrspace(3) [[LDS]], i32 [[COUNTER_EPIL]]
; CHECK-NEXT:    [[VAL_EPIL:%.*]] = load i32, ptr addrspace(3) [[PTR_LDS_EPIL]], align 4
; CHECK-NEXT:    [[PTR_OUT_EPIL:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i32 [[COUNTER_EPIL]]
; CHECK-NEXT:    store i32 [[VAL_EPIL]], ptr addrspace(1) [[PTR_OUT_EPIL]], align 4
; CHECK-NEXT:    [[INC_EPIL]] = add i32 [[COUNTER_EPIL]], 1
; CHECK-NEXT:    [[COND_EPIL:%.*]] = icmp sge i32 [[COUNTER_EPIL]], [[N]]
; CHECK-NEXT:    [[EPIL_ITER_NEXT]] = add i32 [[EPIL_ITER]], 1
; CHECK-NEXT:    [[EPIL_ITER_CMP:%.*]] = icmp ne i32 [[EPIL_ITER_NEXT]], [[XTRAITER]]
; CHECK-NEXT:    br i1 [[EPIL_ITER_CMP]], label [[LOOP_HEADER_EPIL]], label [[EXIT]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop.header

loop.header:
  %counter = phi i32 [0, %entry], [%inc, %loop.inc]
  br label %loop.body

loop.body:
  %ptr_lds = getelementptr i32, ptr addrspace(3) %lds, i32 %counter
  %val = load i32, ptr addrspace(3) %ptr_lds
  %ptr_out = getelementptr i32, ptr addrspace(1) %out, i32 %counter
  store i32 %val, ptr addrspace(1) %ptr_out
  br label %loop.inc

loop.inc:
  %inc = add i32 %counter, 1
  %cond = icmp sge i32 %counter, %n
  br i1 %cond, label  %exit, label %loop.header

exit:
  ret void
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; AMDGCN: {{.*}}
; R600: {{.*}}
