; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=redistribute -S | FileCheck %s

declare void @f(i32)

define void @test_ab_arg(i32 %a, i32 %b, i32 %k) {
; CHECK-LABEL: define void @test_ab_arg(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]], i32 [[K:%.*]]) {
; CHECK-NEXT:    [[K_FREEZE:%.*]] = freeze i32 [[K]]
; CHECK-NEXT:    [[B_DISTR_OP:%.*]] = mul i32 [[B]], [[K_FREEZE]]
; CHECK-NEXT:    [[AK:%.*]] = mul i32 [[A]], [[K_FREEZE]]
; CHECK-NEXT:    [[ABK:%.*]] = add i32 [[AK]], [[B_DISTR_OP]]
; CHECK-NEXT:    [[ABBK:%.*]] = add i32 [[ABK]], [[B_DISTR_OP]]
; CHECK-NEXT:    call void @f(i32 [[AK]])
; CHECK-NEXT:    call void @f(i32 [[ABK]])
; CHECK-NEXT:    call void @f(i32 [[ABBK]])
; CHECK-NEXT:    ret void
;
  %ak = mul i32 %a, %k
  %ab = add i32 %a, %b
  %abk = mul i32 %ab, %k
  %abb = add i32 %ab, %b
  %abbk = mul i32 %abb, %k
  call void @f(i32 %ak)
  call void @f(i32 %abk)
  call void @f(i32 %abbk)
  ret void
}

define void @test_ab_commutative_arg(i32 %a, i32 %b, i32 %k) {
; CHECK-LABEL: define void @test_ab_commutative_arg(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]], i32 [[K:%.*]]) {
; CHECK-NEXT:    [[K_FREEZE:%.*]] = freeze i32 [[K]]
; CHECK-NEXT:    [[B_DISTR_OP:%.*]] = mul i32 [[B]], [[K_FREEZE]]
; CHECK-NEXT:    [[AK:%.*]] = mul i32 [[A]], [[K_FREEZE]]
; CHECK-NEXT:    [[ABK:%.*]] = add i32 [[AK]], [[B_DISTR_OP]]
; CHECK-NEXT:    [[ABBK:%.*]] = add i32 [[ABK]], [[B_DISTR_OP]]
; CHECK-NEXT:    call void @f(i32 [[AK]])
; CHECK-NEXT:    call void @f(i32 [[ABK]])
; CHECK-NEXT:    call void @f(i32 [[ABBK]])
; CHECK-NEXT:    ret void
;
  %ak = mul i32 %a, %k
  %ab = add i32 %a, %b
  %abk = mul i32 %k, %ab
  %abb = add i32 %ab, %b
  %abbk = mul i32 %abb, %k
  call void @f(i32 %ak)
  call void @f(i32 %abk)
  call void @f(i32 %abbk)
  ret void
}

define void @test_aa_arg(i32 %a, i32 %k) {
; CHECK-LABEL: define void @test_aa_arg(
; CHECK-SAME: i32 [[A:%.*]], i32 [[K:%.*]]) {
; CHECK-NEXT:    [[K_FREEZE:%.*]] = freeze i32 [[K]]
; CHECK-NEXT:    [[AK:%.*]] = mul i32 [[A]], [[K_FREEZE]]
; CHECK-NEXT:    [[AAK:%.*]] = add i32 [[AK]], [[AK]]
; CHECK-NEXT:    [[AAAK:%.*]] = add i32 [[AAK]], [[AK]]
; CHECK-NEXT:    call void @f(i32 [[AK]])
; CHECK-NEXT:    call void @f(i32 [[AAK]])
; CHECK-NEXT:    call void @f(i32 [[AAAK]])
; CHECK-NEXT:    ret void
;
  %ak = mul i32 %a, %k
  %aa = add i32 %a, %a
  %aak = mul i32 %aa, %k
  %aaa = add i32 %aa, %a
  %aaak = mul i32 %aaa, %k
  call void @f(i32 %ak)
  call void @f(i32 %aak)
  call void @f(i32 %aaak)
  ret void
}

define void @test_ab_arg_noundef(i32 %a, i32 %b, i32 noundef %k) {
; CHECK-LABEL: define void @test_ab_arg_noundef(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]], i32 noundef [[K:%.*]]) {
; CHECK-NEXT:    [[B_DISTR_OP:%.*]] = mul i32 [[B]], [[K]]
; CHECK-NEXT:    [[AK:%.*]] = mul i32 [[A]], [[K]]
; CHECK-NEXT:    [[ABK:%.*]] = add i32 [[AK]], [[B_DISTR_OP]]
; CHECK-NEXT:    [[ABBK:%.*]] = add i32 [[ABK]], [[B_DISTR_OP]]
; CHECK-NEXT:    call void @f(i32 [[AK]])
; CHECK-NEXT:    call void @f(i32 [[ABK]])
; CHECK-NEXT:    call void @f(i32 [[ABBK]])
; CHECK-NEXT:    ret void
;
  %ak = mul i32 %a, %k
  %ab = add i32 %a, %b
  %abk = mul i32 %ab, %k
  %abb = add i32 %ab, %b
  %abbk = mul i32 %abb, %k
  call void @f(i32 %ak)
  call void @f(i32 %abk)
  call void @f(i32 %abbk)
  ret void
}

define void @test_ab_cd_arg(i32 %a, i32 %b, i32 %c, i32 %d) {
; CHECK-LABEL: define void @test_ab_cd_arg(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]], i32 [[C:%.*]], i32 [[D:%.*]]) {
; CHECK-NEXT:    [[CD:%.*]] = add i32 [[C]], [[D]]
; CHECK-NEXT:    [[CD_FREEZE:%.*]] = freeze i32 [[CD]]
; CHECK-NEXT:    [[B_DISTR_OP:%.*]] = mul i32 [[B]], [[CD_FREEZE]]
; CHECK-NEXT:    [[AB:%.*]] = add i32 [[A]], [[B]]
; CHECK-NEXT:    [[ABCD:%.*]] = mul i32 [[AB]], [[CD_FREEZE]]
; CHECK-NEXT:    [[AB_FREEZE:%.*]] = freeze i32 [[AB]]
; CHECK-NEXT:    [[D_DISTR_OP:%.*]] = mul i32 [[D]], [[AB_FREEZE]]
; CHECK-NEXT:    [[CD_DISTR_OP:%.*]] = mul i32 [[CD]], [[AB_FREEZE]]
; CHECK-NEXT:    [[ACD:%.*]] = mul i32 [[A]], [[CD]]
; CHECK-NEXT:    [[CAB:%.*]] = mul i32 [[C]], [[AB]]
; CHECK-NEXT:    [[CDDAB:%.*]] = add i32 [[CD_DISTR_OP]], [[D_DISTR_OP]]
; CHECK-NEXT:    [[ABBCD:%.*]] = add i32 [[ABCD]], [[B_DISTR_OP]]
; CHECK-NEXT:    [[ABBBCD:%.*]] = add i32 [[ABBCD]], [[B_DISTR_OP]]
; CHECK-NEXT:    call void @f(i32 [[ACD]])
; CHECK-NEXT:    call void @f(i32 [[ABCD]])
; CHECK-NEXT:    call void @f(i32 [[ABBCD]])
; CHECK-NEXT:    call void @f(i32 [[ABBBCD]])
; CHECK-NEXT:    call void @f(i32 [[CAB]])
; CHECK-NEXT:    call void @f(i32 [[ABCD]])
; CHECK-NEXT:    call void @f(i32 [[CDDAB]])
; CHECK-NEXT:    ret void
;
  %cd = add i32 %c, %d
  %ab = add i32 %a, %b
  %acd = mul i32 %a, %cd
  %cab = mul i32 %c, %ab
  %abcd = mul i32 %ab, %cd
  %cdd = add i32 %cd, %d
  %abb = add i32 %ab, %b
  %abbcd = mul i32 %abb, %cd
  %cddab = mul i32 %cdd, %ab
  %abbb = add i32 %abb, %b
  %abbbcd = mul i32 %abbb, %cd
  call void @f(i32 %acd)
  call void @f(i32 %abcd)
  call void @f(i32 %abbcd)
  call void @f(i32 %abbbcd)
  call void @f(i32 %cab)
  call void @f(i32 %abcd)
  call void @f(i32 %cddab)
  ret void
}

define void @test_k_after_ab(i32 %a, i32 %b, ptr %p) {
; CHECK-LABEL: define void @test_k_after_ab(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]], ptr [[P:%.*]]) {
; CHECK-NEXT:    [[K:%.*]] = load i32, ptr [[P]], align 4
; CHECK-NEXT:    [[K_FREEZE:%.*]] = freeze i32 [[K]]
; CHECK-NEXT:    [[B_DISTR_OP:%.*]] = mul i32 [[B]], [[K_FREEZE]]
; CHECK-NEXT:    [[AK:%.*]] = mul i32 [[A]], [[K_FREEZE]]
; CHECK-NEXT:    [[ABK:%.*]] = add i32 [[AK]], [[B_DISTR_OP]]
; CHECK-NEXT:    [[ABBK:%.*]] = add i32 [[ABK]], [[B_DISTR_OP]]
; CHECK-NEXT:    [[ABBBK:%.*]] = add i32 [[ABBK]], [[B_DISTR_OP]]
; CHECK-NEXT:    call void @f(i32 [[AK]])
; CHECK-NEXT:    call void @f(i32 [[ABK]])
; CHECK-NEXT:    call void @f(i32 [[ABBK]])
; CHECK-NEXT:    call void @f(i32 [[ABBBK]])
; CHECK-NEXT:    ret void
;
  %ab = add i32 %a, %b
  %abb = add i32 %ab, %b
  %abbb = add i32 %abb, %b
  %k = load i32, ptr %p
  %abbbk = mul i32 %abbb, %k
  %abbk = mul i32 %abb, %k
  %abk = mul i32 %ab, %k
  %ak = mul i32 %a, %k
  call void @f(i32 %ak)
  call void @f(i32 %abk)
  call void @f(i32 %abbk)
  call void @f(i32 %abbbk)
  ret void
}

define void @test_constant_fold(i32 %a) {
; CHECK-LABEL: define void @test_constant_fold(
; CHECK-SAME: i32 [[A:%.*]]) {
; CHECK-NEXT:    [[AK:%.*]] = mul i32 [[A]], 7
; CHECK-NEXT:    [[ABK:%.*]] = add i32 [[AK]], 77
; CHECK-NEXT:    [[ABBK:%.*]] = add i32 [[ABK]], 77
; CHECK-NEXT:    call void @f(i32 [[AK]])
; CHECK-NEXT:    call void @f(i32 [[ABK]])
; CHECK-NEXT:    call void @f(i32 [[ABBK]])
; CHECK-NEXT:    ret void
;
  %ak = mul i32 %a, 7
  %ab = add i32 %a, 11
  %abk = mul i32 %ab, 7
  %abb = add i32 %ab, 11
  %abbk = mul i32 %abb, 7
  call void @f(i32 %ak)
  call void @f(i32 %abk)
  call void @f(i32 %abbk)
  ret void
}

define void @test_ab_ab_arg(i32 %a, i32 %b) {
; CHECK-LABEL: define void @test_ab_ab_arg(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; CHECK-NEXT:    [[AB:%.*]] = add i32 [[A]], [[B]]
; CHECK-NEXT:    [[AB_FREEZE:%.*]] = freeze i32 [[AB]]
; CHECK-NEXT:    [[B_DISTR_OP:%.*]] = mul i32 [[B]], [[AB_FREEZE]]
; CHECK-NEXT:    [[AB_AB:%.*]] = mul i32 [[AB]], [[AB]]
; CHECK-NEXT:    [[ABB:%.*]] = add i32 [[AB]], [[B]]
; CHECK-NEXT:    [[ABB_AB:%.*]] = mul i32 [[ABB]], [[AB_FREEZE]]
; CHECK-NEXT:    [[ABBB_AB:%.*]] = add i32 [[ABB_AB]], [[B_DISTR_OP]]
; CHECK-NEXT:    call void @f(i32 [[AB_AB]])
; CHECK-NEXT:    call void @f(i32 [[ABB_AB]])
; CHECK-NEXT:    call void @f(i32 [[ABBB_AB]])
; CHECK-NEXT:    ret void
;
  %ab = add i32 %a, %b
  %ab_ab = mul i32 %ab, %ab
  %abb = add i32 %ab, %b
  %abb_ab = mul i32 %abb, %ab
  %abbb = add i32 %abb, %b
  %abbb_ab = mul i32 %abbb, %ab
  call void @f(i32 %ab_ab)
  call void @f(i32 %abb_ab)
  call void @f(i32 %abbb_ab)
  ret void
}

define void @test_ab_ac_arg(i32 %a, i32 %b, i32 %c) {
; CHECK-LABEL: define void @test_ab_ac_arg(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]], i32 [[C:%.*]]) {
; CHECK-NEXT:    [[AB:%.*]] = add i32 [[A]], [[B]]
; CHECK-NEXT:    [[AC:%.*]] = add i32 [[A]], [[C]]
; CHECK-NEXT:    [[AC_FREEZE:%.*]] = freeze i32 [[AC]]
; CHECK-NEXT:    [[B_DISTR_OP:%.*]] = mul i32 [[B]], [[AC_FREEZE]]
; CHECK-NEXT:    [[AB_AC:%.*]] = mul i32 [[AB]], [[AC_FREEZE]]
; CHECK-NEXT:    [[ABB_AC:%.*]] = add i32 [[AB_AC]], [[B_DISTR_OP]]
; CHECK-NEXT:    [[ABBB_AC:%.*]] = add i32 [[ABB_AC]], [[B_DISTR_OP]]
; CHECK-NEXT:    call void @f(i32 [[AB_AC]])
; CHECK-NEXT:    call void @f(i32 [[ABB_AC]])
; CHECK-NEXT:    call void @f(i32 [[ABBB_AC]])
; CHECK-NEXT:    ret void
;
  %ab = add i32 %a, %b
  %ac = add i32 %a, %c
  %ab_ac = mul i32 %ab, %ac
  %abb = add i32 %ab, %b
  %abb_ac = mul i32 %abb, %ac
  %abbb = add i32 %abb, %b
  %abbb_ac = mul i32 %abbb, %ac
  call void @f(i32 %ab_ac)
  call void @f(i32 %abb_ac)
  call void @f(i32 %abbb_ac)
  ret void
}

define void @test_ab_multiple_non_conflicting_candidates(i32 %a, i32 %b, i32 %k, i32 %q) {
; CHECK-LABEL: define void @test_ab_multiple_non_conflicting_candidates(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]], i32 [[K:%.*]], i32 [[Q:%.*]]) {
; CHECK-NEXT:    [[Q_FREEZE:%.*]] = freeze i32 [[Q]]
; CHECK-NEXT:    [[B_DISTR_OP2:%.*]] = mul i32 [[B]], [[Q_FREEZE]]
; CHECK-NEXT:    [[AQ:%.*]] = mul i32 [[A]], [[Q_FREEZE]]
; CHECK-NEXT:    [[K_FREEZE:%.*]] = freeze i32 [[K]]
; CHECK-NEXT:    [[B_DISTR_OP:%.*]] = mul i32 [[B]], [[K_FREEZE]]
; CHECK-NEXT:    [[AK:%.*]] = mul i32 [[A]], [[K_FREEZE]]
; CHECK-NEXT:    [[ABQ:%.*]] = add i32 [[AQ]], [[B_DISTR_OP2]]
; CHECK-NEXT:    [[ABK:%.*]] = add i32 [[AK]], [[B_DISTR_OP]]
; CHECK-NEXT:    [[ABBQ:%.*]] = add i32 [[ABQ]], [[B_DISTR_OP2]]
; CHECK-NEXT:    [[ABBK:%.*]] = add i32 [[ABK]], [[B_DISTR_OP]]
; CHECK-NEXT:    call void @f(i32 [[AK]])
; CHECK-NEXT:    call void @f(i32 [[ABK]])
; CHECK-NEXT:    call void @f(i32 [[ABBK]])
; CHECK-NEXT:    call void @f(i32 [[AQ]])
; CHECK-NEXT:    call void @f(i32 [[ABQ]])
; CHECK-NEXT:    call void @f(i32 [[ABBQ]])
; CHECK-NEXT:    ret void
;
  %ak = mul i32 %a, %k
  %aq = mul i32 %a, %q
  %ab = add i32 %a, %b
  %abk = mul i32 %ab, %k
  %abq = mul i32 %ab, %q
  %abb = add i32 %ab, %b
  %abbk = mul i32 %abb, %k
  %abbq = mul i32 %abb, %q
  call void @f(i32 %ak)
  call void @f(i32 %abk)
  call void @f(i32 %abbk)
  call void @f(i32 %aq)
  call void @f(i32 %abq)
  call void @f(i32 %abbq)
  ret void
}

