; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=redistribute -S | FileCheck %s

declare void @f(<2 x i32>)

define void @test_ab_arg(<2 x i32> %a, <2 x i32> %b, <2 x i32> %k) {
; CHECK-LABEL: define void @test_ab_arg(
; CHECK-SAME: <2 x i32> [[A:%.*]], <2 x i32> [[B:%.*]], <2 x i32> [[K:%.*]]) {
; CHECK-NEXT:    [[K_FREEZE:%.*]] = freeze <2 x i32> [[K]]
; CHECK-NEXT:    [[B_DISTR_OP:%.*]] = mul <2 x i32> [[B]], [[K_FREEZE]]
; CHECK-NEXT:    [[AK:%.*]] = mul <2 x i32> [[A]], [[K_FREEZE]]
; CHECK-NEXT:    [[ABK:%.*]] = add <2 x i32> [[AK]], [[B_DISTR_OP]]
; CHECK-NEXT:    [[ABBK:%.*]] = add <2 x i32> [[ABK]], [[B_DISTR_OP]]
; CHECK-NEXT:    call void @f(<2 x i32> [[AK]])
; CHECK-NEXT:    call void @f(<2 x i32> [[ABK]])
; CHECK-NEXT:    call void @f(<2 x i32> [[ABBK]])
; CHECK-NEXT:    ret void
;
  %ak = mul <2 x i32> %a, %k
  %ab = add <2 x i32> %a, %b
  %abk = mul <2 x i32> %ab, %k
  %abb = add <2 x i32> %ab, %b
  %abbk = mul <2 x i32> %abb, %k
  call void @f(<2 x i32> %ak)
  call void @f(<2 x i32> %abk)
  call void @f(<2 x i32> %abbk)
  ret void
}

define void @test_ab_commutative_arg(<2 x i32> %a, <2 x i32> %b, <2 x i32> %k) {
; CHECK-LABEL: define void @test_ab_commutative_arg(
; CHECK-SAME: <2 x i32> [[A:%.*]], <2 x i32> [[B:%.*]], <2 x i32> [[K:%.*]]) {
; CHECK-NEXT:    [[K_FREEZE:%.*]] = freeze <2 x i32> [[K]]
; CHECK-NEXT:    [[B_DISTR_OP:%.*]] = mul <2 x i32> [[B]], [[K_FREEZE]]
; CHECK-NEXT:    [[AK:%.*]] = mul <2 x i32> [[A]], [[K_FREEZE]]
; CHECK-NEXT:    [[ABK:%.*]] = add <2 x i32> [[AK]], [[B_DISTR_OP]]
; CHECK-NEXT:    [[ABBK:%.*]] = add <2 x i32> [[ABK]], [[B_DISTR_OP]]
; CHECK-NEXT:    call void @f(<2 x i32> [[AK]])
; CHECK-NEXT:    call void @f(<2 x i32> [[ABK]])
; CHECK-NEXT:    call void @f(<2 x i32> [[ABBK]])
; CHECK-NEXT:    ret void
;
  %ak = mul <2 x i32> %a, %k
  %ab = add <2 x i32> %a, %b
  %abk = mul <2 x i32> %k, %ab
  %abb = add <2 x i32> %ab, %b
  %abbk = mul <2 x i32> %abb, %k
  call void @f(<2 x i32> %ak)
  call void @f(<2 x i32> %abk)
  call void @f(<2 x i32> %abbk)
  ret void
}

define void @test_aa_arg(<2 x i32> %a, <2 x i32> %k) {
; CHECK-LABEL: define void @test_aa_arg(
; CHECK-SAME: <2 x i32> [[A:%.*]], <2 x i32> [[K:%.*]]) {
; CHECK-NEXT:    [[K_FREEZE:%.*]] = freeze <2 x i32> [[K]]
; CHECK-NEXT:    [[AK:%.*]] = mul <2 x i32> [[A]], [[K_FREEZE]]
; CHECK-NEXT:    [[AAK:%.*]] = add <2 x i32> [[AK]], [[AK]]
; CHECK-NEXT:    [[AAAK:%.*]] = add <2 x i32> [[AAK]], [[AK]]
; CHECK-NEXT:    call void @f(<2 x i32> [[AK]])
; CHECK-NEXT:    call void @f(<2 x i32> [[AAK]])
; CHECK-NEXT:    call void @f(<2 x i32> [[AAAK]])
; CHECK-NEXT:    ret void
;
  %ak = mul <2 x i32> %a, %k
  %aa = add <2 x i32> %a, %a
  %aak = mul <2 x i32> %aa, %k
  %aaa = add <2 x i32> %aa, %a
  %aaak = mul <2 x i32> %aaa, %k
  call void @f(<2 x i32> %ak)
  call void @f(<2 x i32> %aak)
  call void @f(<2 x i32> %aaak)
  ret void
}

define void @test_ab_arg_noundef(<2 x i32> %a, <2 x i32> %b, <2 x i32> noundef %k) {
; CHECK-LABEL: define void @test_ab_arg_noundef(
; CHECK-SAME: <2 x i32> [[A:%.*]], <2 x i32> [[B:%.*]], <2 x i32> noundef [[K:%.*]]) {
; CHECK-NEXT:    [[B_DISTR_OP:%.*]] = mul <2 x i32> [[B]], [[K]]
; CHECK-NEXT:    [[AK:%.*]] = mul <2 x i32> [[A]], [[K]]
; CHECK-NEXT:    [[ABK:%.*]] = add <2 x i32> [[AK]], [[B_DISTR_OP]]
; CHECK-NEXT:    [[ABBK:%.*]] = add <2 x i32> [[ABK]], [[B_DISTR_OP]]
; CHECK-NEXT:    call void @f(<2 x i32> [[AK]])
; CHECK-NEXT:    call void @f(<2 x i32> [[ABK]])
; CHECK-NEXT:    call void @f(<2 x i32> [[ABBK]])
; CHECK-NEXT:    ret void
;
  %ak = mul <2 x i32> %a, %k
  %ab = add <2 x i32> %a, %b
  %abk = mul <2 x i32> %ab, %k
  %abb = add <2 x i32> %ab, %b
  %abbk = mul <2 x i32> %abb, %k
  call void @f(<2 x i32> %ak)
  call void @f(<2 x i32> %abk)
  call void @f(<2 x i32> %abbk)
  ret void
}

define void @test_ab_cd_arg(<2 x i32> %a, <2 x i32> %b, <2 x i32> %c, <2 x i32> %d) {
; CHECK-LABEL: define void @test_ab_cd_arg(
; CHECK-SAME: <2 x i32> [[A:%.*]], <2 x i32> [[B:%.*]], <2 x i32> [[C:%.*]], <2 x i32> [[D:%.*]]) {
; CHECK-NEXT:    [[CD:%.*]] = add <2 x i32> [[C]], [[D]]
; CHECK-NEXT:    [[CD_FREEZE:%.*]] = freeze <2 x i32> [[CD]]
; CHECK-NEXT:    [[B_DISTR_OP:%.*]] = mul <2 x i32> [[B]], [[CD_FREEZE]]
; CHECK-NEXT:    [[AB:%.*]] = add <2 x i32> [[A]], [[B]]
; CHECK-NEXT:    [[ABCD:%.*]] = mul <2 x i32> [[AB]], [[CD_FREEZE]]
; CHECK-NEXT:    [[AB_FREEZE:%.*]] = freeze <2 x i32> [[AB]]
; CHECK-NEXT:    [[D_DISTR_OP:%.*]] = mul <2 x i32> [[D]], [[AB_FREEZE]]
; CHECK-NEXT:    [[CD_DISTR_OP:%.*]] = mul <2 x i32> [[CD]], [[AB_FREEZE]]
; CHECK-NEXT:    [[ACD:%.*]] = mul <2 x i32> [[A]], [[CD]]
; CHECK-NEXT:    [[CAB:%.*]] = mul <2 x i32> [[C]], [[AB]]
; CHECK-NEXT:    [[CDDAB:%.*]] = add <2 x i32> [[CD_DISTR_OP]], [[D_DISTR_OP]]
; CHECK-NEXT:    [[ABBCD:%.*]] = add <2 x i32> [[ABCD]], [[B_DISTR_OP]]
; CHECK-NEXT:    [[ABBBCD:%.*]] = add <2 x i32> [[ABBCD]], [[B_DISTR_OP]]
; CHECK-NEXT:    call void @f(<2 x i32> [[ACD]])
; CHECK-NEXT:    call void @f(<2 x i32> [[ABCD]])
; CHECK-NEXT:    call void @f(<2 x i32> [[ABBCD]])
; CHECK-NEXT:    call void @f(<2 x i32> [[ABBBCD]])
; CHECK-NEXT:    call void @f(<2 x i32> [[CAB]])
; CHECK-NEXT:    call void @f(<2 x i32> [[ABCD]])
; CHECK-NEXT:    call void @f(<2 x i32> [[CDDAB]])
; CHECK-NEXT:    ret void
;
  %cd = add <2 x i32> %c, %d
  %ab = add <2 x i32> %a, %b
  %acd = mul <2 x i32> %a, %cd
  %cab = mul <2 x i32> %c, %ab
  %abcd = mul <2 x i32> %ab, %cd
  %cdd = add <2 x i32> %cd, %d
  %abb = add <2 x i32> %ab, %b
  %abbcd = mul <2 x i32> %abb, %cd
  %cddab = mul <2 x i32> %cdd, %ab
  %abbb = add <2 x i32> %abb, %b
  %abbbcd = mul <2 x i32> %abbb, %cd
  call void @f(<2 x i32> %acd)
  call void @f(<2 x i32> %abcd)
  call void @f(<2 x i32> %abbcd)
  call void @f(<2 x i32> %abbbcd)
  call void @f(<2 x i32> %cab)
  call void @f(<2 x i32> %abcd)
  call void @f(<2 x i32> %cddab)
  ret void
}

define void @test_k_after_ab(<2 x i32> %a, <2 x i32> %b, ptr %p) {
; CHECK-LABEL: define void @test_k_after_ab(
; CHECK-SAME: <2 x i32> [[A:%.*]], <2 x i32> [[B:%.*]], ptr [[P:%.*]]) {
; CHECK-NEXT:    [[K:%.*]] = load <2 x i32>, ptr [[P]], align 8
; CHECK-NEXT:    [[K_FREEZE:%.*]] = freeze <2 x i32> [[K]]
; CHECK-NEXT:    [[B_DISTR_OP:%.*]] = mul <2 x i32> [[B]], [[K_FREEZE]]
; CHECK-NEXT:    [[AK:%.*]] = mul <2 x i32> [[A]], [[K_FREEZE]]
; CHECK-NEXT:    [[ABK:%.*]] = add <2 x i32> [[AK]], [[B_DISTR_OP]]
; CHECK-NEXT:    [[ABBK:%.*]] = add <2 x i32> [[ABK]], [[B_DISTR_OP]]
; CHECK-NEXT:    [[ABBBK:%.*]] = add <2 x i32> [[ABBK]], [[B_DISTR_OP]]
; CHECK-NEXT:    call void @f(<2 x i32> [[AK]])
; CHECK-NEXT:    call void @f(<2 x i32> [[ABK]])
; CHECK-NEXT:    call void @f(<2 x i32> [[ABBK]])
; CHECK-NEXT:    call void @f(<2 x i32> [[ABBBK]])
; CHECK-NEXT:    ret void
;
  %ab = add <2 x i32> %a, %b
  %abb = add <2 x i32> %ab, %b
  %abbb = add <2 x i32> %abb, %b
  %k = load <2 x i32>, ptr %p
  %abbbk = mul <2 x i32> %abbb, %k
  %abbk = mul <2 x i32> %abb, %k
  %abk = mul <2 x i32> %ab, %k
  %ak = mul <2 x i32> %a, %k
  call void @f(<2 x i32> %ak)
  call void @f(<2 x i32> %abk)
  call void @f(<2 x i32> %abbk)
  call void @f(<2 x i32> %abbbk)
  ret void
}

define void @test_constant_fold(<2 x i32> %a) {
; CHECK-LABEL: define void @test_constant_fold(
; CHECK-SAME: <2 x i32> [[A:%.*]]) {
; CHECK-NEXT:    [[AK:%.*]] = mul <2 x i32> [[A]], <i32 7, i32 5>
; CHECK-NEXT:    [[ABK:%.*]] = add <2 x i32> [[AK]], <i32 77, i32 50>
; CHECK-NEXT:    [[ABBK:%.*]] = add <2 x i32> [[ABK]], <i32 77, i32 50>
; CHECK-NEXT:    call void @f(<2 x i32> [[AK]])
; CHECK-NEXT:    call void @f(<2 x i32> [[ABK]])
; CHECK-NEXT:    call void @f(<2 x i32> [[ABBK]])
; CHECK-NEXT:    ret void
;
  %ak = mul <2 x i32> %a, <i32 7, i32 5>
  %ab = add <2 x i32> %a, <i32 11, i32 10>
  %abk = mul <2 x i32> %ab, <i32 7, i32 5>
  %abb = add <2 x i32> %ab, <i32 11, i32 10>
  %abbk = mul <2 x i32> %abb, <i32 7, i32 5>
  call void @f(<2 x i32> %ak)
  call void @f(<2 x i32> %abk)
  call void @f(<2 x i32> %abbk)
  ret void
}

define void @test_ab_ab_arg(<2 x i32> %a, <2 x i32> %b) {
; CHECK-LABEL: define void @test_ab_ab_arg(
; CHECK-SAME: <2 x i32> [[A:%.*]], <2 x i32> [[B:%.*]]) {
; CHECK-NEXT:    [[AB:%.*]] = add <2 x i32> [[A]], [[B]]
; CHECK-NEXT:    [[AB_FREEZE:%.*]] = freeze <2 x i32> [[AB]]
; CHECK-NEXT:    [[B_DISTR_OP:%.*]] = mul <2 x i32> [[B]], [[AB_FREEZE]]
; CHECK-NEXT:    [[AB_AB:%.*]] = mul <2 x i32> [[AB]], [[AB]]
; CHECK-NEXT:    [[ABB:%.*]] = add <2 x i32> [[AB]], [[B]]
; CHECK-NEXT:    [[ABB_AB:%.*]] = mul <2 x i32> [[ABB]], [[AB_FREEZE]]
; CHECK-NEXT:    [[ABBB_AB:%.*]] = add <2 x i32> [[ABB_AB]], [[B_DISTR_OP]]
; CHECK-NEXT:    call void @f(<2 x i32> [[AB_AB]])
; CHECK-NEXT:    call void @f(<2 x i32> [[ABB_AB]])
; CHECK-NEXT:    call void @f(<2 x i32> [[ABBB_AB]])
; CHECK-NEXT:    ret void
;
  %ab = add <2 x i32> %a, %b
  %ab_ab = mul <2 x i32> %ab, %ab
  %abb = add <2 x i32> %ab, %b
  %abb_ab = mul <2 x i32> %abb, %ab
  %abbb = add <2 x i32> %abb, %b
  %abbb_ab = mul <2 x i32> %abbb, %ab
  call void @f(<2 x i32> %ab_ab)
  call void @f(<2 x i32> %abb_ab)
  call void @f(<2 x i32> %abbb_ab)
  ret void
}

define void @test_ab_ac_arg(<2 x i32> %a, <2 x i32> %b, <2 x i32> %c) {
; CHECK-LABEL: define void @test_ab_ac_arg(
; CHECK-SAME: <2 x i32> [[A:%.*]], <2 x i32> [[B:%.*]], <2 x i32> [[C:%.*]]) {
; CHECK-NEXT:    [[AB:%.*]] = add <2 x i32> [[A]], [[B]]
; CHECK-NEXT:    [[AC:%.*]] = add <2 x i32> [[A]], [[C]]
; CHECK-NEXT:    [[AC_FREEZE:%.*]] = freeze <2 x i32> [[AC]]
; CHECK-NEXT:    [[B_DISTR_OP:%.*]] = mul <2 x i32> [[B]], [[AC_FREEZE]]
; CHECK-NEXT:    [[AB_AC:%.*]] = mul <2 x i32> [[AB]], [[AC_FREEZE]]
; CHECK-NEXT:    [[ABB_AC:%.*]] = add <2 x i32> [[AB_AC]], [[B_DISTR_OP]]
; CHECK-NEXT:    [[ABBB_AC:%.*]] = add <2 x i32> [[ABB_AC]], [[B_DISTR_OP]]
; CHECK-NEXT:    call void @f(<2 x i32> [[AB_AC]])
; CHECK-NEXT:    call void @f(<2 x i32> [[ABB_AC]])
; CHECK-NEXT:    call void @f(<2 x i32> [[ABBB_AC]])
; CHECK-NEXT:    ret void
;
  %ab = add <2 x i32> %a, %b
  %ac = add <2 x i32> %a, %c
  %ab_ac = mul <2 x i32> %ab, %ac
  %abb = add <2 x i32> %ab, %b
  %abb_ac = mul <2 x i32> %abb, %ac
  %abbb = add <2 x i32> %abb, %b
  %abbb_ac = mul <2 x i32> %abbb, %ac
  call void @f(<2 x i32> %ab_ac)
  call void @f(<2 x i32> %abb_ac)
  call void @f(<2 x i32> %abbb_ac)
  ret void
}

define void @test_constant_undef(<2 x i32> %a) {
; CHECK-LABEL: define void @test_constant_undef(
; CHECK-SAME: <2 x i32> [[A:%.*]]) {
; CHECK-NEXT:    [[DOTFREEZE:%.*]] = freeze <2 x i32> <i32 7, i32 undef>
; CHECK-NEXT:    [[DOTDISTR_OP:%.*]] = mul <2 x i32> <i32 11, i32 10>, [[DOTFREEZE]]
; CHECK-NEXT:    [[AK:%.*]] = mul <2 x i32> [[A]], [[DOTFREEZE]]
; CHECK-NEXT:    [[ABK:%.*]] = add <2 x i32> [[AK]], [[DOTDISTR_OP]]
; CHECK-NEXT:    [[ABBK:%.*]] = add <2 x i32> [[ABK]], [[DOTDISTR_OP]]
; CHECK-NEXT:    call void @f(<2 x i32> [[AK]])
; CHECK-NEXT:    call void @f(<2 x i32> [[ABK]])
; CHECK-NEXT:    call void @f(<2 x i32> [[ABBK]])
; CHECK-NEXT:    ret void
;
  %ak = mul <2 x i32> %a, <i32 7, i32 undef>
  %ab = add <2 x i32> %a, <i32 11, i32 10>
  %abk = mul <2 x i32> %ab, <i32 7, i32 undef>
  %abb = add <2 x i32> %ab, <i32 11, i32 10>
  %abbk = mul <2 x i32> %abb, <i32 7, i32 undef>
  call void @f(<2 x i32> %ak)
  call void @f(<2 x i32> %abk)
  call void @f(<2 x i32> %abbk)
  ret void
}
