; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=redistribute -redistribute-force-profitable -S | FileCheck %s

declare void @f(i32)
declare i32 @boo(i32)
declare i32 @__gxx_personality_v0(...)

define void @test_ab_diamond(i32 %a, i32 %b, i32 %k) {
; CHECK-LABEL: define void @test_ab_diamond(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]], i32 [[K:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[K_FREEZE:%.*]] = freeze i32 [[K]]
; CHECK-NEXT:    br i1 true, label %[[IF_THEN:.*]], label %[[IF_ELSE:.*]]
; CHECK:       [[IF_THEN]]:
; CHECK-NEXT:    [[AK3:%.*]] = mul i32 [[A]], [[K_FREEZE]]
; CHECK-NEXT:    [[B_DISTR_OP:%.*]] = mul i32 [[B]], [[K_FREEZE]]
; CHECK-NEXT:    [[ABK1:%.*]] = add i32 [[AK3]], [[B_DISTR_OP]]
; CHECK-NEXT:    [[ABBK1:%.*]] = add i32 [[ABK1]], [[B_DISTR_OP]]
; CHECK-NEXT:    call void @f(i32 [[AK3]])
; CHECK-NEXT:    call void @f(i32 [[ABK1]])
; CHECK-NEXT:    call void @f(i32 [[ABBK1]])
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[IF_ELSE]]:
; CHECK-NEXT:    [[AK2:%.*]] = mul i32 [[A]], [[K_FREEZE]]
; CHECK-NEXT:    [[B_K_FREEZE2:%.*]] = mul i32 [[B]], [[K_FREEZE]]
; CHECK-NEXT:    [[ABK2:%.*]] = add i32 [[AK2]], [[B_K_FREEZE2]]
; CHECK-NEXT:    [[ABBK2:%.*]] = add i32 [[ABK2]], [[B_K_FREEZE2]]
; CHECK-NEXT:    call void @f(i32 [[AK2]])
; CHECK-NEXT:    call void @f(i32 [[ABK2]])
; CHECK-NEXT:    call void @f(i32 [[ABBK2]])
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[AK4:%.*]] = mul i32 [[A]], [[K_FREEZE]]
; CHECK-NEXT:    [[B_K_FREEZE1:%.*]] = mul i32 [[B]], [[K_FREEZE]]
; CHECK-NEXT:    [[ABK3:%.*]] = add i32 [[AK4]], [[B_K_FREEZE1]]
; CHECK-NEXT:    [[ABBK3:%.*]] = add i32 [[ABK3]], [[B_K_FREEZE1]]
; CHECK-NEXT:    call void @f(i32 [[AK4]])
; CHECK-NEXT:    call void @f(i32 [[ABK3]])
; CHECK-NEXT:    call void @f(i32 [[ABBK3]])
; CHECK-NEXT:    ret void
;
entry:
  br i1 true, label %if.then, label %if.else
if.then:
  %ak1 = mul i32 %a, %k
  %ab1 = add i32 %a, %b
  %abk1 = mul i32 %ab1, %k
  %abb1 = add i32 %ab1, %b
  %abbk1 = mul i32 %abb1, %k
  call void @f(i32 %ak1)
  call void @f(i32 %abk1)
  call void @f(i32 %abbk1)
  br label %exit
if.else:
  %ak2 = mul i32 %a, %k
  %ab2 = add i32 %a, %b
  %abk2 = mul i32 %ab2, %k
  %abb2 = add i32 %ab2, %b
  %abbk2 = mul i32 %abb2, %k
  call void @f(i32 %ak2)
  call void @f(i32 %abk2)
  call void @f(i32 %abbk2)
  br label %exit
exit:
  %ak3 = mul i32 %a, %k
  %ab3 = add i32 %a, %b
  %abk3 = mul i32 %ab3, %k
  %abb3 = add i32 %ab3, %b
  %abbk3 = mul i32 %abb3, %k
  call void @f(i32 %ak3)
  call void @f(i32 %abk3)
  call void @f(i32 %abbk3)
  ret void
}

define void @test_ab_cross_block(i32 %a, i32 %b, i32 %k) {
; CHECK-LABEL: define void @test_ab_cross_block(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]], i32 [[K:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[K_FREEZE:%.*]] = freeze i32 [[K]]
; CHECK-NEXT:    [[AK:%.*]] = mul i32 [[A]], [[K_FREEZE]]
; CHECK-NEXT:    [[B_DISTR_OP:%.*]] = mul i32 [[B]], [[K_FREEZE]]
; CHECK-NEXT:    [[ABK:%.*]] = add i32 [[AK]], [[B_DISTR_OP]]
; CHECK-NEXT:    call void @f(i32 [[AK]])
; CHECK-NEXT:    br label %[[NEXT:.*]]
; CHECK:       [[NEXT]]:
; CHECK-NEXT:    call void @f(i32 [[ABK]])
; CHECK-NEXT:    [[ABBK:%.*]] = add i32 [[ABK]], [[B_DISTR_OP]]
; CHECK-NEXT:    call void @f(i32 [[ABBK]])
; CHECK-NEXT:    [[ABBBK:%.*]] = add i32 [[ABBK]], [[B_DISTR_OP]]
; CHECK-NEXT:    call void @f(i32 [[ABBBK]])
; CHECK-NEXT:    ret void
;
entry:
  %ak = mul i32 %a, %k
  %ab = add i32 %a, %b
  %abk = mul i32 %ab, %k
  %abb = add i32 %ab, %b
  call void @f(i32 %ak)
  br label %next
next:
  call void @f(i32 %abk)
  %abbk = mul i32 %abb, %k
  call void @f(i32 %abbk)
  %abbb = add i32 %abb, %b
  %abbbk = mul i32 %abbb, %k
  call void @f(i32 %abbbk)
  ret void
}

define void @test_ab_diamond_load(i32 %a, i32 %b, ptr %p) {
; CHECK-LABEL: define void @test_ab_diamond_load(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]], ptr [[P:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[K:%.*]] = load i32, ptr [[P]], align 4
; CHECK-NEXT:    [[K_FREEZE:%.*]] = freeze i32 [[K]]
; CHECK-NEXT:    br i1 true, label %[[IF_THEN:.*]], label %[[IF_ELSE:.*]]
; CHECK:       [[IF_THEN]]:
; CHECK-NEXT:    [[K1:%.*]] = load i32, ptr [[P]], align 4
; CHECK-NEXT:    [[K1_FREEZE:%.*]] = freeze i32 [[K1]]
; CHECK-NEXT:    [[AK1:%.*]] = mul i32 [[A]], [[K1_FREEZE]]
; CHECK-NEXT:    [[B_DISTR_OP:%.*]] = mul i32 [[B]], [[K1_FREEZE]]
; CHECK-NEXT:    [[ABK1:%.*]] = add i32 [[AK1]], [[B_DISTR_OP]]
; CHECK-NEXT:    [[ABBK1:%.*]] = add i32 [[ABK1]], [[B_DISTR_OP]]
; CHECK-NEXT:    call void @f(i32 [[AK1]])
; CHECK-NEXT:    call void @f(i32 [[ABK1]])
; CHECK-NEXT:    call void @f(i32 [[ABBK1]])
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[IF_ELSE]]:
; CHECK-NEXT:    [[AK2:%.*]] = mul i32 [[A]], [[K_FREEZE]]
; CHECK-NEXT:    [[B_DISTR_OP4:%.*]] = mul i32 [[B]], [[K_FREEZE]]
; CHECK-NEXT:    [[ABK2:%.*]] = add i32 [[AK2]], [[B_DISTR_OP4]]
; CHECK-NEXT:    [[ABBK2:%.*]] = add i32 [[ABK2]], [[B_DISTR_OP4]]
; CHECK-NEXT:    call void @f(i32 [[AK2]])
; CHECK-NEXT:    call void @f(i32 [[ABK2]])
; CHECK-NEXT:    call void @f(i32 [[ABBK2]])
; CHECK-NEXT:    br label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[K2:%.*]] = phi i32 [ [[K1]], %[[IF_THEN]] ], [ [[K]], %[[IF_ELSE]] ]
; CHECK-NEXT:    [[K2_FREEZE:%.*]] = freeze i32 [[K2]]
; CHECK-NEXT:    [[AK3:%.*]] = mul i32 [[A]], [[K2_FREEZE]]
; CHECK-NEXT:    [[B_DISTR_OP2:%.*]] = mul i32 [[B]], [[K2_FREEZE]]
; CHECK-NEXT:    [[ABK3:%.*]] = add i32 [[AK3]], [[B_DISTR_OP2]]
; CHECK-NEXT:    [[ABBK3:%.*]] = add i32 [[ABK3]], [[B_DISTR_OP2]]
; CHECK-NEXT:    call void @f(i32 [[AK3]])
; CHECK-NEXT:    call void @f(i32 [[ABK3]])
; CHECK-NEXT:    call void @f(i32 [[ABBK3]])
; CHECK-NEXT:    ret void
;
entry:
  %k = load i32, ptr %p
  br i1 true, label %if.then, label %if.else
if.then:
  %k1 = load i32, ptr %p
  %ak1 = mul i32 %a, %k1
  %ab1 = add i32 %a, %b
  %abk1 = mul i32 %ab1, %k1
  %abb1 = add i32 %ab1, %b
  %abbk1 = mul i32 %abb1, %k1
  call void @f(i32 %ak1)
  call void @f(i32 %abk1)
  call void @f(i32 %abbk1)
  br label %exit
if.else:
  %ak2 = mul i32 %a, %k
  %ab2 = add i32 %a, %b
  %abk2 = mul i32 %ab2, %k
  %abb2 = add i32 %ab2, %b
  %abbk2 = mul i32 %abb2, %k
  call void @f(i32 %ak2)
  call void @f(i32 %abk2)
  call void @f(i32 %abbk2)
  br label %exit
exit:
  %k2 = phi i32 [ %k1, %if.then ], [ %k, %if.else ]
  %ak3 = mul i32 %a, %k2
  %ab3 = add i32 %a, %b
  %abk3 = mul i32 %ab3, %k2
  %abb3 = add i32 %ab3, %b
  %abbk3 = mul i32 %abb3, %k2
  call void @f(i32 %ak3)
  call void @f(i32 %abk3)
  call void @f(i32 %abbk3)
  ret void
}

define void @test_ab_cross_block_load(i32 %a, i32 %b, ptr %p) {
; CHECK-LABEL: define void @test_ab_cross_block_load(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]], ptr [[P:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[K:%.*]] = load i32, ptr [[P]], align 4
; CHECK-NEXT:    [[K_FREEZE:%.*]] = freeze i32 [[K]]
; CHECK-NEXT:    [[AK:%.*]] = mul i32 [[A]], [[K_FREEZE]]
; CHECK-NEXT:    [[B_DISTR_OP:%.*]] = mul i32 [[B]], [[K_FREEZE]]
; CHECK-NEXT:    [[ABK:%.*]] = add i32 [[AK]], [[B_DISTR_OP]]
; CHECK-NEXT:    call void @f(i32 [[AK]])
; CHECK-NEXT:    br label %[[NEXT:.*]]
; CHECK:       [[NEXT]]:
; CHECK-NEXT:    call void @f(i32 [[ABK]])
; CHECK-NEXT:    [[ABBK:%.*]] = add i32 [[ABK]], [[B_DISTR_OP]]
; CHECK-NEXT:    call void @f(i32 [[ABBK]])
; CHECK-NEXT:    [[ABBBK:%.*]] = add i32 [[ABBK]], [[B_DISTR_OP]]
; CHECK-NEXT:    call void @f(i32 [[ABBBK]])
; CHECK-NEXT:    ret void
;
entry:
  %k = load i32, ptr %p
  %ak = mul i32 %a, %k
  %ab = add i32 %a, %b
  %abk = mul i32 %ab, %k
  %abb = add i32 %ab, %b
  call void @f(i32 %ak)
  br label %next
next:
  call void @f(i32 %abk)
  %abbk = mul i32 %abb, %k
  call void @f(i32 %abbk)
  %abbb = add i32 %abb, %b
  %abbbk = mul i32 %abbb, %k
  call void @f(i32 %abbbk)
  ret void
}

define void @test_repetead_ab_use(i32 %a, i32 %b, i32 %k) {
; CHECK-LABEL: define void @test_repetead_ab_use(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]], i32 [[K:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[K_FREEZE:%.*]] = freeze i32 [[K]]
; CHECK-NEXT:    [[AK1:%.*]] = mul i32 [[A]], [[K]]
; CHECK-NEXT:    [[AB:%.*]] = add i32 [[A]], [[B]]
; CHECK-NEXT:    [[ABK:%.*]] = mul i32 [[AB]], [[K_FREEZE]]
; CHECK-NEXT:    br i1 true, label %[[IF_THEN:.*]], label %[[IF_ELSE:.*]]
; CHECK:       [[IF_THEN]]:
; CHECK-NEXT:    [[ABK1:%.*]] = mul i32 [[AB]], [[K]]
; CHECK-NEXT:    [[B_DISTR_OP:%.*]] = mul i32 [[B]], [[K_FREEZE]]
; CHECK-NEXT:    [[ABBK1:%.*]] = add i32 [[ABK]], [[B_DISTR_OP]]
; CHECK-NEXT:    call void @f(i32 [[AK1]])
; CHECK-NEXT:    call void @f(i32 [[ABK1]])
; CHECK-NEXT:    call void @f(i32 [[ABBK1]])
; CHECK-NEXT:    ret void
; CHECK:       [[IF_ELSE]]:
; CHECK-NEXT:    [[B_K_FREEZE1:%.*]] = mul i32 [[B]], [[K_FREEZE]]
; CHECK-NEXT:    [[ABBK2:%.*]] = add i32 [[ABK]], [[B_K_FREEZE1]]
; CHECK-NEXT:    call void @f(i32 [[AK1]])
; CHECK-NEXT:    call void @f(i32 [[ABK]])
; CHECK-NEXT:    call void @f(i32 [[ABBK2]])
; CHECK-NEXT:    ret void
;
entry:
  %ak = mul i32 %a, %k
  %ab = add i32 %a, %b
  %abk = mul i32 %ab, %k
  %abb = add i32 %ab, %b
  br i1 true, label %if.then, label %if.else
if.then:
  %abk1 = mul i32 %ab, %k
  %abb1 = add i32 %ab, %b
  %abbk1 = mul i32 %abb1, %k
  call void @f(i32 %ak)
  call void @f(i32 %abk1)
  call void @f(i32 %abbk1)
  ret void
if.else:
  %abbk2 = mul i32 %abb, %k
  call void @f(i32 %ak)
  call void @f(i32 %abk)
  call void @f(i32 %abbk2)
  ret void
}

define void @test_ab_invoke_k(i32 %a, i32 %b) personality ptr @__gxx_personality_v0 {
; CHECK-LABEL: define void @test_ab_invoke_k(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) personality ptr @__gxx_personality_v0 {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[K:%.*]] = invoke i32 @boo()
; CHECK-NEXT:            to label %[[INVOKE_CONT:.*]] unwind label %[[LPAD:.*]]
; CHECK:       [[INVOKE_CONT]]:
; CHECK-NEXT:    [[K_FREEZE:%.*]] = freeze i32 [[K]]
; CHECK-NEXT:    [[AK3:%.*]] = mul i32 [[A]], [[K_FREEZE]]
; CHECK-NEXT:    [[B_DISTR_OP:%.*]] = mul i32 [[B]], [[K_FREEZE]]
; CHECK-NEXT:    [[ABK1:%.*]] = add i32 [[AK3]], [[B_DISTR_OP]]
; CHECK-NEXT:    [[ABBK1:%.*]] = add i32 [[ABK1]], [[B_DISTR_OP]]
; CHECK-NEXT:    call void @f(i32 [[AK3]])
; CHECK-NEXT:    call void @f(i32 [[ABK1]])
; CHECK-NEXT:    call void @f(i32 [[ABBK1]])
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[LPAD]]:
; CHECK-NEXT:    [[TMP0:%.*]] = landingpad { ptr, i32 }
; CHECK-NEXT:            cleanup
; CHECK-NEXT:    resume { ptr, i32 } [[TMP0]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[AK4:%.*]] = mul i32 [[A]], [[K]]
; CHECK-NEXT:    [[ABK3:%.*]] = add i32 [[AK3]], [[B_DISTR_OP]]
; CHECK-NEXT:    [[ABBK3:%.*]] = add i32 [[ABK3]], [[B_DISTR_OP]]
; CHECK-NEXT:    call void @f(i32 [[AK4]])
; CHECK-NEXT:    call void @f(i32 [[ABK3]])
; CHECK-NEXT:    call void @f(i32 [[ABBK3]])
; CHECK-NEXT:    ret void
;
entry:
  %k = invoke i32 @boo()
  to label %invoke.cont unwind label %lpad
invoke.cont:
  %ak1 = mul i32 %a, %k
  %ab1 = add i32 %a, %b
  %abk1 = mul i32 %ab1, %k
  %abb1 = add i32 %ab1, %b
  %abbk1 = mul i32 %abb1, %k
  call void @f(i32 %ak1)
  call void @f(i32 %abk1)
  call void @f(i32 %abbk1)
  br label %exit
lpad:
  %1 = landingpad { ptr, i32 }
  cleanup
  resume { ptr, i32 } %1
exit:
  %ak3 = mul i32 %a, %k
  %ab3 = add i32 %a, %b
  %abk3 = mul i32 %ab3, %k
  %abb3 = add i32 %ab3, %b
  %abbk3 = mul i32 %abb3, %k
  call void @f(i32 %ak3)
  call void @f(i32 %abk3)
  call void @f(i32 %abbk3)
  ret void
}

define void @test_ab_invoke_b(i32 %a, i32 %k) personality ptr @__gxx_personality_v0 {
; CHECK-LABEL: define void @test_ab_invoke_b(
; CHECK-SAME: i32 [[A:%.*]], i32 [[K:%.*]]) personality ptr @__gxx_personality_v0 {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[K_FREEZE:%.*]] = freeze i32 [[K]]
; CHECK-NEXT:    [[B:%.*]] = invoke i32 @boo()
; CHECK-NEXT:            to label %[[INVOKE_CONT:.*]] unwind label %[[LPAD:.*]]
; CHECK:       [[INVOKE_CONT]]:
; CHECK-NEXT:    [[AK3:%.*]] = mul i32 [[A]], [[K_FREEZE]]
; CHECK-NEXT:    [[B_DISTR_OP:%.*]] = mul i32 [[B]], [[K_FREEZE]]
; CHECK-NEXT:    [[ABK1:%.*]] = add i32 [[AK3]], [[B_DISTR_OP]]
; CHECK-NEXT:    [[ABBK1:%.*]] = add i32 [[ABK1]], [[B_DISTR_OP]]
; CHECK-NEXT:    call void @f(i32 [[AK3]])
; CHECK-NEXT:    call void @f(i32 [[ABK1]])
; CHECK-NEXT:    call void @f(i32 [[ABBK1]])
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[LPAD]]:
; CHECK-NEXT:    [[TMP0:%.*]] = landingpad { ptr, i32 }
; CHECK-NEXT:            cleanup
; CHECK-NEXT:    resume { ptr, i32 } [[TMP0]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[AK4:%.*]] = mul i32 [[A]], [[K]]
; CHECK-NEXT:    [[ABK3:%.*]] = add i32 [[AK3]], [[B_DISTR_OP]]
; CHECK-NEXT:    [[ABBK3:%.*]] = add i32 [[ABK3]], [[B_DISTR_OP]]
; CHECK-NEXT:    call void @f(i32 [[AK4]])
; CHECK-NEXT:    call void @f(i32 [[ABK3]])
; CHECK-NEXT:    call void @f(i32 [[ABBK3]])
; CHECK-NEXT:    ret void
;
entry:
  %b = invoke i32 @boo()
  to label %invoke.cont unwind label %lpad
invoke.cont:
  %ak1 = mul i32 %a, %k
  %ab1 = add i32 %a, %b
  %abk1 = mul i32 %ab1, %k
  %abb1 = add i32 %ab1, %b
  %abbk1 = mul i32 %abb1, %k
  call void @f(i32 %ak1)
  call void @f(i32 %abk1)
  call void @f(i32 %abbk1)
  br label %exit
lpad:
  %1 = landingpad { ptr, i32 }
  cleanup
  resume { ptr, i32 } %1
exit:
  %ak3 = mul i32 %a, %k
  %ab3 = add i32 %a, %b
  %abk3 = mul i32 %ab3, %k
  %abb3 = add i32 %ab3, %b
  %abbk3 = mul i32 %abb3, %k
  call void @f(i32 %ak3)
  call void @f(i32 %abk3)
  call void @f(i32 %abbk3)
  ret void
}

