; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=redistribute -redistribute-force-profitable -S | FileCheck %s --check-prefixes=FORCE
; RUN: opt < %s -passes=redistribute -S | FileCheck %s --check-prefix=SAME_OP_COST
; RUN: %if amdgpu-registered-target %{ opt < %s -passes=redistribute -S -mtriple amdgcn-- -mcpu gfx600 | FileCheck %s --check-prefix=ADD_IS_CHEAPER %}
; RUN: %if amdgpu-registered-target %{ opt < %s -passes=redistribute -S -mtriple amdgcn-- -mcpu gfx1200 | FileCheck %s --check-prefixes=ADD_IS_CHEAPER,HAS_MAD %}

declare void @f(i32)

define void @test_ab_arg(i32 %a, i32 %b, i32 %k) {
; FORCE-LABEL: define void @test_ab_arg(
; FORCE-SAME: i32 [[A:%.*]], i32 [[B:%.*]], i32 [[K:%.*]]) {
; FORCE-NEXT:    [[K_FREEZE:%.*]] = freeze i32 [[K]]
; FORCE-NEXT:    [[AK:%.*]] = mul i32 [[A]], [[K_FREEZE]]
; FORCE-NEXT:    [[TMP1:%.*]] = mul i32 [[B]], [[K_FREEZE]]
; FORCE-NEXT:    [[ABK1:%.*]] = add i32 [[AK]], [[TMP1]]
; FORCE-NEXT:    call void @f(i32 [[AK]])
; FORCE-NEXT:    call void @f(i32 [[ABK1]])
; FORCE-NEXT:    ret void
;
; SAME_OP_COST-LABEL: define void @test_ab_arg(
; SAME_OP_COST-SAME: i32 [[A:%.*]], i32 [[B:%.*]], i32 [[K:%.*]]) {
; SAME_OP_COST-NEXT:    [[AK:%.*]] = mul i32 [[A]], [[K]]
; SAME_OP_COST-NEXT:    [[AB:%.*]] = add i32 [[A]], [[B]]
; SAME_OP_COST-NEXT:    [[ABK:%.*]] = mul i32 [[AB]], [[K]]
; SAME_OP_COST-NEXT:    call void @f(i32 [[AK]])
; SAME_OP_COST-NEXT:    call void @f(i32 [[ABK]])
; SAME_OP_COST-NEXT:    ret void
;
; HAS_MAD-LABEL: define void @test_ab_arg(
; HAS_MAD-SAME: i32 [[A:%.*]], i32 [[B:%.*]], i32 [[K:%.*]]) #[[ATTR0:[0-9]+]] {
; HAS_MAD-NEXT:    [[K_FREEZE:%.*]] = freeze i32 [[K]]
; HAS_MAD-NEXT:    [[AK:%.*]] = mul i32 [[A]], [[K_FREEZE]]
; HAS_MAD-NEXT:    [[B_K_FREEZE:%.*]] = mul i32 [[B]], [[K_FREEZE]]
; HAS_MAD-NEXT:    [[ABK:%.*]] = add i32 [[AK]], [[B_K_FREEZE]]
; HAS_MAD-NEXT:    call void @f(i32 [[AK]])
; HAS_MAD-NEXT:    call void @f(i32 [[ABK]])
; HAS_MAD-NEXT:    ret void
;
  %ak = mul i32 %a, %k
  %ab = add i32 %a, %b
  %abk = mul i32 %ab, %k
  call void @f(i32 %ak)
  call void @f(i32 %abk)
  ret void
}

define void @test_ab_multiple_non_conflicting_candidates(i32 %a, i32 %b, i32 %k, i32 %q) {
; FORCE-LABEL: define void @test_ab_multiple_non_conflicting_candidates(
; FORCE-SAME: i32 [[A:%.*]], i32 [[B:%.*]], i32 [[K:%.*]], i32 [[Q:%.*]]) {
; FORCE-NEXT:    [[AK:%.*]] = mul i32 [[A]], [[K]]
; FORCE-NEXT:    [[AQ:%.*]] = mul i32 [[A]], [[Q]]
; FORCE-NEXT:    [[AB:%.*]] = add i32 [[A]], [[B]]
; FORCE-NEXT:    [[ABK1:%.*]] = mul i32 [[AB]], [[K]]
; FORCE-NEXT:    [[ABQ2:%.*]] = mul i32 [[AB]], [[Q]]
; FORCE-NEXT:    [[ABB:%.*]] = add i32 [[AB]], [[B]]
; FORCE-NEXT:    [[ABBK3:%.*]] = mul i32 [[ABB]], [[K]]
; FORCE-NEXT:    [[ABBQ4:%.*]] = mul i32 [[ABB]], [[Q]]
; FORCE-NEXT:    call void @f(i32 [[AK]])
; FORCE-NEXT:    call void @f(i32 [[ABK1]])
; FORCE-NEXT:    call void @f(i32 [[ABBK3]])
; FORCE-NEXT:    call void @f(i32 [[AQ]])
; FORCE-NEXT:    call void @f(i32 [[ABQ2]])
; FORCE-NEXT:    call void @f(i32 [[ABBQ4]])
; FORCE-NEXT:    ret void
;
; SAME_OP_COST-LABEL: define void @test_ab_multiple_non_conflicting_candidates(
; SAME_OP_COST-SAME: i32 [[A:%.*]], i32 [[B:%.*]], i32 [[K:%.*]], i32 [[Q:%.*]]) {
; SAME_OP_COST-NEXT:    [[AK:%.*]] = mul i32 [[A]], [[K]]
; SAME_OP_COST-NEXT:    [[AQ:%.*]] = mul i32 [[A]], [[Q]]
; SAME_OP_COST-NEXT:    [[AB:%.*]] = add i32 [[A]], [[B]]
; SAME_OP_COST-NEXT:    [[ABK:%.*]] = mul i32 [[AB]], [[K]]
; SAME_OP_COST-NEXT:    [[ABQ:%.*]] = mul i32 [[AB]], [[Q]]
; SAME_OP_COST-NEXT:    [[ABB:%.*]] = add i32 [[AB]], [[B]]
; SAME_OP_COST-NEXT:    [[ABBK:%.*]] = mul i32 [[ABB]], [[K]]
; SAME_OP_COST-NEXT:    [[ABBQ:%.*]] = mul i32 [[ABB]], [[Q]]
; SAME_OP_COST-NEXT:    call void @f(i32 [[AK]])
; SAME_OP_COST-NEXT:    call void @f(i32 [[ABK]])
; SAME_OP_COST-NEXT:    call void @f(i32 [[ABBK]])
; SAME_OP_COST-NEXT:    call void @f(i32 [[AQ]])
; SAME_OP_COST-NEXT:    call void @f(i32 [[ABQ]])
; SAME_OP_COST-NEXT:    call void @f(i32 [[ABBQ]])
; SAME_OP_COST-NEXT:    ret void
;
; ADD_IS_CHEAPER-LABEL: define void @test_ab_multiple_non_conflicting_candidates(
; ADD_IS_CHEAPER-SAME: i32 [[A:%.*]], i32 [[B:%.*]], i32 [[K:%.*]], i32 [[Q:%.*]]) #[[ATTR0:[0-9]+]] {
; ADD_IS_CHEAPER-NEXT:    [[AK:%.*]] = mul i32 [[A]], [[K]]
; ADD_IS_CHEAPER-NEXT:    [[AQ:%.*]] = mul i32 [[A]], [[Q]]
; ADD_IS_CHEAPER-NEXT:    [[AB:%.*]] = add i32 [[A]], [[B]]
; ADD_IS_CHEAPER-NEXT:    [[ABK1:%.*]] = mul i32 [[AB]], [[K]]
; ADD_IS_CHEAPER-NEXT:    [[ABQ2:%.*]] = mul i32 [[AB]], [[Q]]
; ADD_IS_CHEAPER-NEXT:    [[ABB:%.*]] = add i32 [[AB]], [[B]]
; ADD_IS_CHEAPER-NEXT:    [[ABBK3:%.*]] = mul i32 [[ABB]], [[K]]
; ADD_IS_CHEAPER-NEXT:    [[ABBQ4:%.*]] = mul i32 [[ABB]], [[Q]]
; ADD_IS_CHEAPER-NEXT:    call void @f(i32 [[AK]])
; ADD_IS_CHEAPER-NEXT:    call void @f(i32 [[ABK1]])
; ADD_IS_CHEAPER-NEXT:    call void @f(i32 [[ABBK3]])
; ADD_IS_CHEAPER-NEXT:    call void @f(i32 [[AQ]])
; ADD_IS_CHEAPER-NEXT:    call void @f(i32 [[ABQ2]])
; ADD_IS_CHEAPER-NEXT:    call void @f(i32 [[ABBQ4]])
; ADD_IS_CHEAPER-NEXT:    ret void
;
  %ak = mul i32 %a, %k
  %aq = mul i32 %a, %q
  %ab = add i32 %a, %b
  %abk = mul i32 %ab, %k
  %abq = mul i32 %ab, %q
  %abb = add i32 %ab, %b
  %abbk = mul i32 %abb, %k
  %abbq = mul i32 %abb, %q
  call void @f(i32 %ak)
  call void @f(i32 %abk)
  call void @f(i32 %abbk)
  call void @f(i32 %aq)
  call void @f(i32 %abq)
  call void @f(i32 %abbq)
  ret void
}
