; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=redistribute -redistribute-force-profitable -S | FileCheck %s

declare void @f(<2 x i32>)
declare void @f1(<1 x i32>)

define void @test_ab_arg(<2 x i32> %a, <2 x i32> %b, <2 x i32> %k) {
; CHECK-LABEL: define void @test_ab_arg(
; CHECK-SAME: <2 x i32> [[A:%.*]], <2 x i32> [[B:%.*]], <2 x i32> [[K:%.*]]) {
; CHECK-NEXT:    [[K_FREEZE:%.*]] = freeze <2 x i32> [[K]]
; CHECK-NEXT:    [[AK:%.*]] = mul <2 x i32> [[A]], [[K_FREEZE]]
; CHECK-NEXT:    [[B_DISTR_OP:%.*]] = mul <2 x i32> [[B]], [[K_FREEZE]]
; CHECK-NEXT:    [[ABK:%.*]] = add <2 x i32> [[AK]], [[B_DISTR_OP]]
; CHECK-NEXT:    [[ABBK:%.*]] = add <2 x i32> [[ABK]], [[B_DISTR_OP]]
; CHECK-NEXT:    call void @f(<2 x i32> [[AK]])
; CHECK-NEXT:    call void @f(<2 x i32> [[ABK]])
; CHECK-NEXT:    call void @f(<2 x i32> [[ABBK]])
; CHECK-NEXT:    ret void
;
  %ak = mul <2 x i32> %a, %k
  %ab = add <2 x i32> %a, %b
  %abk = mul <2 x i32> %ab, %k
  %abb = add <2 x i32> %ab, %b
  %abbk = mul <2 x i32> %abb, %k
  call void @f(<2 x i32> %ak)
  call void @f(<2 x i32> %abk)
  call void @f(<2 x i32> %abbk)
  ret void
}


define void @test_ab_arg_1(<1 x i32> %a, <1 x i32> %b, <1 x i32> %k) {
; CHECK-LABEL: define void @test_ab_arg_1(
; CHECK-SAME: <1 x i32> [[A:%.*]], <1 x i32> [[B:%.*]], <1 x i32> [[K:%.*]]) {
; CHECK-NEXT:    [[K_FREEZE:%.*]] = freeze <1 x i32> [[K]]
; CHECK-NEXT:    [[AK:%.*]] = mul <1 x i32> [[A]], [[K_FREEZE]]
; CHECK-NEXT:    [[TMP1:%.*]] = mul <1 x i32> [[B]], [[K_FREEZE]]
; CHECK-NEXT:    [[ABK1:%.*]] = add <1 x i32> [[AK]], [[TMP1]]
; CHECK-NEXT:    [[ABBK2:%.*]] = add <1 x i32> [[ABK1]], [[TMP1]]
; CHECK-NEXT:    call void @f1(<1 x i32> [[AK]])
; CHECK-NEXT:    call void @f1(<1 x i32> [[ABK1]])
; CHECK-NEXT:    call void @f1(<1 x i32> [[ABBK2]])
; CHECK-NEXT:    ret void
;
  %ak = mul <1 x i32> %a, %k
  %ab = add <1 x i32> %a, %b
  %abk = mul <1 x i32> %ab, %k
  %abb = add <1 x i32> %ab, %b
  %abbk = mul <1 x i32> %abb, %k
  call void @f1(<1 x i32> %ak)
  call void @f1(<1 x i32> %abk)
  call void @f1(<1 x i32> %abbk)
  ret void
}

define void @test_constant_fold(<2 x i32> %a) {
; CHECK-LABEL: define void @test_constant_fold(
; CHECK-SAME: <2 x i32> [[A:%.*]]) {
; CHECK-NEXT:    [[AK:%.*]] = mul <2 x i32> [[A]], <i32 7, i32 5>
; CHECK-NEXT:    [[ABK:%.*]] = add <2 x i32> [[AK]], <i32 77, i32 50>
; CHECK-NEXT:    [[ABBK:%.*]] = add <2 x i32> [[ABK]], <i32 77, i32 50>
; CHECK-NEXT:    call void @f(<2 x i32> [[AK]])
; CHECK-NEXT:    call void @f(<2 x i32> [[ABK]])
; CHECK-NEXT:    call void @f(<2 x i32> [[ABBK]])
; CHECK-NEXT:    ret void
;
  %ak = mul <2 x i32> %a, <i32 7, i32 5>
  %ab = add <2 x i32> %a, <i32 11, i32 10>
  %abk = mul <2 x i32> %ab, <i32 7, i32 5>
  %abb = add <2 x i32> %ab, <i32 11, i32 10>
  %abbk = mul <2 x i32> %abb, <i32 7, i32 5>
  call void @f(<2 x i32> %ak)
  call void @f(<2 x i32> %abk)
  call void @f(<2 x i32> %abbk)
  ret void
}

define void @test_constant_undef(<2 x i32> %a) {
; CHECK-LABEL: define void @test_constant_undef(
; CHECK-SAME: <2 x i32> [[A:%.*]]) {
; CHECK-NEXT:    [[DOTFREEZE:%.*]] = freeze <2 x i32> <i32 7, i32 undef>
; CHECK-NEXT:    [[AK:%.*]] = mul <2 x i32> [[A]], [[DOTFREEZE]]
; CHECK-NEXT:    [[DOTDISTR_OP:%.*]] = mul <2 x i32> <i32 11, i32 10>, [[DOTFREEZE]]
; CHECK-NEXT:    [[ABK:%.*]] = add <2 x i32> [[AK]], [[DOTDISTR_OP]]
; CHECK-NEXT:    [[ABBK:%.*]] = add <2 x i32> [[ABK]], [[DOTDISTR_OP]]
; CHECK-NEXT:    call void @f(<2 x i32> [[AK]])
; CHECK-NEXT:    call void @f(<2 x i32> [[ABK]])
; CHECK-NEXT:    call void @f(<2 x i32> [[ABBK]])
; CHECK-NEXT:    ret void
;
  %ak = mul <2 x i32> %a, <i32 7, i32 undef>
  %ab = add <2 x i32> %a, <i32 11, i32 10>
  %abk = mul <2 x i32> %ab, <i32 7, i32 undef>
  %abb = add <2 x i32> %ab, <i32 11, i32 10>
  %abbk = mul <2 x i32> %abb, <i32 7, i32 undef>
  call void @f(<2 x i32> %ak)
  call void @f(<2 x i32> %abk)
  call void @f(<2 x i32> %abbk)
  ret void
}
