; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=redistribute -S | FileCheck %s

declare void @f(i32)
declare void @intermediate_use(i32)

define void @test_ab_use_intermediate_first(i32 %a, i32 %b, i32 %k) {
; CHECK-LABEL: define void @test_ab_use_intermediate_first(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]], i32 [[K:%.*]]) {
; CHECK-NEXT:    [[K_FREEZE:%.*]] = freeze i32 [[K]]
; CHECK-NEXT:    [[B_DISTR_OP:%.*]] = mul i32 [[B]], [[K_FREEZE]]
; CHECK-NEXT:    [[AK:%.*]] = mul i32 [[A]], [[K]]
; CHECK-NEXT:    [[AB:%.*]] = add i32 [[A]], [[B]]
; CHECK-NEXT:    [[ABK:%.*]] = mul i32 [[AB]], [[K_FREEZE]]
; CHECK-NEXT:    [[ABBK:%.*]] = add i32 [[ABK]], [[B_DISTR_OP]]
; CHECK-NEXT:    call void @f(i32 [[AK]])
; CHECK-NEXT:    call void @f(i32 [[ABK]])
; CHECK-NEXT:    call void @intermediate_use(i32 [[AB]])
; CHECK-NEXT:    call void @f(i32 [[ABBK]])
; CHECK-NEXT:    ret void
;
  %ak = mul i32 %a, %k
  %ab = add i32 %a, %b
  %abk = mul i32 %ab, %k
  %abb = add i32 %ab, %b
  %abbk = mul i32 %abb, %k
  call void @f(i32 %ak)
  call void @f(i32 %abk)
  call void @intermediate_use(i32 %ab)
  call void @f(i32 %abbk)
  ret void
}

define void @test_ab_use_intermediate_last(i32 %a, i32 %b, i32 %k) {
; CHECK-LABEL: define void @test_ab_use_intermediate_last(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]], i32 [[K:%.*]]) {
; CHECK-NEXT:    [[AK:%.*]] = mul i32 [[A]], [[K]]
; CHECK-NEXT:    [[AB:%.*]] = add i32 [[A]], [[B]]
; CHECK-NEXT:    [[ABK:%.*]] = mul i32 [[AB]], [[K]]
; CHECK-NEXT:    [[ABB:%.*]] = add i32 [[AB]], [[B]]
; CHECK-NEXT:    [[ABBK:%.*]] = mul i32 [[ABB]], [[K]]
; CHECK-NEXT:    call void @f(i32 [[AK]])
; CHECK-NEXT:    call void @f(i32 [[ABK]])
; CHECK-NEXT:    call void @f(i32 [[ABBK]])
; CHECK-NEXT:    call void @intermediate_use(i32 [[ABB]])
; CHECK-NEXT:    ret void
;
  %ak = mul i32 %a, %k
  %ab = add i32 %a, %b
  %abk = mul i32 %ab, %k
  %abb = add i32 %ab, %b
  %abbk = mul i32 %abb, %k
  call void @f(i32 %ak)
  call void @f(i32 %abk)
  call void @f(i32 %abbk)
  call void @intermediate_use(i32 %abb)
  ret void
}

define void @test_ab_use_intermediate_both(i32 %a, i32 %b, i32 %k) {
; CHECK-LABEL: define void @test_ab_use_intermediate_both(
; CHECK-SAME: i32 [[A:%.*]], i32 [[B:%.*]], i32 [[K:%.*]]) {
; CHECK-NEXT:    [[AK:%.*]] = mul i32 [[A]], [[K]]
; CHECK-NEXT:    [[AB:%.*]] = add i32 [[A]], [[B]]
; CHECK-NEXT:    [[ABK:%.*]] = mul i32 [[AB]], [[K]]
; CHECK-NEXT:    [[ABB:%.*]] = add i32 [[AB]], [[B]]
; CHECK-NEXT:    [[ABBK:%.*]] = mul i32 [[ABB]], [[K]]
; CHECK-NEXT:    call void @f(i32 [[AK]])
; CHECK-NEXT:    call void @f(i32 [[ABK]])
; CHECK-NEXT:    call void @intermediate_use(i32 [[AB]])
; CHECK-NEXT:    call void @f(i32 [[ABBK]])
; CHECK-NEXT:    call void @intermediate_use(i32 [[ABB]])
; CHECK-NEXT:    ret void
;
  %ak = mul i32 %a, %k
  %ab = add i32 %a, %b
  %abk = mul i32 %ab, %k
  %abb = add i32 %ab, %b
  %abbk = mul i32 %abb, %k
  call void @f(i32 %ak)
  call void @f(i32 %abk)
  call void @intermediate_use(i32 %ab)
  call void @f(i32 %abbk)
  call void @intermediate_use(i32 %abb)
  ret void
}
