; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=redistribute -redistribute-force-profitable -S | FileCheck %s --check-prefixes=COMMON,FORCE
; RUN: opt < %s -passes=redistribute -S | FileCheck %s --check-prefixes=COMMON,DEFAULT

declare void @f(i32)
declare void @intermediate_use(i32)

define void @test_ab_use_intermediate_first(i32 %a, i32 %b, i32 %k) {
; FORCE-LABEL: define void @test_ab_use_intermediate_first(
; FORCE-SAME: i32 [[A:%.*]], i32 [[B:%.*]], i32 [[K:%.*]]) {
; FORCE-NEXT:    [[K_FREEZE:%.*]] = freeze i32 [[K]]
; FORCE-NEXT:    [[AK:%.*]] = mul i32 [[A]], [[K]]
; FORCE-NEXT:    [[AB:%.*]] = add i32 [[A]], [[B]]
; FORCE-NEXT:    [[ABK:%.*]] = mul i32 [[AB]], [[K_FREEZE]]
; FORCE-NEXT:    [[TMP1:%.*]] = mul i32 [[B]], [[K_FREEZE]]
; FORCE-NEXT:    [[ABBK1:%.*]] = add i32 [[ABK]], [[TMP1]]
; FORCE-NEXT:    call void @f(i32 [[AK]])
; FORCE-NEXT:    call void @f(i32 [[ABK]])
; FORCE-NEXT:    call void @intermediate_use(i32 [[AB]])
; FORCE-NEXT:    call void @f(i32 [[ABBK1]])
; FORCE-NEXT:    ret void
;
; DEFAULT-LABEL: define void @test_ab_use_intermediate_first(
; DEFAULT-SAME: i32 [[A:%.*]], i32 [[B:%.*]], i32 [[K:%.*]]) {
; DEFAULT-NEXT:    [[AK:%.*]] = mul i32 [[A]], [[K]]
; DEFAULT-NEXT:    [[AB:%.*]] = add i32 [[A]], [[B]]
; DEFAULT-NEXT:    [[ABK:%.*]] = mul i32 [[AB]], [[K]]
; DEFAULT-NEXT:    [[ABB:%.*]] = add i32 [[AB]], [[B]]
; DEFAULT-NEXT:    [[ABBK:%.*]] = mul i32 [[ABB]], [[K]]
; DEFAULT-NEXT:    call void @f(i32 [[AK]])
; DEFAULT-NEXT:    call void @f(i32 [[ABK]])
; DEFAULT-NEXT:    call void @intermediate_use(i32 [[AB]])
; DEFAULT-NEXT:    call void @f(i32 [[ABBK]])
; DEFAULT-NEXT:    ret void
;
  %ak = mul i32 %a, %k
  %ab = add i32 %a, %b
  %abk = mul i32 %ab, %k
  %abb = add i32 %ab, %b
  %abbk = mul i32 %abb, %k
  call void @f(i32 %ak)
  call void @f(i32 %abk)
  call void @intermediate_use(i32 %ab)
  call void @f(i32 %abbk)
  ret void
}

define void @test_ab_use_intermediate_last(i32 %a, i32 %b, i32 %k) {
; COMMON-LABEL: define void @test_ab_use_intermediate_last(
; COMMON-SAME: i32 [[A:%.*]], i32 [[B:%.*]], i32 [[K:%.*]]) {
; COMMON-NEXT:    [[AK:%.*]] = mul i32 [[A]], [[K]]
; COMMON-NEXT:    [[AB:%.*]] = add i32 [[A]], [[B]]
; COMMON-NEXT:    [[ABK:%.*]] = mul i32 [[AB]], [[K]]
; COMMON-NEXT:    [[ABB:%.*]] = add i32 [[AB]], [[B]]
; COMMON-NEXT:    [[ABBK:%.*]] = mul i32 [[ABB]], [[K]]
; COMMON-NEXT:    call void @f(i32 [[AK]])
; COMMON-NEXT:    call void @f(i32 [[ABK]])
; COMMON-NEXT:    call void @f(i32 [[ABBK]])
; COMMON-NEXT:    call void @intermediate_use(i32 [[ABB]])
; COMMON-NEXT:    ret void
;
  %ak = mul i32 %a, %k
  %ab = add i32 %a, %b
  %abk = mul i32 %ab, %k
  %abb = add i32 %ab, %b
  %abbk = mul i32 %abb, %k
  call void @f(i32 %ak)
  call void @f(i32 %abk)
  call void @f(i32 %abbk)
  call void @intermediate_use(i32 %abb)
  ret void
}

define void @test_ab_use_intermediate_both(i32 %a, i32 %b, i32 %k) {
; COMMON-LABEL: define void @test_ab_use_intermediate_both(
; COMMON-SAME: i32 [[A:%.*]], i32 [[B:%.*]], i32 [[K:%.*]]) {
; COMMON-NEXT:    [[AK:%.*]] = mul i32 [[A]], [[K]]
; COMMON-NEXT:    [[AB:%.*]] = add i32 [[A]], [[B]]
; COMMON-NEXT:    [[ABK:%.*]] = mul i32 [[AB]], [[K]]
; COMMON-NEXT:    [[ABB:%.*]] = add i32 [[AB]], [[B]]
; COMMON-NEXT:    [[ABBK:%.*]] = mul i32 [[ABB]], [[K]]
; COMMON-NEXT:    call void @f(i32 [[AK]])
; COMMON-NEXT:    call void @f(i32 [[ABK]])
; COMMON-NEXT:    call void @intermediate_use(i32 [[AB]])
; COMMON-NEXT:    call void @f(i32 [[ABBK]])
; COMMON-NEXT:    call void @intermediate_use(i32 [[ABB]])
; COMMON-NEXT:    ret void
;
  %ak = mul i32 %a, %k
  %ab = add i32 %a, %b
  %abk = mul i32 %ab, %k
  %abb = add i32 %ab, %b
  %abbk = mul i32 %abb, %k
  call void @f(i32 %ak)
  call void @f(i32 %abk)
  call void @intermediate_use(i32 %ab)
  call void @f(i32 %abbk)
  call void @intermediate_use(i32 %abb)
  ret void
}
