; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=redistribute -redistribute-force-profitable -S | FileCheck %s --check-prefixes=COMMON,FORCE
; RUN: opt < %s -passes=redistribute -S | FileCheck %s --check-prefixes=COMMON,DEFAULT

declare void @f(i32)
declare void @f1(i1)
declare void @f8(i8)

define void @test_ab_arg(i32 %a, i32 %b, i32 %k) {
; COMMON-LABEL: define void @test_ab_arg(
; COMMON-SAME: i32 [[A:%.*]], i32 [[B:%.*]], i32 [[K:%.*]]) {
; COMMON-NEXT:    [[K_FREEZE:%.*]] = freeze i32 [[K]]
; COMMON-NEXT:    [[AK:%.*]] = mul i32 [[A]], [[K_FREEZE]]
; COMMON-NEXT:    [[B_K_FREEZE:%.*]] = mul i32 [[B]], [[K_FREEZE]]
; COMMON-NEXT:    [[ABK:%.*]] = add i32 [[AK]], [[B_K_FREEZE]]
; COMMON-NEXT:    [[ABBK:%.*]] = add i32 [[ABK]], [[B_K_FREEZE]]
; COMMON-NEXT:    call void @f(i32 [[AK]])
; COMMON-NEXT:    call void @f(i32 [[ABK]])
; COMMON-NEXT:    call void @f(i32 [[ABBK]])
; COMMON-NEXT:    ret void
;
  %ak = mul i32 %a, %k
  %ab = add i32 %a, %b
  %abk = mul i32 %ab, %k
  %abb = add i32 %ab, %b
  %abbk = mul i32 %abb, %k
  call void @f(i32 %ak)
  call void @f(i32 %abk)
  call void @f(i32 %abbk)
  ret void
}

define void @test_ab_commutative_arg(i32 %a, i32 %b, i32 %k) {
; COMMON-LABEL: define void @test_ab_commutative_arg(
; COMMON-SAME: i32 [[A:%.*]], i32 [[B:%.*]], i32 [[K:%.*]]) {
; COMMON-NEXT:    [[K_FREEZE:%.*]] = freeze i32 [[K]]
; COMMON-NEXT:    [[AK:%.*]] = mul i32 [[A]], [[K_FREEZE]]
; COMMON-NEXT:    [[B_K_FREEZE:%.*]] = mul i32 [[B]], [[K_FREEZE]]
; COMMON-NEXT:    [[ABK:%.*]] = add i32 [[AK]], [[B_K_FREEZE]]
; COMMON-NEXT:    [[ABBK:%.*]] = add i32 [[ABK]], [[B_K_FREEZE]]
; COMMON-NEXT:    call void @f(i32 [[AK]])
; COMMON-NEXT:    call void @f(i32 [[ABK]])
; COMMON-NEXT:    call void @f(i32 [[ABBK]])
; COMMON-NEXT:    ret void
;
  %ak = mul i32 %a, %k
  %ab = add i32 %a, %b
  %abk = mul i32 %k, %ab
  %abb = add i32 %ab, %b
  %abbk = mul i32 %abb, %k
  call void @f(i32 %ak)
  call void @f(i32 %abk)
  call void @f(i32 %abbk)
  ret void
}

define void @test_aa_arg(i32 %a, i32 %k) {
; COMMON-LABEL: define void @test_aa_arg(
; COMMON-SAME: i32 [[A:%.*]], i32 [[K:%.*]]) {
; COMMON-NEXT:    [[K_FREEZE:%.*]] = freeze i32 [[K]]
; COMMON-NEXT:    [[AK:%.*]] = mul i32 [[A]], [[K_FREEZE]]
; COMMON-NEXT:    [[AAK1:%.*]] = add i32 [[AK]], [[AK]]
; COMMON-NEXT:    [[AAAK2:%.*]] = add i32 [[AAK1]], [[AK]]
; COMMON-NEXT:    call void @f(i32 [[AK]])
; COMMON-NEXT:    call void @f(i32 [[AAK1]])
; COMMON-NEXT:    call void @f(i32 [[AAAK2]])
; COMMON-NEXT:    ret void
;
  %ak = mul i32 %a, %k
  %aa = add i32 %a, %a
  %aak = mul i32 %aa, %k
  %aaa = add i32 %aa, %a
  %aaak = mul i32 %aaa, %k
  call void @f(i32 %ak)
  call void @f(i32 %aak)
  call void @f(i32 %aaak)
  ret void
}

define void @test_ab_arg_noundef(i32 %a, i32 %b, i32 noundef %k) {
; COMMON-LABEL: define void @test_ab_arg_noundef(
; COMMON-SAME: i32 [[A:%.*]], i32 [[B:%.*]], i32 noundef [[K:%.*]]) {
; COMMON-NEXT:    [[AK:%.*]] = mul i32 [[A]], [[K]]
; COMMON-NEXT:    [[B_K:%.*]] = mul i32 [[B]], [[K]]
; COMMON-NEXT:    [[ABK:%.*]] = add i32 [[AK]], [[B_K]]
; COMMON-NEXT:    [[ABBK:%.*]] = add i32 [[ABK]], [[B_K]]
; COMMON-NEXT:    call void @f(i32 [[AK]])
; COMMON-NEXT:    call void @f(i32 [[ABK]])
; COMMON-NEXT:    call void @f(i32 [[ABBK]])
; COMMON-NEXT:    ret void
;
  %ak = mul i32 %a, %k
  %ab = add i32 %a, %b
  %abk = mul i32 %ab, %k
  %abb = add i32 %ab, %b
  %abbk = mul i32 %abb, %k
  call void @f(i32 %ak)
  call void @f(i32 %abk)
  call void @f(i32 %abbk)
  ret void
}

define void @test_ab_cd_arg(i32 %a, i32 %b, i32 %c, i32 %d) {
; FORCE-LABEL: define void @test_ab_cd_arg(
; FORCE-SAME: i32 [[A:%.*]], i32 [[B:%.*]], i32 [[C:%.*]], i32 [[D:%.*]]) {
; FORCE-NEXT:    [[CD:%.*]] = add i32 [[C]], [[D]]
; FORCE-NEXT:    [[CD_FREEZE:%.*]] = freeze i32 [[CD]]
; FORCE-NEXT:    [[AB:%.*]] = add i32 [[A]], [[B]]
; FORCE-NEXT:    [[AB_FREEZE:%.*]] = freeze i32 [[AB]]
; FORCE-NEXT:    [[ACD:%.*]] = mul i32 [[A]], [[CD]]
; FORCE-NEXT:    [[CAB:%.*]] = mul i32 [[C]], [[AB]]
; FORCE-NEXT:    [[TMP4:%.*]] = mul i32 [[CD]], [[AB_FREEZE]]
; FORCE-NEXT:    [[ABB:%.*]] = add i32 [[AB]], [[B]]
; FORCE-NEXT:    [[ABBCD2:%.*]] = mul i32 [[ABB]], [[CD_FREEZE]]
; FORCE-NEXT:    [[TMP6:%.*]] = mul i32 [[D]], [[AB_FREEZE]]
; FORCE-NEXT:    [[ABBBCD3:%.*]] = add i32 [[TMP4]], [[TMP6]]
; FORCE-NEXT:    [[TMP1:%.*]] = mul i32 [[B]], [[CD_FREEZE]]
; FORCE-NEXT:    [[ABBBCD:%.*]] = add i32 [[ABBCD2]], [[TMP1]]
; FORCE-NEXT:    call void @f(i32 [[ACD]])
; FORCE-NEXT:    call void @f(i32 [[TMP4]])
; FORCE-NEXT:    call void @f(i32 [[ABBCD2]])
; FORCE-NEXT:    call void @f(i32 [[ABBBCD]])
; FORCE-NEXT:    call void @f(i32 [[CAB]])
; FORCE-NEXT:    call void @f(i32 [[TMP4]])
; FORCE-NEXT:    call void @f(i32 [[ABBBCD3]])
; FORCE-NEXT:    ret void
;
; DEFAULT-LABEL: define void @test_ab_cd_arg(
; DEFAULT-SAME: i32 [[A:%.*]], i32 [[B:%.*]], i32 [[C:%.*]], i32 [[D:%.*]]) {
; DEFAULT-NEXT:    [[CD:%.*]] = add i32 [[C]], [[D]]
; DEFAULT-NEXT:    [[CD_FREEZE:%.*]] = freeze i32 [[CD]]
; DEFAULT-NEXT:    [[AB:%.*]] = add i32 [[A]], [[B]]
; DEFAULT-NEXT:    [[ACD:%.*]] = mul i32 [[A]], [[CD]]
; DEFAULT-NEXT:    [[CAB:%.*]] = mul i32 [[C]], [[AB]]
; DEFAULT-NEXT:    [[ABCD:%.*]] = mul i32 [[AB]], [[CD_FREEZE]]
; DEFAULT-NEXT:    [[CDD:%.*]] = add i32 [[CD]], [[D]]
; DEFAULT-NEXT:    [[B_CD_FREEZE:%.*]] = mul i32 [[B]], [[CD_FREEZE]]
; DEFAULT-NEXT:    [[ABBCD:%.*]] = add i32 [[ABCD]], [[B_CD_FREEZE]]
; DEFAULT-NEXT:    [[CDDAB:%.*]] = mul i32 [[CDD]], [[AB]]
; DEFAULT-NEXT:    [[ABBBCD:%.*]] = add i32 [[ABBCD]], [[B_CD_FREEZE]]
; DEFAULT-NEXT:    call void @f(i32 [[ACD]])
; DEFAULT-NEXT:    call void @f(i32 [[ABCD]])
; DEFAULT-NEXT:    call void @f(i32 [[ABBCD]])
; DEFAULT-NEXT:    call void @f(i32 [[ABBBCD]])
; DEFAULT-NEXT:    call void @f(i32 [[CAB]])
; DEFAULT-NEXT:    call void @f(i32 [[ABCD]])
; DEFAULT-NEXT:    call void @f(i32 [[CDDAB]])
; DEFAULT-NEXT:    ret void
;
  %cd = add i32 %c, %d
  %ab = add i32 %a, %b
  %acd = mul i32 %a, %cd
  %cab = mul i32 %c, %ab
  %abcd = mul i32 %ab, %cd
  %cdd = add i32 %cd, %d
  %abb = add i32 %ab, %b
  %abbcd = mul i32 %abb, %cd
  %cddab = mul i32 %cdd, %ab
  %abbb = add i32 %abb, %b
  %abbbcd = mul i32 %abbb, %cd
  call void @f(i32 %acd)
  call void @f(i32 %abcd)
  call void @f(i32 %abbcd)
  call void @f(i32 %abbbcd)
  call void @f(i32 %cab)
  call void @f(i32 %abcd)
  call void @f(i32 %cddab)
  ret void
}

define void @test_k_after_ab(i32 %a, i32 %b, ptr %p) {
; COMMON-LABEL: define void @test_k_after_ab(
; COMMON-SAME: i32 [[A:%.*]], i32 [[B:%.*]], ptr [[P:%.*]]) {
; COMMON-NEXT:    [[AB:%.*]] = add i32 [[A]], [[B]]
; COMMON-NEXT:    [[ABB:%.*]] = add i32 [[AB]], [[B]]
; COMMON-NEXT:    [[ABBB:%.*]] = add i32 [[ABB]], [[B]]
; COMMON-NEXT:    [[K:%.*]] = load i32, ptr [[P]], align 4
; COMMON-NEXT:    [[ABBBK3:%.*]] = mul i32 [[ABBB]], [[K]]
; COMMON-NEXT:    [[ABBK2:%.*]] = mul i32 [[ABB]], [[K]]
; COMMON-NEXT:    [[ABK1:%.*]] = mul i32 [[AB]], [[K]]
; COMMON-NEXT:    [[AK:%.*]] = mul i32 [[A]], [[K]]
; COMMON-NEXT:    call void @f(i32 [[AK]])
; COMMON-NEXT:    call void @f(i32 [[ABK1]])
; COMMON-NEXT:    call void @f(i32 [[ABBK2]])
; COMMON-NEXT:    call void @f(i32 [[ABBBK3]])
; COMMON-NEXT:    ret void
;
  %ab = add i32 %a, %b
  %abb = add i32 %ab, %b
  %abbb = add i32 %abb, %b
  %k = load i32, ptr %p
  %abbbk = mul i32 %abbb, %k
  %abbk = mul i32 %abb, %k
  %abk = mul i32 %ab, %k
  %ak = mul i32 %a, %k
  call void @f(i32 %ak)
  call void @f(i32 %abk)
  call void @f(i32 %abbk)
  call void @f(i32 %abbbk)
  ret void
}

define void @test_constant_fold(i32 %a) {
; COMMON-LABEL: define void @test_constant_fold(
; COMMON-SAME: i32 [[A:%.*]]) {
; COMMON-NEXT:    [[AK:%.*]] = mul i32 [[A]], 7
; COMMON-NEXT:    [[ABK1:%.*]] = add i32 [[AK]], 77
; COMMON-NEXT:    [[ABBK2:%.*]] = add i32 [[ABK1]], 77
; COMMON-NEXT:    call void @f(i32 [[AK]])
; COMMON-NEXT:    call void @f(i32 [[ABK1]])
; COMMON-NEXT:    call void @f(i32 [[ABBK2]])
; COMMON-NEXT:    ret void
;
  %ak = mul i32 %a, 7
  %ab = add i32 %a, 11
  %abk = mul i32 %ab, 7
  %abb = add i32 %ab, 11
  %abbk = mul i32 %abb, 7
  call void @f(i32 %ak)
  call void @f(i32 %abk)
  call void @f(i32 %abbk)
  ret void
}

define void @test_ab_ab_arg(i32 %a, i32 %b) {
; FORCE-LABEL: define void @test_ab_ab_arg(
; FORCE-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; FORCE-NEXT:    [[AB:%.*]] = add i32 [[A]], [[B]]
; FORCE-NEXT:    [[AB_FREEZE:%.*]] = freeze i32 [[AB]]
; FORCE-NEXT:    [[AB_AB:%.*]] = mul i32 [[AB]], [[AB]]
; FORCE-NEXT:    [[ABB:%.*]] = add i32 [[AB]], [[B]]
; FORCE-NEXT:    [[ABBB_AB2:%.*]] = mul i32 [[ABB]], [[AB_FREEZE]]
; FORCE-NEXT:    [[TMP1:%.*]] = mul i32 [[B]], [[AB_FREEZE]]
; FORCE-NEXT:    [[ABBB_AB:%.*]] = add i32 [[ABBB_AB2]], [[TMP1]]
; FORCE-NEXT:    call void @f(i32 [[AB_AB]])
; FORCE-NEXT:    call void @f(i32 [[ABBB_AB2]])
; FORCE-NEXT:    call void @f(i32 [[ABBB_AB]])
; FORCE-NEXT:    ret void
;
; DEFAULT-LABEL: define void @test_ab_ab_arg(
; DEFAULT-SAME: i32 [[A:%.*]], i32 [[B:%.*]]) {
; DEFAULT-NEXT:    [[AB:%.*]] = add i32 [[A]], [[B]]
; DEFAULT-NEXT:    [[AB_AB:%.*]] = mul i32 [[AB]], [[AB]]
; DEFAULT-NEXT:    [[ABB:%.*]] = add i32 [[AB]], [[B]]
; DEFAULT-NEXT:    [[ABB_AB:%.*]] = mul i32 [[ABB]], [[AB]]
; DEFAULT-NEXT:    [[ABBB:%.*]] = add i32 [[ABB]], [[B]]
; DEFAULT-NEXT:    [[ABBB_AB:%.*]] = mul i32 [[ABBB]], [[AB]]
; DEFAULT-NEXT:    call void @f(i32 [[AB_AB]])
; DEFAULT-NEXT:    call void @f(i32 [[ABB_AB]])
; DEFAULT-NEXT:    call void @f(i32 [[ABBB_AB]])
; DEFAULT-NEXT:    ret void
;
  %ab = add i32 %a, %b
  %ab_ab = mul i32 %ab, %ab
  %abb = add i32 %ab, %b
  %abb_ab = mul i32 %abb, %ab
  %abbb = add i32 %abb, %b
  %abbb_ab = mul i32 %abbb, %ab
  call void @f(i32 %ab_ab)
  call void @f(i32 %abb_ab)
  call void @f(i32 %abbb_ab)
  ret void
}

define void @test_ab_ac_arg(i32 %a, i32 %b, i32 %c) {
; COMMON-LABEL: define void @test_ab_ac_arg(
; COMMON-SAME: i32 [[A:%.*]], i32 [[B:%.*]], i32 [[C:%.*]]) {
; COMMON-NEXT:    [[AB:%.*]] = add i32 [[A]], [[B]]
; COMMON-NEXT:    [[AC:%.*]] = add i32 [[A]], [[C]]
; COMMON-NEXT:    [[AC_FREEZE:%.*]] = freeze i32 [[AC]]
; COMMON-NEXT:    [[AB_AC:%.*]] = mul i32 [[AB]], [[AC_FREEZE]]
; COMMON-NEXT:    [[B_AC_FREEZE:%.*]] = mul i32 [[B]], [[AC_FREEZE]]
; COMMON-NEXT:    [[ABB_AC:%.*]] = add i32 [[AB_AC]], [[B_AC_FREEZE]]
; COMMON-NEXT:    [[ABBB_AC:%.*]] = add i32 [[ABB_AC]], [[B_AC_FREEZE]]
; COMMON-NEXT:    call void @f(i32 [[AB_AC]])
; COMMON-NEXT:    call void @f(i32 [[ABB_AC]])
; COMMON-NEXT:    call void @f(i32 [[ABBB_AC]])
; COMMON-NEXT:    ret void
;
  %ab = add i32 %a, %b
  %ac = add i32 %a, %c
  %ab_ac = mul i32 %ab, %ac
  %abb = add i32 %ab, %b
  %abb_ac = mul i32 %abb, %ac
  %abbb = add i32 %abb, %b
  %abbb_ac = mul i32 %abbb, %ac
  call void @f(i32 %ab_ac)
  call void @f(i32 %abb_ac)
  call void @f(i32 %abbb_ac)
  ret void
}

define void @test_ab_multiple_non_conflicting_candidates(i32 %a, i32 %b, i32 %k, i32 %q) {
; COMMON-LABEL: define void @test_ab_multiple_non_conflicting_candidates(
; COMMON-SAME: i32 [[A:%.*]], i32 [[B:%.*]], i32 [[K:%.*]], i32 [[Q:%.*]]) {
; COMMON-NEXT:    [[AK:%.*]] = mul i32 [[A]], [[K]]
; COMMON-NEXT:    [[AQ:%.*]] = mul i32 [[A]], [[Q]]
; COMMON-NEXT:    [[AB:%.*]] = add i32 [[A]], [[B]]
; COMMON-NEXT:    [[ABK:%.*]] = mul i32 [[AB]], [[K]]
; COMMON-NEXT:    [[ABQ:%.*]] = mul i32 [[AB]], [[Q]]
; COMMON-NEXT:    [[ABB:%.*]] = add i32 [[AB]], [[B]]
; COMMON-NEXT:    [[ABBK:%.*]] = mul i32 [[ABB]], [[K]]
; COMMON-NEXT:    [[ABBQ:%.*]] = mul i32 [[ABB]], [[Q]]
; COMMON-NEXT:    call void @f(i32 [[AK]])
; COMMON-NEXT:    call void @f(i32 [[ABK]])
; COMMON-NEXT:    call void @f(i32 [[ABBK]])
; COMMON-NEXT:    call void @f(i32 [[AQ]])
; COMMON-NEXT:    call void @f(i32 [[ABQ]])
; COMMON-NEXT:    call void @f(i32 [[ABBQ]])
; COMMON-NEXT:    ret void
;
  %ak = mul i32 %a, %k
  %aq = mul i32 %a, %q
  %ab = add i32 %a, %b
  %abk = mul i32 %ab, %k
  %abq = mul i32 %ab, %q
  %abb = add i32 %ab, %b
  %abbk = mul i32 %abb, %k
  %abbq = mul i32 %abb, %q
  call void @f(i32 %ak)
  call void @f(i32 %abk)
  call void @f(i32 %abbk)
  call void @f(i32 %aq)
  call void @f(i32 %abq)
  call void @f(i32 %abbq)
  ret void
}

define void @test_ab_arg_i1(i1 %a, i1 %b, i1 %k) {
; COMMON-LABEL: define void @test_ab_arg_i1(
; COMMON-SAME: i1 [[A:%.*]], i1 [[B:%.*]], i1 [[K:%.*]]) {
; COMMON-NEXT:    [[K_FREEZE:%.*]] = freeze i1 [[K]]
; COMMON-NEXT:    [[AK:%.*]] = mul i1 [[A]], [[K_FREEZE]]
; COMMON-NEXT:    [[B_K_FREEZE:%.*]] = mul i1 [[B]], [[K_FREEZE]]
; COMMON-NEXT:    [[ABK:%.*]] = add i1 [[AK]], [[B_K_FREEZE]]
; COMMON-NEXT:    [[ABBK:%.*]] = add i1 [[ABK]], [[B_K_FREEZE]]
; COMMON-NEXT:    call void @f1(i1 [[AK]])
; COMMON-NEXT:    call void @f1(i1 [[ABK]])
; COMMON-NEXT:    call void @f1(i1 [[ABBK]])
; COMMON-NEXT:    ret void
;
  %ak = mul i1 %a, %k
  %ab = add i1 %a, %b
  %abk = mul i1 %ab, %k
  %abb = add i1 %ab, %b
  %abbk = mul i1 %abb, %k
  call void @f1(i1 %ak)
  call void @f1(i1 %abk)
  call void @f1(i1 %abbk)
  ret void
}

define void @test_ab_arg_i8(i8 %a, i8 %b, i8 %k) {
; COMMON-LABEL: define void @test_ab_arg_i8(
; COMMON-SAME: i8 [[A:%.*]], i8 [[B:%.*]], i8 [[K:%.*]]) {
; COMMON-NEXT:    [[K_FREEZE:%.*]] = freeze i8 [[K]]
; COMMON-NEXT:    [[AK:%.*]] = mul i8 [[A]], [[K_FREEZE]]
; COMMON-NEXT:    [[B_K_FREEZE:%.*]] = mul i8 [[B]], [[K_FREEZE]]
; COMMON-NEXT:    [[ABK:%.*]] = add i8 [[AK]], [[B_K_FREEZE]]
; COMMON-NEXT:    [[ABBK:%.*]] = add i8 [[ABK]], [[B_K_FREEZE]]
; COMMON-NEXT:    call void @f1(i8 [[AK]])
; COMMON-NEXT:    call void @f1(i8 [[ABK]])
; COMMON-NEXT:    call void @f1(i8 [[ABBK]])
; COMMON-NEXT:    ret void
;
  %ak = mul i8 %a, %k
  %ab = add i8 %a, %b
  %abk = mul i8 %ab, %k
  %abb = add i8 %ab, %b
  %abbk = mul i8 %abb, %k
  call void @f1(i8 %ak)
  call void @f1(i8 %abk)
  call void @f1(i8 %abbk)
  ret void
}
